# Verbal Reasoning · Topic 50 · Writing Task · part C: the language rubric, part 2.
# Source: writing_src/seg10-seg14 (correctness and style, syntactic structures and punctuation, organizational tools,
# language richness), adapted to English; official facts from nite_verbal_guide.txt; lessons from findings.md #25-#27.
# All example sentences are original (the camera and tax examples are the teacher's own running examples).
from dsl import *
from writing_assets import ANSWER_SHEET

T50 = 50


# ---------------------------------------------------------------- slide helpers
def S(label, text, size=40, gap=30):
    """A key statement."""
    return A(label, T(text, size=size, gap=gap))


def N(label, text, size=30, gap=26):
    """A note / explanation line."""
    return A(label, T(text, size=size, gap=gap))


def X(text, size=31, label='The wrong version appears'):
    return A(label, T('✗  ' + text, size=size, gap=12))


def V(text, size=31, label='The corrected version appears', gap=34):
    return A(label, T('✓  ' + text, size=size, gap=gap))


def PARA(label, text, size=28, gap=26):
    """A full example paragraph (one per slide)."""
    return A(label, T(text, size=size, w=1140, gap=gap))


# ---------------------------------------------------------------- sidebars
SB_STYLE = ['Correct, not perfect', 'Correctness + style', 'Trying to impress', '"In case" means if?',
            '"Also" / "Plus"', 'Spoken forms', 'Say it once', '"In my opinion"', 'One register',
            'Spelling']

SB_GRAMMAR = ['Why grammar matters', 'Articles', 'Relative clauses', 'When / if missing',
              'Comparatives', 'Agreement', 'Pronoun reference', 'Tense', 'Missing negatives',
              'Parallel structure', 'Hebrew-speaker traps']

SB_SENT = ['No terminology', 'Too short', 'Too long', 'The breath test', 'The fixed paragraph',
           'Punctuation = strings', 'Period and comma', 'Comma splices', 'Semicolon and colon',
           'Dash and brackets', 'Quotation marks', '? and !', 'Allowed in an essay?']

SB_ORG = ['Three tools', 'What connectors do', 'An example', 'Know your connectors',
          'Relationship first', 'Connectors by type', 'Paragraph openers',
          'Paragraphs have jobs', 'Transition sentences', 'One argument each?', 'On the page']

SB_RICH = ['Not in the rubric?', 'Repetition', 'Referring words', 'The paragraph, fixed',
           'Raising the register', 'Not flowery', 'Practice']


MODULES = [
# ============================================================ lesson 1: correctness and style (seg10, first part)
lesson('vr50-c-style', 'Correctness and Style', SB_STYLE, [
 dict(mode='title', title='Correctness and Style', script=[
  "Correctness and style.",
  "We're continuing through the language rubric, and this lesson is about writing correct, academic English.",
  "Not perfect English. Correct and clear. You'll see the difference in a minute.",
 ]),
 dict(mode='concept', active=0, title='Correct, not perfect', script=[
  "Correctness means using the language according to its accepted rules, the grammar you learned at school.",
  "But remember: correct, not perfect. A small number of minor slips is not what brings your score down.",
  S("Don't let perfectionism slow you down appears", 'Do not let perfectionism stop you from starting, or slow you down', size=40),
  "Don't let perfectionism make it hard to start, or make you write too slowly.",
  N("Clear language first appears", 'Clear language with an occasional small error  >  a perfect sentence you never finished', size=32),
  "Write clearly. If there's an occasional small error, that's fine. What we fix are the errors that change the meaning, and the ones that sound wrong to an academic reader.",
 ]),
 dict(mode='concept', active=1, title='Correctness + style', script=[
  "You'll notice the title says correctness and style.",
  S("Language criteria appear", 'The language rubric: clarity and academic style · precise words · correct grammar · varied sentences · organizational tools', size=34),
  "In the language rubric, correctness is its own criterion. Style isn't listed as a separate word, but it's there, inside clarity and consistency with academic writing.",
  S("Style = academic register appears", 'Style = vocabulary, level and phrasing that suit academic writing', size=38),
  "Style means using vocabulary, a language level, and phrasing that fit academic writing.",
  N("Academic English basics appear", 'No contractions (do not, it is) · no slang · no "you" addressing the reader · no rhetorical questions', size=32),
  "In English that means: no contractions, no slang, no talking to the reader as 'you', and no rhetorical questions.",
  N("A mismatch jumps out appears", 'A reader used to academic texts notices a wrong register immediately', size=32),
  "And by the way, when someone writes in a style that doesn't fit academic writing, it really jars.",
  "A rater reads academic texts all day. When the style is different, it jumps right out.",
  "Now, the first part of correctness is common mistakes. We collected mistakes that students make again and again.",
  "They don't necessarily come from a low level of English. Sometimes you just don't know the rule, or you didn't notice, or you had no time to proofread.",
  "Let's go through them, so you can avoid them.",
 ]),
 dict(mode='concept', active=2, title='Trying to impress', script=[
  "Let's start with one of the most common sources of mistakes: trying to sound more formal than you need to.",
  S("Sounding 'higher' can make it wrong appears", 'Many errors come from trying to sound more formal', size=40),
  "Some words feel formal, so people use them to raise their language, and end up with a mistake.",
  X('My classmates and myself believe that the proposal is mistaken.'),
  V('My classmates and I believe that the proposal is mistaken.'),
  "'Myself' sounds formal to many people. But here the correct word is simply 'I'. 'Myself' only works when you already used 'I' in the sentence: 'I taught myself'.",
  X('The minister of transport is the one whom is responsible for road safety.'),
  V('The minister of transport is responsible for road safety.'),
  "Same thing with 'whom'. It sounds impressive, so people put it in the wrong place. Here we need 'who', and even better, just drop the extra words.",
  N("Simple and correct appears", 'Not sure a formal word is correct?  Use the simple one.', size=34),
  "If you're not sure a formal-sounding word is correct, use the simple one. It will never cost you points.",
 ]),
 dict(mode='concept', active=3, title='"In case" means if?', script=[
  "Another very common one. People use it every day, in emails and letters, when they want to sound a little more official.",
  X('In case the state cancels plea deals, the courts will not be able to function.', size=30),
  "What do we actually want to say here? 'If the city cancels'. Right? So let's write 'if'.",
  V('If the state cancels plea deals, the courts will not be able to function at all.', size=30),
  N("In case = as a precaution appears", '"In case" means as a precaution:  Take an umbrella in case it rains.', size=31),
  "'In case' means something else. It means as a precaution. 'Take an umbrella in case it rains'. You take the umbrella whether it rains or not.",
  X('Some women will be harmed in case the law protecting pregnant workers is cancelled.', size=30),
  V('Some women will be harmed if the law protecting pregnant workers is cancelled.', size=30),
  "Here too: 'if'. Simple. Don't complicate it.",
  S("Condition = if appears", 'A condition?  Write "if".  Not "in case", not "in the event that".', size=36),
  "The same goes for 'in the event that'. It isn't wrong, but it's heavy. When you mean a condition, write 'if'.",
  N("Being that / due to appear", '"being that ..." →  because ...     "due to it harms ..." →  because it harms ...', size=31),
  "And a close relative: 'being that' as a way of saying 'because'. 'Being that these events harm residents'. That's not standard. Write 'because' or 'since'.",
  X('Mass sporting events should not be held in city centres due to they harm residents.', size=30),
  V('Mass sporting events should not be held in city centres because they harm residents.', size=30),
  "'Due to' takes a noun: 'due to the noise'. Before a full clause, with a subject and a verb, use 'because'.",
 ]),
 dict(mode='concept', active=4, title='"Also" / "Plus"', script=[
  "This next one isn't an absolute error, but it's less accepted in academic writing.",
  X('Plus, relying on emotions when buying things may cause consumers to waste money.', size=30),
  X('Also, relying on emotions when buying things may cause consumers to waste money.', size=30, label='A second weak version appears'),
  "'Plus' at the start of a sentence is spoken English. 'Also' at the start is weak and a bit informal.",
  V('In addition, relying on emotional considerations when making purchases may lead consumers to waste money.', size=30),
  "Better: 'In addition', 'Moreover', 'Furthermore'.",
  N("Also inside the sentence appears", '"Also" is fine inside the sentence:  Such purchases may also lead ...', size=31),
  "'Also' is completely fine inside the sentence: 'such purchases may also lead to debt'. Just don't open with it.",
 ]),
 dict(mode='concept', active=5, title='Spoken forms', script=[
  "Now, a mistake that comes from the way we speak. We already said: no contractions. But there's more to it.",
  X("I'll demonstrate a case where a paternalistic law hurts society as a whole:", size=30),
  V('One case in which a paternalistic law harms society as a whole is the following:', size=30),
  "Full forms, of course. But notice the second improvement. We didn't need 'I will demonstrate' at all. Just present the case.",
  "Don't say the same thing twice. Which brings us to the next topic.",
 ]),
 dict(mode='concept', active=6, title='Say it once', script=[
  "Redundancy, and phrases that add nothing.",
  N("Empty phrases appear", '"This is a complex issue."   "This is not a simple dilemma."   "A significant proposal."', size=32),
  "'This is a complex issue.' OK... and? How does that move forward what I want to say?",
  "'This is not a simple dilemma.' Fine. And? It doesn't help, it doesn't contribute anything.",
  "'A significant proposal.' Really.",
  N("Double words appear", '"logical and reasonable"   ·   "good, proper and right"   ·   "unnecessary and harmful"', size=32),
  "'Logical and reasonable' is repetition. It's the same word twice.",
  "'Good, proper and right.' We say things like that when we speak, to add emphasis. In academic writing it doesn't fit.",
  N("Fillers appear", '"Basically, this law is supposed to ..."  →  "This law is supposed to ..."', size=32),
  "And fillers: 'basically', 'actually', 'in fact', 'literally'. 'Basically, this law is supposed to...' Why write 'basically'? Just drop it.",
  S("Every word must do a job appears", 'If a word does not add meaning, delete it', size=40),
 ]),
 dict(mode='concept', active=7, title='"In my opinion"', script=[
  "More examples, this time with 'in my opinion'. This one is a classic for Hebrew speakers.",
  X('In my opinion I think that ...'),
  X('In my personal opinion ...', label='A second wrong version appears'),
  X('According to me ... / According to my opinion ...', label='A third wrong version appears'),
  "'In my opinion I think' says it twice. 'My personal opinion': obviously your opinion is personal. It's not someone else's.",
  "'According to me' and 'according to my opinion' aren't English. They're translated word for word.",
  V('In my opinion, ...    I believe that ...    I would argue that ...'),
  "Pick one: 'In my opinion', with a comma. Or 'I believe that'. Or 'I would argue that'.",
  N("Other ways appear", 'Also possible:  "My view is that ..."   ·   "It seems to me that ..."', size=32),
  "Other options: 'My view is that', or, a bit softer, 'It seems to me that'.",
  N("Once is enough appears", 'Where it goes: the position in the opening, and the start of each key sentence. Inside the development, hedge (may, is likely to) instead of repeating it.', size=30),
  "Where does it go? Once when you state your position, and at the start of each key sentence. Inside the development, don't repeat it. Hedge instead: may, is likely to.",
 ]),
 dict(mode='concept', active=8, title='One register', script=[
  "Now I want to talk about fixed 'fancy' phrases.",
  N("Forced phrases appear", '"It is my contention that ..."   "Some would posit that ..."   "Herein lies ..."', size=32),
  "In many cases, students try to raise the language artificially with a few fixed phrases like these.",
  "These are places where the formal phrase doesn't really add anything to the content.",
  S("Guide: avoid needlessly difficult language appears", 'The official guide: avoid flowery and needlessly difficult language', size=38),
  "And the official guide says it explicitly: avoid flowery, needlessly difficult language. It makes the text heavy and harder to understand.",
  "Formal language belongs where it adds to the content.",
  "And I'll tell you this: if a rater sees that all your high-level words are these fixed phrases, you won't get a high language score.",
  S("Keep one register appears", 'The register must stay uniform through the whole essay', size=40),
  "The guide asks for a uniform style. What does that mean?",
  N("Simple throughout / high throughout appears", 'Writing in plain, clear English?  Keep it that way. Do not drop in one fancy phrase.  Writing at a high level throughout?  Then such phrases fit.', size=30),
  "If you write in relatively simple, clear English, keep the whole essay in that English. Don't suddenly insert 'it is my contention'. That creates a mixed register, and it hurts your score.",
  "If your whole essay is written at a high level, with rich vocabulary everywhere, then these phrases fit in, and there's no problem using them.",
 ]),
 dict(mode='concept', active=9, title='Spelling', script=[
  "Spelling mistakes.",
  S("Spelling is not a rubric criterion appears", 'Spelling is not one of the criteria in the language rubric', size=40),
  "First of all, spelling isn't one of the criteria in the language rubric. Some students have dyslexia, and the test is not meant to penalize them for it.",
  "But don't take that as permission to be careless. Here are some common confusions, both for the essay and for life in general.",
  N("Pairs with different meanings appear", 'its (belonging to it)  /  it\'s (it is)    ·    their / there / they\'re    ·    than / then', size=31),
  "Its without an apostrophe means belonging to it. It's with an apostrophe means 'it is', and we already said no contractions, so in the essay you almost always want 'its'.",
  N("More pairs appear", 'affect (verb) / effect (noun)    ·    lose / loose    ·    whether / weather', size=31),
  "Affect is usually the verb, effect is usually the noun: 'the law affects workers', 'the law has an effect on workers'.",
  N("Similar words, different meanings appear", 'discriminate against (treat unfairly)  /  distinguish between (tell apart)    ·    principle / principal', size=31),
  "And watch out for pairs where both words exist but mean different things.",
  "To discriminate against a group means to treat it unfairly. To distinguish between things means to tell them apart, like distinguishing between opinion and fact.",
  S("Wrong word = wrong meaning appears", 'Here the problem is not spelling but precision: the wrong word says something else', size=34),
  "And that one isn't just spelling anymore. That's precision. The wrong word says something you didn't mean.",
 ]),
], T50),

# ============================================================ lesson 2: grammar that changes meaning (seg10, second part)
lesson('vr50-c-grammar', 'Grammar That Changes Meaning', SB_GRAMMAR, [
 dict(mode='title', title='Grammar That Changes Meaning', script=[
  "Grammar that changes meaning.",
  "We're not going to study grammar terminology. We'll look at examples, and from the examples you'll understand.",
  "And we'll focus on the mistakes that matter most: the ones that change what your sentence says.",
 ]),
 dict(mode='concept', active=0, title='Why grammar matters', script=[
  S("Grammar is part of the reasoning appears", 'Some grammar errors make the reader misunderstand your argument', size=40),
  "Some grammar mistakes just sound a little off. Others make the reader misunderstand your argument.",
  N("Who acts, what causes what, what you support appears", 'Who does what?   What causes what?   Which side do you support?', size=34),
  "Who does what, what causes what, which side you're on. One wrong pronoun or one missing 'not' can flip all of that.",
  N("Those errors first appear", 'In proofreading, look first for errors that change the meaning', size=34),
  "So when you proofread, those are the mistakes you hunt for first.",
 ]),
 dict(mode='concept', active=1, title='Articles', script=[
  "Let's start with articles: 'a', 'an', 'the'. Hebrew has 'the' but no 'a', so this is where Hebrew speakers slip most.",
  X('The people think that the technology will solve the every problem.'),
  "'The people' means a specific group of people we already mentioned. When you talk about people in general, there's no 'the'.",
  V('Many people believe that technology will solve every problem.'),
  "Same for 'technology', 'society', 'education' in general: no 'the'. 'Technology changes society', not 'the technology changes the society'.",
  X('Government should build new hospital in periphery.', label='Missing articles appear'),
  V('The government should build a new hospital in the periphery.'),
  "And the other direction: a single countable thing needs 'a' or 'the'. 'A new hospital', 'the government'.",
  N("Two nouns together appear", '"the city council" · "the school principal" · "government offices" (not "the offices government")', size=31),
  "When two nouns go together, like 'city council', the article comes once, at the front: 'the city council'.",
  X('Some argue that there is logic in moving the offices government to the periphery.', size=30, label='The wrong word order appears'),
  V('Some argue that there is logic in moving government offices to the periphery.', size=30),
 ]),
 dict(mode='concept', active=2, title='Relative clauses', script=[
  "Now some common sentence-structure mistakes.",
  X('This is the topic that the book deals with it.'),
  "Look at the 'it' at the end. In Hebrew that's natural. In English, the 'that' already refers to the topic, so the 'it' repeats it.",
  V('This is the topic that the book deals with.   /   the topic with which the book deals'),
  X('The claim that according to it there is no need for the law is unjustified.', size=30, label='A second wrong version appears'),
  V('The claim that there is no need for the law is unjustified.', size=30),
  "When you explain what a claim says: 'the claim that', and then the content. Simple.",
  X('Citizens which do this will live in safety.', label='The wrong relative word appears'),
  V('Citizens who do this will live in safety.'),
  N("who / which / that appears", 'who = people   ·   which = things   ·   that = both', size=36),
  "'Who' for people, 'which' for things, and 'that' works for both. If you're not sure, 'that' is the safe choice.",
 ]),
 dict(mode='concept', active=3, title='When / if missing', script=[
  "And pay attention to the next sentence. This one is very common.",
  X('Robots will be able to replace people in many tasks, the population will be different from what it is now.', size=30),
  "What's missing here? The small word that shows the first part is a time or a condition.",
  V('When robots are able to replace people in many tasks, the population will be different from what it is now.', size=30),
  "'When robots are able to'. Don't forget the 'when'. It tells the reader that the first part is the situation, and the second part is what follows from it.",
  X('Citizens go out to protest, the government will make changes.', label='A second wrong version appears'),
  V('If citizens go out to protest, the government will make changes.'),
  N("Without it: two sentences glued by a comma appears", 'Without "when" or "if", you have two full sentences joined only by a comma. That is a comma splice.', size=31),
  "Without the 'when' or 'if', you have two complete sentences joined by nothing but a comma. That's called a comma splice, and we'll come back to it in the punctuation lesson.",
 ]),
 dict(mode='concept', active=4, title='Comparatives', script=[
  "Comparatives. This is very, very common.",
  X('If the number of terms a mayor can serve is limited, the fight against corruption will be more better.', size=30),
  "'More better' is a double comparative. 'Better' already means 'more good'.",
  V('If the number of terms a mayor can serve is limited, the fight against corruption will be more effective than it is today.', size=30),
  "And once you've written a comparative, it's recommended to add: better than what? More effective than it is today.",
  X('I believe that the situation of democratic countries is much more better.', size=30, label='A second wrong version appears'),
  V('I believe that the situation of democratic countries is much better than that of dictatorships.', size=30),
  "Here we had 'much more better'. The fix: 'much better'. And again: better than what? 'Than that of dictatorships'.",
  S("Comparative + than appears", 'better / much better / more effective  +  than ...', size=40),
  "So: better, or much better, never 'more better'. And complete the comparison.",
 ]),
 dict(mode='concept', active=5, title='Agreement', script=[
  "Agreement. The subject and the verb must match: singular with singular, plural with plural.",
  X('Belonging to a group are the main concern of teenagers.'),
  V('Belonging to a group is the main concern of teenagers.'),
  "'Belonging' is one thing, singular. So: 'is'. A sentence like this costs points, because the mismatch is right there, next to the subject. It really jars.",
  N("A distant mismatch appears", '"In some cases, the universities that joined the new initiative and opened their doors to applicants without a matriculation certificate did so only because it wants to increase its number of students."', size=28),
  "Now another example. The universities... and at the end, 'because it wants to increase its number of students'.",
  "'Universities' is plural, so it should be 'they want' and 'their students'.",
  V('... did so only because they want to increase their number of students.', size=30),
  N("Distance hides the mismatch appears", 'Far from the subject, the slip is less jarring, but it is still a mistake. Check it in proofreading.', size=30),
  "Here it's less certain you'll lose points. Why? Because of the distance. By the time we get to 'it', we've gone through a sentence and a half, so the mismatch is less noticeable.",
  "The first kind of mistake, right next to the subject, stands out. The second, far away, is easier to forgive. But fix both when you proofread.",
 ]),
 dict(mode='concept', active=6, title='Pronoun reference', script=[
  "Pronoun reference. Every 'it', 'they', 'this' must point clearly to one thing.",
  X('When the city council met the teachers, they rejected the plan.'),
  "Who rejected the plan? The council, or the teachers? The reader can't know, and those are two different arguments.",
  V('When the city council met the teachers, the teachers rejected the plan.'),
  X('The ministry funds the schools, but this is not enough.', label='A vague "this" appears'),
  "'This' what? The funding? The number of schools?",
  V('The ministry funds the schools, but this funding is not enough.'),
  S("this + noun appears", 'Unclear?  Repeat the noun, or write "this + noun"', size=40),
  "If there's any doubt, repeat the noun, or add it after 'this': 'this funding', 'this policy'.",
 ]),
 dict(mode='concept', active=7, title='Tense', script=[
  "Tense. A few mistakes come up again and again.",
  X('If the law will pass, companies will pay less tax.'),
  V('If the law passes, companies will pay less tax.'),
  "After 'if' and 'when', English uses the present for the future: 'if the law passes', not 'if the law will pass'. A classic Hebrew-speaker mistake.",
  X('In recent years, many cities install cameras in public spaces.', label='A second wrong version appears'),
  V('In recent years, many cities have installed cameras in public spaces.'),
  "'In recent years' describes something that started in the past and continues now. That takes 'have installed'.",
  N("Keep one time frame appears", 'Keep one time frame: general claims in the present, predictions with will / may / could', size=32),
  "And don't jump between past and present for no reason. General claims in the present tense. Predictions with 'will', or more carefully with 'may' or 'could'.",
 ]),
 dict(mode='concept', active=8, title='Missing negatives', script=[
  "Missing negatives. The smallest word with the biggest effect.",
  X('Without cameras, the police can identify suspects quickly, so the cameras are necessary.', size=30),
  "Read it again. It says the police can identify suspects without cameras, so the cameras are necessary? That argues against itself.",
  V('Without cameras, the police cannot identify suspects quickly, so the cameras are necessary.', size=30),
  "One missing 'not' and the argument points in the opposite direction.",
  X('Lowering taxes for large companies will reduce jobs, so the state should lower them.', size=30, label='A second wrong version appears'),
  V('Lowering taxes for large companies will not reduce jobs, so the state can afford to lower them.', size=30),
  S("Read every 'not' twice appears", 'In proofreading: check every can / cannot, will / will not, more / less', size=36),
  "When you proofread, check every can and cannot, every will and will not, every more and less.",
 ]),
 dict(mode='concept', active=9, title='Parallel structure', script=[
  "The last topic of correctness and style: consistency, or parallel structure.",
  X('The new road will allow the public easier access to the centre, to shorten travel time and saving money on fuel.', size=30),
  "Let's read it again, slowly. 'Easier access', 'to shorten', 'saving'. There's a problem, right? The three items aren't built the same way.",
  "Again, I don't want to go into terminology. It's something you see. It jars.",
  V('The new road will allow the public to reach the centre more easily, shorten travel time and save money on fuel.', size=30),
  "Either three verbs: to reach, shorten, save.",
  V('The new road will provide easier access to the centre, shorter travel times and savings on fuel.', size=30, label='A second correct version appears'),
  "Or three nouns: easier access, shorter travel times, savings on fuel. And by the way, this version is a bit more academic.",
  S("Lists: same form appears", 'Items in a list = the same grammatical form', size=40),
 ]),
 dict(mode='concept', active=10, title='Hebrew-speaker traps', script=[
  "And finally, a short list of mistakes that come from translating Hebrew word for word.",
  N("discuss about appears", '✗  discuss about the problem   →   ✓  discuss the problem', size=32, gap=18),
  "'Discuss' takes no 'about'. Discuss the problem.",
  N("explain me appears", '✗  explain me why   →   ✓  explain to me why', size=32, gap=18),
  N("depends in appears", '✗  it depends in the budget   →   ✓  it depends on the budget', size=32, gap=18),
  N("the people appears", '✗  the people think that ...   →   ✓  people think that ... / many people believe ...', size=32, gap=18),
  N("according to me appears", '✗  according to me   →   ✓  in my opinion, ...', size=32, gap=18),
  N("more better appears", '✗  more better / more easier   →   ✓  better / easier', size=32, gap=18),
  N("if will appears", '✗  if the law will pass   →   ✓  if the law passes', size=32, gap=18),
  N("informations appears", '✗  informations, researches, evidences   →   ✓  information, research, evidence', size=32, gap=30),
  "'Information', 'research', 'evidence', 'advice' have no plural with an 's'. Write 'a great deal of research', or 'many studies'.",
  "Keep this list next to you when you proofread your practice essays. After a few essays you'll catch them on your own.",
 ]),
], T50),

# ============================================================ lesson 3: sentence structure and punctuation (seg11 + seg12)
lesson('vr50-c-sentences', 'Sentence Structure and Punctuation', SB_SENT, [
 dict(mode='title', title='Sentence Structure and Punctuation', script=[
  "Sentence structure and punctuation.",
  "The language rubric asks for varied sentence structures. Let's see what that means in practice, and how punctuation helps.",
 ]),
 dict(mode='concept', active=0, title='No terminology', script=[
  "First, sentence structures. There are all kinds of sentence types, but we don't want to go into that.",
  S("No terminology appears", 'You do not need grammar terminology. This is not a grammar exam.', size=40),
  "We're not interested in the terminology. This isn't a grammar exam.",
  S("Not only short, not overloaded appears", 'In practice: not only short sentences, and not overloaded ones either', size=40),
  "What does it mean in practice? That your sentences shouldn't all be short, and they shouldn't be heavy and overloaded either.",
  N("Write naturally appears", 'Write naturally and fluently. Split a sentence where it needs splitting, join where it needs joining, and let punctuation help.', size=32),
  "You don't need to think about it too much or try to build varied structures on purpose. Just write naturally and fluently. Where a sentence needs splitting, split it, and use punctuation to do that.",
 ]),
 dict(mode='concept', active=1, title='Too short', script=[
  "Let's see an example. One problem students have is sentences that are too short. It breaks the flow of reading.",
  PARA("The choppy paragraph appears", 'In recent years, security officials have been promoting a bill. The aim of the bill is to set up a national network of face-recognition cameras. The cameras will be placed in public spaces. Current technology can identify people and objects in real time. It can do this with high certainty. The technology will identify any person, vehicle or object caught on camera. This will be possible if their image is already in the database. This information will help fight crime and terrorism. It will be possible to identify suspicious activity before an offence. It will be possible to stop illegal activity while it happens. It will be possible to catch offenders after the offence.', size=28),
  "If a whole paragraph looks like this, full stop, full stop, full stop, it ruins the flow. You can't really read it.",
  D("teacher marks the full stops one after another"),
  "So what do we do? We join some of these sentences together.",
  PARA("The last three sentences, joined, appear", 'It will be possible to identify suspicious activity before an offence, to stop illegal activity while it happens, or to catch offenders after the offence.', size=30),
  "For example: identify suspicious activity before an offence, comma, stop it while it happens, comma, or catch offenders afterwards.",
  "I joined three sentences into one, and got a varied sentence structure.",
 ]),
 dict(mode='concept', active=2, title='Too long', script=[
  "Now the other extreme: an overloaded sentence.",
  PARA("The overloaded sentence appears", 'In recent years, security officials have been promoting a bill to set up a national network of face-recognition cameras in public spaces, since current technology can identify people and objects in real time with high certainty, and it will be possible to identify any person, vehicle or object caught on camera, provided that their image is already in the database, and this information will help fight crime and terrorism that harm the population, in that it will be possible to identify suspicious activity before an offence, to stop illegal activity while it happens, or to catch offenders after the offence.', size=28),
  "Sorry, I'm out of breath.",
  "One sentence, a million commas, lots of parts. Why? That's the other extreme. Not short sentences, but one sentence with so many parts that we stop breathing.",
  N("You lose the connections appears", 'By the end, the reader no longer remembers how the parts are connected', size=32),
  "With so many connecting words, one after another, you no longer remember how the different parts of the sentence relate to each other.",
 ]),
 dict(mode='concept', active=3, title='The breath test', script=[
  S("The breath test appears", 'The breath test: a good sentence can be read aloud in one breath', size=42),
  "A good sentence is one you can read in one breath. Take a breath once, and if you manage to finish the sentence, it's a sign it's fine.",
  N("Out of breath = warning sign appears", 'Out of breath before the full stop?  Warning sign: it may be too long.  Split it.', size=34),
  "If you don't manage, that's a warning sign that it may be too long.",
  N("Variety comes naturally appears", 'Variety = a natural mix: some short sentences, some longer ones joined by connectors', size=32),
  "Variety isn't something you manufacture. It comes naturally once you join some sentences and split others.",
 ]),
 dict(mode='concept', active=4, title='The fixed paragraph', script=[
  "Let's see this paragraph written properly and comfortably.",
  PARA("The fixed paragraph appears", 'In recent years, security officials have been promoting a bill to set up a national network of face-recognition cameras in public spaces. Because current technology can identify people and objects in real time with high certainty, it will be possible to identify any person, vehicle or object caught on camera, provided that their image is already in the database. This information will help fight crime and terrorism: it will make it possible to identify suspicious activity before an offence, to stop illegal activity while it happens, or to catch offenders after the offence.', size=29),
  "Full stop after the first sentence. Pause, breathe.",
  D("teacher marks each full stop as a place to breathe"),
  "Each time I took a few sentences and joined them, and the result is varied sentence structure.",
  "You don't need to strain. It comes naturally once you join sentences. Just don't do what I did before: sentences that are too short, or one long, overloaded sentence.",
 ]),
 dict(mode='concept', active=5, title='Punctuation = strings', script=[
  "Now, punctuation. There are many punctuation marks and all kinds of rules, and again, we don't want to get into all of it.",
  S("The goal of punctuation appears", 'Punctuation makes the reader read your essay the way you would read it aloud to them', size=40),
  "What do we want from punctuation? Its purpose is to make the reader read the essay the way I would want to read it to them.",
  N("A puppet on strings appears", 'The reader is a puppet on strings: you decide where they stop, where they pause, what they stress', size=32),
  "The reader is like a puppet on strings. I tell them when to stop, what to stress, and I can even change their intonation while they read.",
  N("Really needed: . and , appears", 'For the exam, you really need the full stop and the comma, and maybe the semicolon. The rest: know when you might need them.', size=32),
  "We won't go through every mark, only the main ones. To be honest, for the exam the full stop and the comma are almost enough. But we should know the others, to see when we might need them.",
 ]),
 dict(mode='concept', active=6, title='Period and comma', script=[
  S("Full stop appears", 'Full stop ( . ): at the end of every sentence, wherever the reading stops', size=36),
  "The full stop. At the end of every sentence, anywhere there's a full stop in the reading. Did you notice? I stopped. There's a full stop there.",
  S("Comma appears", 'Comma ( , ): a short pause in the flow, but not a full stop', size=36),
  "The comma: wherever there should be a short pause in the flow of reading, but not a full stop like a period.",
  "Did you see what I did there? A short pause, comma, but not a full stop.",
  N("Comma after an opening phrase appears", 'After an opening phrase:  In recent years, ...   On the other hand, ...   If the law passes, ...', size=31),
  "In English, one of the most useful comma rules: put a comma after an opening phrase. 'In recent years, comma'. 'On the other hand, comma'. 'If the law passes, comma'.",
  N("Comma before and/but + full sentence appears", 'Before and / but that joins two full sentences:  Cameras may deter crime, and they can help the police.', size=31),
  "And before 'and' or 'but' when it joins two full sentences, each with its own subject: 'Cameras may deter crime, comma, and they can help the police'. In a simple list, like 'cameras and sensors', there's no comma.",
  N("Want a pause? appears", 'The practical rule: if you want the reader to pause for a moment, a comma is usually right', size=31),
  "And the most important rule, in my view: when you want the reader to pause for a moment, put a comma.",
 ]),
 dict(mode='concept', active=7, title='Comma splices', script=[
  "There's one thing a comma cannot do in English: join two full sentences on its own.",
  X('Cameras reduce crime, they also help the police find missing people.'),
  "Two complete sentences, with only a comma between them. This is called a comma splice, and it's one of the most common mistakes in English essays.",
  N("Three fixes appear", 'Three ways to fix it:', size=34, gap=12),
  V('Cameras reduce crime. They also help the police find missing people.', label='Fix 1 · a full stop appears', gap=12),
  V('Cameras reduce crime; they also help the police find missing people.', label='Fix 2 · a semicolon appears', gap=12),
  V('Cameras reduce crime, and they also help the police find missing people.', label='Fix 3 · a connector appears'),
  "A full stop. A semicolon. Or a comma plus a connecting word like 'and' or 'but'.",
  X('The plan is expensive, however it will save money in the long run.', label='The "however" splice appears'),
  V('The plan is expensive; however, it will save money in the long run.', label='The fixed "however" appears'),
  "And watch out for 'however'. It's not like 'but'. Between two full sentences it needs a full stop or a semicolon before it, and a comma after it.",
 ]),
 dict(mode='concept', active=8, title='Semicolon and colon', script=[
  S("Semicolon appears", 'Semicolon ( ; ): joins two full sentences that are closely related', size=36),
  "The semicolon joins two full sentences that are closely connected. We just saw it.",
  S("Colon appears", 'Colon ( : ) in three cases:', size=36, gap=14),
  "The colon. We use it in the following cases.",
  N("A list appears", '1 · a list:  The plan has three parts: training, equipment and supervision.', size=31, gap=14),
  "One: a list of details. What was on the table: a plate, comma, a fork, comma, a glass, and so on.",
  N("A quotation appears", '2 · a quotation or direct speech:  The report stated: "Most offences occur at night."', size=31, gap=14),
  "Two: when I quote, or there's direct speech.",
  N("An explanation appears", '3 · an explanation:  The plan has one weakness: it depends on accurate data.', size=31),
  "Three: when an explanation follows. Like right here: 'in the following cases', colon.",
 ]),
 dict(mode='concept', active=9, title='Dash and brackets', script=[
  S("Dash appears", 'Dash ( – ): a stronger separation, often before an explanation (like a colon)', size=34),
  N("Dash example appears", 'This regulation is a "dead letter" – nobody actually follows it.', size=31),
  "The dash. A stronger separation, often before an explanation, like a colon. This regulation is a dead letter, dash, nobody actually follows it.",
  S("Brackets appear", 'Brackets ( ): an addition, detail or side note:  closed-circuit television (CCTV)', size=34),
  "Brackets: an addition or a side note, for example when you define an abbreviation.",
 ]),
 dict(mode='concept', active=10, title='Quotation marks', script=[
  S("Quotation marks appear", 'Quotation marks ( " " ): a quotation · a name · a term you discuss · a word used loosely, on purpose', size=34),
  "Quotation marks: a quotation, a name, a term you're discussing, or, rarely, an informal word used on purpose.",
  N("A useful expression appears", 'Useful in an essay:  "a dead letter" = a rule that exists on paper but nobody follows', size=31),
  "By the way, a dead letter is a great expression for the essay: a rule that exists on paper, but nobody follows.",
 ]),
 dict(mode='concept', active=11, title='? and !', script=[
  S("Question mark appears", 'Question mark ( ? ): after a direct question only', size=36),
  X('The question is whether the city should close the centre to cars?', label='The indirect question appears'),
  V('The question is whether the city should close the centre to cars.'),
  "The question mark goes only after a direct question. 'The question is whether' is indirect, so no question mark. And no rhetorical questions in the essay.",
  S("Exclamation mark appears", 'Exclamation mark ( ! ): an order or strong emotion. Not in the essay', size=36),
  "The exclamation mark is for an order or strong emotion. Not for academic writing.",
 ]),
 dict(mode='concept', active=12, title='Allowed in an essay?', script=[
  "So, can we use all these marks in academic writing? Here's the summary.",
  N("Quotation marks: when needed appears", 'Quotation marks: yes, when needed (a term, a name, a word used on purpose)', size=31, gap=14),
  "Quotation marks: allowed when needed, when they serve the content.",
  N("Abbreviations: define first appears", 'Abbreviations: only after you define them  (closed-circuit television (CCTV))', size=31, gap=14),
  "Abbreviations: as a rule we don't use them unless they were defined earlier.",
  N("Brackets: allowed, better without appears", 'Brackets: allowed, but better to rephrase. Important?  Write it with commas.', size=31, gap=14),
  "Brackets: allowed, but it's better to try to phrase it without them. If something is important, write it, with commas, not in brackets.",
  N("Exclamation mark: no appears", 'Exclamation mark: no. It is like shouting, too strong for academic writing.', size=31, gap=14),
  "The exclamation mark: in principle, no. It's very forceful, like a shout, an emphasis that doesn't suit academic writing.",
  N("etc.: avoid appears", '"etc.": better not. Write "and similar measures", "and other services".', size=31, gap=14),
  "Etcetera: better not. Write it out: 'and similar measures', 'and other public services'.",
  N("Three dots: no appears", 'Three dots ( ... ): no. Nothing is obvious. Explain it.', size=31, gap=14),
  "Three dots: better not, also for content reasons. We said nothing is obvious. Three dots means 'you figure it out'. We want to explain.",
  N("Contractions: no appears", "Apostrophe contractions (don't, it's): no. Write the full form.", size=31),
  "And one that's special to English: no contractions.",
 ]),
], T50),

# ============================================================ lesson 4: organizational tools (seg13 + findings #27)
lesson('vr50-c-organize', 'Organizational Tools', SB_ORG, [
 dict(mode='title', title='Organizational Tools', script=[
  "Organizational tools.",
  "This is the last criterion in the language rubric: connectors, transitions and paragraphing.",
 ]),
 dict(mode='concept', active=0, title='Three tools', script=[
  "We remember that in our rubric, organizational tools are divided into three.",
  S("Connectors appear", '1 · Connectors', size=42, gap=18),
  S("Transition sentences appear", '2 · Transition sentences', size=42, gap=18),
  S("Paragraphing appears", '3 · Paragraphing', size=42),
  "Connectors, transition sentences, and dividing the essay into paragraphs. The official guide names exactly these: conjunctions, transition sentences and correct paragraphing.",
  "Let's go through them, starting with connectors.",
 ]),
 dict(mode='concept', active=1, title='What connectors do', script=[
  S("Definition appears", 'A connector states the relationship between what came before it and what comes after it', size=38),
  "What is a connector? A word that defines the relationship between the part before it and the part after it.",
  N("They help focus and flow appears", 'They support focus and coherence, keep the main idea on track and keep the reading smooth', size=31),
  "Connectors support focus and coherence, keep the main line of thought, and keep the reading flowing. They help the reader understand how the different parts connect.",
  N("Three places appear", 'Three places:  inside a sentence  ·  between sentences  ·  between paragraphs', size=34),
  "Notice I said between the part before and the part after, because connectors can appear in three places.",
  "Inside a sentence, between its first part and its second part: agreement, detail, explanation, contrast.",
  "Between sentences, inside the paragraph: one sentence, then the next one explains it, then the next one contrasts with it.",
  "And between paragraphs: connectors at the start of a paragraph that tell us how this paragraph relates to the one before.",
 ]),
 dict(mode='concept', active=2, title='An example', script=[
  "Let's see an example.",
  PARA("The example paragraph appears", 'On the other hand, some call for a ban on personal electric vehicles such as e-scooters, since they are involved in a higher share of injury accidents than their share of road users. Admittedly, this figure is accurate; however, it is important to note that most of these accidents involve only minor injuries, unlike accidents involving larger vehicles.', size=30),
  "I've highlighted the connectors. We have connectors inside sentences and between sentences, and even at the start of the paragraph.",
  D("teacher underlines: On the other hand · since · Admittedly · however · unlike"),
  N("On the other hand appears", 'On the other hand  →  this paragraph will be the opposite of the one before', size=31, gap=12),
  "'On the other hand'. Right away I know this paragraph is going to go against the one before it. That's a connector between paragraphs.",
  N("since appears", 'since  →  the second part explains the first', size=31, gap=12),
  "'Some call for a ban since...' The second part of the sentence will explain the first. Why ban them? Because they're involved in a higher share of accidents.",
  N("Admittedly ... however appears", 'Admittedly ... ; however,  →  partial agreement, then a reservation', size=31, gap=12),
  "'Admittedly'. There's a kind of half agreement, with a reservation. 'Admittedly this figure is accurate; however'. There's the contrast.",
  N("unlike appears", 'unlike  →  a comparison', size=31),
  "'Unlike accidents involving larger vehicles'. Here we have a comparison.",
 ]),
 dict(mode='concept', active=3, title='Know your connectors', script=[
  "Now, everything I just said, comparison, detail, explanation: you really don't need to know the names of all the types of connectors.",
  S("Understand what you use appears", 'You do not need to know every connector. You need to understand the ones you use.', size=38),
  "You just need to understand the connectors you use.",
  N("albeit appears", '"albeit" = although  (not "also"):  The plan is effective, albeit expensive.', size=31, gap=16),
  "If there's a connector that's hard for you, don't use it. Many students see 'albeit' and think it means 'also', an addition. It means 'although'.",
  N("On the contrary appears", '"On the contrary" = what I said before is false  ·  "On the other hand" = here is the other side', size=31, gap=16),
  "Another classic: 'on the contrary' is not the same as 'on the other hand'. 'On the contrary' says the previous statement is wrong. To introduce the other side, write 'on the other hand'.",
  N("Grammar of connectors appears", 'because + a clause  ·  because of / due to / despite + a noun  ·  however; + a full sentence', size=31),
  "And some connectors come with grammar. 'Because' before a full clause. 'Because of', 'due to', 'despite' before a noun. 'However' starts a new sentence, or comes after a semicolon.",
 ]),
 dict(mode='concept', active=4, title='Relationship first', script=[
  "Now a very important rule.",
  S("Signal, not create appears", 'A connector signals a relationship. It does not create one.', size=44),
  "A connector signals a relationship. It doesn't create one.",
  X('Cameras record every street. Therefore, crime will disappear.', label='The empty "therefore" appears'),
  "Putting 'therefore' in front of a conclusion doesn't prove that it follows. Why would recording streets make crime disappear? The step in the middle is missing.",
  V('Offenders who know they are likely to be identified may avoid committing crimes in areas covered by cameras. As a result, crime in those areas may decrease.', size=30, label='The real link appears'),
  "Here the link is explained. Now 'as a result' describes a relationship that really exists. And notice 'may', not 'will disappear'.",
  X('Cameras should be installed in every public space. However, they should not be installed near homes.', size=30, label='The empty "however" appears'),
  "And 'however' between two positions that contradict each other doesn't explain why there's an exception. You have to explain it: what's different about homes?",
  S("First the relationship, then the word appears", 'First decide the relationship  →  then choose the connector that expresses it', size=36),
  "So first identify the relationship: cause, result, contrast, concession, condition, example. Then choose the connector that expresses it accurately.",
 ]),
 dict(mode='concept', active=5, title='Connectors by type', script=[
  "Here are the main English connectors, grouped by the relationship they express.",
  N("Cause appears", 'Cause:  because · since · as · because of / due to (+ noun)', size=30, gap=10),
  N("Result appears", 'Result:  therefore · as a result · consequently · thus · which in turn', size=30, gap=10),
  N("Contrast appears", 'Contrast:  however · whereas · while · in contrast · on the other hand', size=30, gap=10),
  N("Concession appears", 'Concession:  although · even though · despite (+ noun) · admittedly ...; however · nevertheless', size=30, gap=10),
  N("Condition appears", 'Condition:  if · unless · provided that · as long as · only if', size=30, gap=10),
  N("Example appears", 'Example:  for example · for instance · such as · in particular', size=30, gap=10),
  N("Addition appears", 'Addition:  in addition · moreover · furthermore · also (inside the sentence)', size=30, gap=10),
  N("Conclusion appears", 'Conclusion:  in conclusion · to sum up · in light of the above · overall', size=30),
  "Cause and result, contrast and concession, condition, example, addition, and conclusion.",
  "Concession is the one students forget: you admit part of the other side's point, and then add your reservation. 'Admittedly... however'. 'Although this is true...'.",
  "You don't need all of them. Two or three from each group that you understand well are plenty. You'll find this table on the card after the lesson.",
 ]),
 dict(mode='concept', active=6, title='Paragraph openers', script=[
  "Connectors at the start of paragraphs. Here's a list you can go through.",
  N("Opening paragraph appears", 'Opening paragraph:  no connector.  Start with the background:  In recent years, ... / Recently, ...', size=30, gap=14),
  "The opening paragraph doesn't start with a connector. It usually starts with 'In recent years' or 'Recently', depending on the background in the task.",
  N("First argument paragraph appears", 'First argument paragraph:  its key sentence opens with  In my opinion, ... / I believe that ...', size=30, gap=14),
  "The first argument paragraph opens with its key sentence, and the key sentence starts with 'In my opinion' or 'I believe that'. No connector needed.",
  N("Second argument paragraph appears", 'Second argument paragraph:  Moreover, in my opinion, ... / In addition, I believe that ... / Beyond this, I believe that ...', size=30, gap=14),
  "The second argument paragraph adds a connector before it: 'Moreover, in my opinion', 'In addition, I believe that'. 'First, in my opinion' sounds awkward, so skip the numbers.",
  N("Rebuttal paragraph appears", 'Rebuttal paragraph:  On the other hand, ... / Nevertheless, some argue that ... / Admittedly, ...', size=30, gap=14),
  "The rebuttal paragraph. Now I want to confront the other side, there's a counter-argument: 'On the other hand', 'Nevertheless', 'Admittedly'. There's contrast here.",
  N("Closing paragraph appears", 'Closing paragraph:  In conclusion, ... / To sum up, ... / In light of the above, ...', size=30),
  "And the closing paragraph. I want to sum up: 'In conclusion', 'To sum up', 'In light of the above'.",
 ]),
 dict(mode='concept', active=7, title='Paragraphs have jobs', script=[
  "Paragraphing and transition sentences.",
  S("Essay = paragraphs with roles appears", 'The essay is built of paragraphs, and each paragraph has a job', size=40),
  "First of all, the essay is made of paragraphs. Each paragraph has a specific role, and we have to make sure each one does its job in the essay.",
  N("Paragraphs connect appears", 'The paragraphs must connect to each other and keep one line of thought', size=32),
  "The paragraphs have to connect to each other and keep the line of thought. That's where the connectors come in.",
  N("Paragraphs reflect ideas appears", 'The official guide: the division into paragraphs should reflect the ideas in the essay', size=32),
  "The official guide says the division into paragraphs should reflect the ideas in the essay. A new idea, a new paragraph.",
 ]),
 dict(mode='concept', active=8, title='Transition sentences', script=[
  S("Transition sentence defined appears", 'A transition sentence links two paragraphs and shows the reader how the ideas continue', size=38),
  "Transition sentences are sentences that connect paragraphs and help the reader follow the line of thought.",
  "I can connect paragraphs with a connector, or with a longer sentence that explains how the paragraphs relate.",
  N("Just a connector appears", 'A connector:   Moreover, cameras could shorten police response times.', size=31, gap=16),
  N("A transition sentence appears", 'A transition sentence:   Beyond preventing crime, cameras could also change what happens once a crime has occurred: they could shorten police response times.', size=31),
  "The transition sentence reminds the reader where we've been, preventing crime, and tells them where we're going now, what happens after a crime.",
 ]),
 dict(mode='concept', active=9, title='One argument each?', script=[
  "The rule: one argument per paragraph.",
  S("Same field → one paragraph is fine appears", 'One argument per paragraph. Two points from the same field that serve ONE argument may share it', size=38),
  "But sometimes two points come from the same field and serve one argument. For example, two economic points: one from the employers' side and one from the workers' side.",
  N("Tax example appears", 'Reduced tax for large companies:  the benefit for the companies + the benefit for their workers  →  one economic argument, one paragraph', size=31),
  "Take reduced tax for large companies. The benefit to the companies, and the benefit to their employees. Both economic, and together they make one argument: the economy gains. So they share one paragraph.",
  N("Not a fixed rule appears", 'Different perspectives → split into paragraphs.  Same field, one argument → combine.', size=31),
  "If the points are from different perspectives, they are different arguments, so we split them. If they're from the same field and serve one argument, I combine them.",
  "Split into two paragraphs, they'd look too similar to each other. That weakens the critical thinking I'm showing.",
 ]),
 dict(mode='concept', active=10, title='On the page', script=[
  "And now, how it looks on the answer sheet.",
  A("The answer sheet appears", dict(ANSWER_SHEET, x=400, y=20, w=640, h=832)),
  A("No new line mid-paragraph appears", T('No new line in the middle of a paragraph', size=32, x=1070, y=90, w=470)),
  "In the middle of a paragraph, we don't start a new line. Keep writing until you finish the paragraph.",
  A("Indent appears", T('Start each new paragraph with an indent: begin a little way in from the margin', size=32, x=1070, y=300, w=470)),
  "When you move to the next paragraph, it's recommended to indent: start a little further in, and leave that bit blank.",
  A("A blank line if you can spare it appears", T('A blank line between paragraphs leaves room for corrections, if the essay still fits in the 50 lines', size=32, x=1070, y=540, w=470)),
  "We also recommend leaving a blank line between paragraphs, so you have room for corrections later without crossing out and squeezing words above the line. Just make sure the essay still fits in the fifty lines.",
  "That's it for organizational tools. We've covered the language rubric. But there's one more thing we added: language richness. See you in the next lesson.",
 ]),
], T50),

# ============================================================ lesson 5: language richness (seg14 + findings #25)
lesson('vr50-c-richness', 'Language Richness', SB_RICH, [
 dict(mode='title', title='Language Richness', script=[
  "Language richness.",
  "How to make your English richer, without making it flowery.",
 ]),
 dict(mode='concept', active=0, title='Not in the rubric?', script=[
  S("Richness: inside academic style appears", 'Rich vocabulary is part of what the raters look for', size=40),
  "As we said, language richness doesn't appear in the language table as its own row. But it's implied by consistency with academic writing.",
  N("The guide mentions it appears", 'The official guide lists "richness of vocabulary" among the things raters consider', size=32),
  "And the official guide lists it explicitly: raters consider precision of word usage and richness of vocabulary.",
  "Today we'll talk about two tools: referring words, and raising the register carefully.",
 ]),
 dict(mode='concept', active=1, title='Repetition', script=[
  "Let's see a sample paragraph.",
  PARA("The repetitive paragraph appears", 'In my opinion, the job of passing on knowledge and learning material to the young generation should stay with teachers alone, since teachers studied for years to do this, and teachers\' studies include accepted methods for teaching the learning material that teachers must pass on. Unlike teachers, parents do not know the learning material, and parents did not study, as teachers did, how to pass on the learning material in the best way.', size=29),
  "Wow. As you can see, there's so much repetition of 'the learning material' and of 'teachers'.",
  D("teacher circles every 'teachers' and every 'learning material'"),
  "Teachers, teachers, teachers, teachers. It's almost impossible to read. And of course that costs points.",
 ]),
 dict(mode='concept', active=2, title='Referring words', script=[
  S("Referring words appear", 'Referring words: words that point back, so you do not repeat the same noun', size=38),
  "Referring words are words we can use instead, so we don't get this kind of repetition.",
  N("Synonyms appears", 'Synonyms:  studied → were trained  ·  learning material → the curriculum', size=31, gap=12),
  N("Pronouns appears", 'Pronouns:  they · them · it', size=31, gap=12),
  N("Demonstratives appears", 'Demonstratives:  these · those · this approach · such methods', size=31, gap=12),
  N("Possessives appears", 'Possessives:  their · its', size=31, gap=12),
  N("Preposition phrases appears", 'Phrases with prepositions:  with them · like them · unlike them', size=31),
  "They can be synonyms, pronouns like they and them, words like these and those, possessives like their, and phrases like 'with them' or 'unlike them'.",
 ]),
 dict(mode='concept', active=3, title='The paragraph, fixed', script=[
  "Let's see how I can write this paragraph differently, using referring words.",
  PARA("The rewritten paragraph appears", 'In my opinion, the job of passing on knowledge and learning material to the young generation should stay with teachers alone, since they have been trained for years to do this, and the courses they have taken include accepted methods for teaching the content they must pass on. Unlike them, parents are not familiar with the national curriculum, and they have not been trained in the best ways of teaching it.', size=29),
  "'They' instead of 'teachers'. 'Have been trained' instead of 'studied', a synonym. 'The courses they have taken'. 'Unlike them'. 'The national curriculum', 'teaching it'.",
  D("teacher underlines: they · trained · the courses they have taken · Unlike them · it"),
  "We've seen how I used different referring words to make the text more readable.",
 ]),
 dict(mode='concept', active=4, title='Raising the register', script=[
  "Now some examples of raising the register. Just a few examples, to give you a direction, so you understand what to do and try it yourselves, with every word and sentence you come across.",
  N("Pairs appear", 'but → however, yet   ·   because → since, as   ·   because of → due to, owing to', size=31, gap=12),
  "Instead of 'but', you can write 'however' or 'yet'. Everything is correct. 'But' is fine. 'However' is just a bit more formal.",
  N("More pairs appear", 'maybe → perhaps, possibly   ·   how → the way in which   ·   why → the reason that', size=31, gap=12),
  N("Even more pairs appear", 'get → obtain, gain   ·   give → provide, grant   ·   show → demonstrate', size=31, gap=12),
  N("And more pairs appear", 'enough → sufficient   ·   totally → entirely   ·   a lot of → many, considerable', size=31, gap=12),
  N("Kids and big appear", 'kids → children   ·   big → substantial, major   ·   think → believe, argue, maintain', size=31),
  "'Enough' becomes 'sufficient'. It says the same thing, but signals a higher register. 'Kids' is everyday English; in the essay, 'children'.",
  "Again, these are just a few small examples. You can take almost any sentence and try to raise it with synonyms that keep the same meaning.",
  "With practice, and depending on your vocabulary, you'll gradually be able to take sentences and raise the language, and show more richness.",
 ]),
 dict(mode='concept', active=5, title='Not flowery', script=[
  "But here's the limit.",
  S("Guide: avoid needlessly difficult appears", 'Avoid flowery and needlessly difficult language', size=42),
  "The guide says: avoid flowery and needlessly difficult language. And use only words that accurately convey what you mean.",
  X('The utilization of surveillance apparatus shall ameliorate the plethora of infractions.', size=30, label='The flowery version appears'),
  V('Using cameras may reduce the number of offences.', size=30, label='The clear version appears'),
  "Nobody gets extra points for 'plethora'. The second sentence is shorter, clearer, and more precise. It even adds the careful 'may'.",
  N("Because is fine appears", '"because", "but" and "if" can express the relationship perfectly well', size=32),
  "'Because', 'but' and 'if' can express a relationship perfectly well. A more formal word helps only when it says exactly what you mean, and fits the sentence.",
  S("Use the range you control appears", 'Richness = the range you can control, used precisely', size=40),
  "So richness means using the range of English you can control, and using it precisely.",
 ]),
 dict(mode='concept', active=6, title='Practice', script=[
  "A short practice routine.",
  N("Step 1 appears", '1 · Take a paragraph you wrote. Circle every noun that appears three times or more.', size=32, gap=18),
  "Take a paragraph from a practice essay. Circle every noun that appears three times or more.",
  N("Step 2 appears", '2 · Replace some with referring words. Keep the key term.', size=32, gap=18),
  "Replace some of them with referring words: they, these, such, a synonym. But keep your key term.",
  N("Step 3 appears", '3 · Find three everyday words (but, get, a lot of) and upgrade them only if the meaning stays exactly the same.', size=32, gap=18),
  "Find three everyday words and raise them, only where the meaning stays exactly the same.",
  N("Step 4 appears", '4 · Read it aloud: still clear?  Still in one breath?', size=32),
  "Then read it aloud. Is it still clear? Can each sentence still be read in one breath?",
  "That's it for this lesson. See you in the next one.",
 ]),
], T50),
]


MEMORY = [
 dict(id='mem-wr-grammar', after='vr50-c-grammar', title='Grammar that changes meaning',
  intro='Fix these first when you proofread: they change what your sentence says, or sound wrong to an academic reader.',
  tables=[dict(title='Errors and fixes', head=['Problem', 'Wrong', 'Right'], rows=[
    ['Articles', 'The people think the technology ...', 'Many people believe technology ...'],
    ['Relative clause', 'the topic that the book deals with it', 'the topic that the book deals with'],
    ['Missing when / if', 'Citizens protest, the government will act.', 'If citizens protest, the government will act.'],
    ['Comparative', 'more better / much more better', 'better / much better than ...'],
    ['Agreement', 'Belonging to a group are ...', 'Belonging to a group is ...'],
    ['Pronoun reference', 'The council met the teachers; they rejected it.', '... the teachers rejected the plan.'],
    ['Tense after if', 'If the law will pass, ...', 'If the law passes, ...'],
    ['Missing negative', 'Without cameras, the police can identify ...', 'Without cameras, the police cannot identify ...'],
    ['Parallel lists', 'easier access, to shorten and saving', 'easier access, shorter trips and savings'],
    ['Comma splice', 'Cameras reduce crime, they also ...', 'Cameras reduce crime; they also ...'],
   ]),
   dict(title='Hebrew-speaker traps and style', head=['Avoid', 'Write'], rows=[
    ['discuss about · explain me · depends in', 'discuss · explain to me · depends on'],
    ['In my opinion I think / according to me', 'In my opinion, ... / I believe that ...'],
    ['in case (= if) · being that · due to + clause', 'if · because · because + clause'],
    ['myself (as a subject) · whom (as a subject)', 'I · who'],
    ['Plus, / Also, (at the start)', 'In addition, / Moreover,'],
    ["don't · it's · gonna", 'do not · it is · will'],
    ['informations · researches · evidences', 'information · research / studies · evidence'],
    ['on the one side ... on the other side · until today', 'on the one hand ... on the other hand · to this day'],
    ['a lot of damages · the possibility to', 'a great deal of damage · the opportunity to / the possibility of'],
    ['logical and reasonable · basically · a complex issue', 'say it once; delete empty words'],
   ])],
  tips=['A few minor slips in a first draft will not sink you; errors that change the meaning will.',
        'Keep one register through the whole essay: no single forced fancy phrase.',
        'In proofreading, check every can / cannot, will / will not, more / less.',
        'Unclear "this" or "they"?  Repeat the noun.']),
 dict(id='mem-wr-connectors', after='vr50-c-organize', title='Connectors by relationship',
  intro='A connector signals a relationship; it does not create one. Decide the relationship first, then choose the word.',
  tables=[dict(title='Connectors', head=['Relationship', 'Connectors', 'Note'], rows=[
    ['Cause', 'because · since · as · because of / due to', 'due to / because of + noun'],
    ['Result', 'therefore · as a result · consequently · thus · which in turn', 'only if the link is explained'],
    ['Contrast', 'however · whereas · while · in contrast · on the other hand', 'however; + full sentence'],
    ['Concession', 'although · even though · despite · admittedly ...; however · nevertheless', 'despite + noun'],
    ['Condition', 'if · unless · provided that · as long as · only if', 'if + present (not will)'],
    ['Example', 'for example · for instance · such as · in particular', ''],
    ['Addition', 'in addition · moreover · furthermore · also (inside)', 'not "Also," or "Plus," to open'],
    ['Conclusion', 'in conclusion · to sum up · in light of the above · overall', ''],
   ]),
   dict(title='Paragraph openers', head=['Paragraph', 'Opens with'], rows=[
    ['Opening paragraph', 'no connector: In recent years, ... / Recently, ...'],
    ['First argument paragraph', 'its key sentence: In my opinion, ... / I believe that ...'],
    ['Second argument paragraph', 'Moreover, in my opinion, ... / In addition, I believe that ...'],
    ['Rebuttal paragraph', 'On the other hand, ... / Nevertheless, ... / Admittedly, ...'],
    ['Closing paragraph', 'In conclusion, ... / To sum up, ... / In light of the above, ...'],
   ])],
  tips=['Use only connectors you understand: albeit = although; "on the contrary" is not "on the other hand".',
        'Turning a chain (the cause-and-effect steps, taught later) into a paragraph: each arrow gets a connector that names the link.',
        'One argument per paragraph; two points from the same field that serve one argument may share it.',
        'No new line mid-paragraph; indent each new paragraph.']),
]
