# Verbal Reasoning · Topic 41 · Sentence completion.
# Hebrew hebverbal.txt 650–1169 gives the concepts, order, methods, tips and verdicts (two lessons: solving techniques,
# then hypothetical conditions). Every question is an ORIGINAL English question (content/verbal_originals_A.json) that mirrors
# a real NITE item's type and traps; no Hebrew example is translated. Hebrew connector / condition words are taught through their English equivalents.
from dsl import *

T41 = 41
def C(t, y, size=40): return T(t, size=size, x=410, y=y, w=1140)

DEMO = 'vo-41-001'              # lesson demo (original question, answer: choice 3)

SB_L1 = ['Where and how long', 'What it tests', 'The instructions', 'Read it in place', 'Similar beginnings',
         'Inner contradiction', 'Found it? Move on', 'Plug in and predict', 'The skeleton']
SB_L2 = ['If it had…', 'Had it not been for', 'Reality is reversed', 'Solve with a skeleton', 'The because trick']
SBQ = ['Q1', 'Q2']

MODULES = [
# ------------------------------------------------------------------ lesson 1: solving techniques (Hebrew 650–925)
lesson('vr41-techniques', 'Sentence Completion', SB_L1, [
 dict(mode='title', title='Sentence Completion', script=[
  "Sentence completion - the techniques.",
  "Short lesson, big payoff. Let's go.",
 ]),
 dict(mode='concept', active=0, title='Where and how long', script=[
  "Where do you meet these questions?",
  A("After the analogies, before the reading passage appears", C('In the verbal section: after the analogies, before the reading passage', 150)),
  "In the verbal section - after the analogies and before the reading passage. Right in the middle.",
  "Their exact place isn't fixed. Usually at the start or in the middle of that part.",
  A("Three questions, always in a row appears", C('Three questions - always in a row', 230)),
  "But they always come as a block - three questions, one after the other.",
  A("About one minute per question appears", C('About one minute per question', 310)),
  "Time? About a minute a question. Depends on how hard it is.",
 ]),
 dict(mode='concept', active=1, title='What it tests', script=[
  "What are they really testing?",
  A("The logical links between the parts of the sentence appears", C('Do you understand the logical links between the parts of the sentence?', 150)),
  "Whether you understand the logical links between the parts of a sentence.",
  "The sentences on the exam are built from several parts - usually three or four.",
  A("Contrast · addition · detail · example appears", C('Contrast · addition · detail · example', 260, 44)),
  "The link between the parts can be contrast, addition, detail, an example - and so on.",
  A("Built with connectors and punctuation appears", C('Built with connectors (but, therefore, for example…) and punctuation (- : ,)', 350)),
  "And how is that link built? With connectors - and with punctuation: a dash, a colon, commas.",
  "That's the skill: can you see how the parts hang together?",
 ]),
 dict(mode='concept', active=2, title='The instructions', script=[
  "Here are the instructions, the way they appear on the exam.",
  A("The instructions appear", C('Each question has a sentence (or several) with some parts missing, followed by four possible completions. Choose the completion that best fits.', 150, 36)),
  "A sentence - sometimes a few sentences in a row - with parts missing. Then four options to fill the gaps.",
  A("Completions go in order: first blank, second blank… appears", C('Each option fills the blanks in order: first part → first blank, second part → second blank…', 330, 36)),
  "Each option fills the blanks in order: its first part goes in the first blank, the second in the second, and so on.",
  "Most of the time you'll have four blanks. Now and then - three.",
 ]),
 dict(mode='question', active=3, title='Read it in place', pre=[VQ(DEMO)], script=[
  "Let's see the tips on a real question.",
  "Tip one: never read the sentence with holes in it.",
  "\"Blank, they blank the proposal…\" - that tells you nothing. And with long sentences it's hopeless.",
  A("Read it with a completion already in place appears", P('Always read with a completion already in place', y=180)),
  "Always read it with the first completion already in.",
  D("Write choice 1's three parts above the three blanks"),
  "\"Keeping classes small is usually a top priority for the members of the town's school board. Therefore they did not support the proposal to move the town's music program into the Oren school building, a proposal not expected to increase the number of pupils in each classroom.\"",
  "Now I'm reading a real sentence. I can actually judge it.",
 ]),
 dict(mode='question', active=4, title='Similar beginnings', pre=[VQ(DEMO)], script=[
  "Tip two: plug in the options by similar beginnings.",
  D("Underline 'Therefore' in choices 1 and 4, and 'Nevertheless' in choices 2 and 3"),
  "Look - choices 1 and 4 both start with \"Therefore\". Choices 2 and 3 both start with \"Nevertheless\".",
  A("After choice 1, try the choice with the same start appears", P('After one option, try the option that starts the same way', y=180)),
  "So after choice 1, the next one I'd try is choice 4 - same start.",
  "Why? Because I still remember the first part of the sentence. I don't have to read it again.",
  "The beginning stays the same - I only check how the rest continues.",
 ]),
 dict(mode='question', active=5, title='Inner contradiction', pre=[VQ(DEMO)], script=[
  "Tip three: internal contradiction.",
  "If the parts of the sentence contradict each other - the option is out. Even if you haven't finished reading.",
  "Choice 1: \"Therefore they did not support the proposal - a proposal not expected to increase the number of pupils in each classroom.\"",
  "Therefore? Because they care about small classes, they rejected a proposal that doesn't touch class size? That doesn't hang together.",
  A("Contradiction between parts → eliminate appears", P('The parts contradict each other → eliminate', y=180)),
  D("Cross out choice 1"),
  "Out. Same start next - choice 4: \"Therefore they supported the proposal - a proposal sure to increase the number of pupils.\"",
  "Because small classes matter to them, they backed a plan that makes classes bigger? Same problem.",
  D("Cross out choice 4"),
  A("Judge the sentence's logic - not general knowledge appears", P("Judge only the sentence's own logic - not what you know about the world", y=250)),
  "And careful: internal contradiction means the logic of the sentence itself. Not general knowledge.",
  "Whether you happen to know how school boards really decide - irrelevant. Only: do its parts connect logically?",
 ]),
 dict(mode='question', active=6, title='Found it? Move on', pre=[VQ(DEMO)], script=[
  "Tip four - mostly a psychological one. Don't check.",
  "The \"Nevertheless\" pair. Choice 2: \"Nevertheless they did not support… a proposal certain to increase the number of pupils.\"",
  "Nevertheless signals a contrast. But rejecting a plan that fills the classrooms is exactly what you'd expect from them. No contrast.",
  D("Cross out choice 2"),
  "Choice 3: \"usually a top priority… Nevertheless they supported… a proposal expected to increase the number of pupils in each classroom.\"",
  "They care about small classes, and still backed a plan that makes them bigger. Perfect contrast. It works.",
  D("Circle choice 3"),
  "Choice 3.",
  A("A completion that works → mark it and move on appears", P('A completion that works → mark it and move on. Don’t check the rest.', y=180)),
  "Found a completion that fits well? Mark it. Don't check the others. Waste of time.",
  "This is hard for students. They find the right one - and keep checking all the rest. Train yourself not to.",
  "\"But the instructions say choose the best completion!\" - In practice there is no \"best\". There's only one that's correct.",
 ]),
 dict(mode='concept', active=7, title='Plug in and predict', script=[
  "So how do we actually solve?",
  A("Technique 1: plug in the options one by one appears", C('Technique 1: plug in the options one after another', 150, 44)),
  "The obvious technique: plug in the options, one after the other, until one completes the sentence logically.",
  "And like we said - once it works, you stop.",
  A("Predict how it should continue appears", C('While reading: predict how the sentence should continue - then check', 250)),
  "While you plug in, think ahead: how should this sentence continue?",
  "Usually your head already tells you what has to come next for the sentence to end well.",
  "Then check if it fits. It helps you eliminate faster and get tangled up less.",
 ]),
 dict(mode='concept', active=8, title='The skeleton', script=[
  "Technique 2 - the most important one: the skeleton.",
  A("Technique 2: shrink the sentence to its skeleton appears", C('Technique 2 (the most important): shrink the sentence to its skeleton', 150, 44)),
  "Especially for long sentences, or ones with complicated links - and there are plenty of those. Three, four lines.",
  "By the time you reach the end, you've forgotten the beginning.",
  A("Delete the noise: descriptions, names, details appears", C('Delete the noise: descriptions, names, details that don’t change the structure', 260)),
  "So we clean out the noise. Descriptive words, names, details - anything that doesn't affect the link between the parts. Cross it out.",
  A("Hard parts → rewrite briefly in your own words appears", C('A complicated part → write it above, briefly, in your own words', 350)),
  "A complicated part? Write it above the line, short, in your own words.",
  "What's left is a skeleton - and you can still plug the options straight into it.",
  "What to delete and what to keep - that comes with practice. Let's practice.",
 ]),
], T41),
# ------------------------------------------------------------------ guided: the two worked examples of lesson 1
guided(0, 'vo-41-002', 'Completion Questions I', SBQ,
 ["Question one - a short one.", "Before we solve it, let's build the skeleton."],
 [('Build the skeleton', [
   "Let's not solve yet. First - what's the skeleton?",
   "\"The speaker's heavy reliance on blank gives his lecture the character of blank; the audience was therefore surprised when, amid the lecture's blank style, he repeatedly paused to blank.\"",
   D("Bracket 'heavy reliance on' and write 'using' above"),
   "\"heavy reliance on\" - in my words: using.",
   A("Skeleton: using X gives the lecture a Y character → surprising: in the Y style, he kept doing Z appears",
     P('Skeleton: using X gives the lecture a Y character → so it’s surprising: in the Y style, he kept doing Z', y=170)),
   "So: X gives the lecture a certain character. Therefore it's surprising that, in that style, he kept stopping to do Z.",
   D("Circle 'surprised'"),
   "And look at the key word - surprised.",
   A("Prediction: Z must clash with the style appears", P('Prediction: Z must clash with that style', y=250)),
   "Predict: whatever goes in the last blank has to clash with the style. Otherwise, what's surprising?",
  ]),
  ('Plug in', [
   "Now plug in, straight into the skeleton.",
   D("Write choice 1 above the blanks: statistical tables / a technical report / dry and impersonal / tell jokes about his own childhood"),
   "Choice 1: detailed statistical tables give the lecture the character of a technical report. Surprising that, amid the dry and impersonal style, he kept pausing to tell jokes about his own childhood.",
   "Yes! Personal jokes clash with a dry, impersonal report. That's the surprise.",
   D("Circle choice 1"),
   "Choice 1.",
   "On the exam - mark it and move on. Don't check the other three.",
  ]),
  ('For the lesson: 2, 3, 4', [
   "Just this once, let's see why the others fail - fast, straight into the skeleton.",
   "Choice 2: legal terminology, an official document, a formal style - and he paused to quote the laws. Surprising? No. Quoting laws fits a formal document. Out.",
   D("Cross out choice 2"),
   "Choice 4: simple words, a talk for young children, playful - and he asked the audience easy questions. Also fits. Nothing surprising. Out.",
   D("Cross out choice 4"),
   "Choice 3: colorful personal anecdotes give the lecture the character of a dry academic paper? The first two parts already contradict each other. Out.",
   D("Cross out choice 3"),
   A("Surprise = the last part must clash appears", P('“surprised” → the last part must clash with the style', y=200)),
   "One key word - surprised - and the prediction did all the work.",
  ])], T41),
guided(1, 'vo-41-003', 'Completion Questions I', SBQ,
 ["Question two - a long one.", "Four blanks, two sentences. This is where the skeleton earns its keep."],
 [('Skeleton first', [
   "A long question. We start with the skeleton - clean out the noise.",
   D("Cross out 'introduced by Principal Harel', 'since the reform took effect', 'written'"),
   "Who introduced the reform, when it started, what kind of assignment - none of it changes the structure.",
   A("Critics: the time spent checking each assignment ___ appears", P('Critics: the time spent checking each assignment ___', y=170)),
   "What's left: the critics argue that the time spent checking each assignment - blank.",
   A("Harel ___ checking takes longer, ___ the extra time = a real improvement, and ___ appears",
     P('Harel ___ checking now takes longer, ___ the extra time = a real improvement, and ___', y=240)),
   "Harel - blank - that checking now takes longer, blank - the extra time is evidence of a real improvement - and blank.",
  ]),
  ('Similar beginnings', [
   "Now plug in. And notice the beginnings.",
   D("Underline 'has decreased' in choices 1 and 4, and 'has increased' in choices 2 and 3"),
   "Choices 1 and 4 start with \"has decreased\". Choices 2 and 3 with \"has increased\".",
   D("Write choice 1 into the skeleton"),
   "Choice 1: the critics argue the checking time has decreased. Harel accepts that checking takes longer, but maintains the extra time is an improvement, and that the teachers' workload has become considerably lighter.",
   "Wait - he 'accepts' the opposite of what the critics said? And checking takes longer, but the workload got lighter? It doesn't hold together.",
   D("Cross out choice 1"),
   "Out. Same beginning next - choice 4.",
   "Choice 4: has decreased… Harel is convinced that checking takes longer, but adds in the same breath that the process has become far too slow.",
   "An improvement - and far too slow, in the same breath? Contradiction.",
   D("Cross out choice 4"),
  ]),
  ('Finish it', [
   "Now the \"has increased\" pair.",
   "Choice 2: the time has increased considerably. Harel does not dispute that checking takes longer, but maintains that, far from being a flaw, the extra time is evidence of a genuine improvement - and that students now receive far more detailed comments on their work.",
   A("Does not dispute ↔ but maintains that, far from being a flaw: concession, then his point appears", P('does not dispute … but maintains that, far from being a flaw … → a concession, then his own point', y=170)),
   "He concedes the critics' point, then turns it into an advantage. Everything connects.",
   D("Circle choice 2"),
   "Choice 2.",
   "Choice 3? On the exam you don't even read it. For the record: he admits checking takes longer - and says it's quicker. Out.",
   D("Cross out choice 3"),
  ]),
  ("Don't guess - check", [
   "One more warning.",
   "Sometimes you read a sentence and think: I get what they want, it's surely choice 2.",
   A("A hunch may pick the order - not the answer appears", P('A hunch may decide which option you try first - never the answer itself', y=170)),
   "That's fine - let the hunch decide which option you plug in first. It saves time.",
   "But don't mark it without checking. Change one connector and the same sentence means the opposite.",
   A("Most important: the skeleton · then don't re-check appears", P('Most important: the skeleton. And once it fits - trust yourself, mark, move on.', y=260)),
   "What I most want you to take from this lesson: the skeleton. Delete what you can, keep the bones. It saves a lot of time.",
   "And trust yourself: you found the one that fits? Mark it and run. If time's left at the end of the section - come back and check.",
  ])], T41),
# ------------------------------------------------------------------ lesson 2: hypothetical conditions (Hebrew 927–1029)
lesson('vr41-hypothetical', 'Hypothetical Conditions', SB_L2, [
 dict(mode='title', title='Hypothetical Conditions', script=[
  "Hypothetical conditions.",
  "Some of the hardest completions on the exam. Let's make them simple.",
 ]),
 dict(mode='concept', active=0, title='If it had…', script=[
  "A hypothetical condition is a condition that didn't happen - or can't happen.",
  "When we use one, we're asking: what would have happened if it had?",
  A("If X had happened, Y would have happened appears", C('If X had happened, Y would have happened', 150, 46)),
  "In English it sounds like this: if X had happened, Y would have happened.",
  A("Also: Had X happened… / Were X true… appears", C('Also written: Had X happened, … · Were X the case, …', 240)),
  "Sometimes without the \"if\": Had X happened… Were X the case…",
  A("If the bus had come on time, I would have caught the train → it didn't come; I missed the train appears",
    C('If the bus had come on time, I would have caught the train. → It didn’t come on time, and I missed the train.', 330, 36)),
  "\"If the bus had come on time, I would have caught the train.\" What really happened? The bus was late - and I missed the train.",
  "That's the easy kind.",
 ]),
 dict(mode='concept', active=1, title='Had it not been for', script=[
  "Now the harder kind - the negative one.",
  A("Had it not been for · Were it not for · But for · If … had not appears",
    C('Had it not been for X · Were it not for X · But for X · If X had not…', 150, 42)),
  "Had it not been for. Were it not for. But for. If… had not.",
  A("= if not appears", C('= “if not”', 240, 46)),
  "They all mean the same thing: if not. When you see one, just say \"if not\" in your head.",
  A("Were it not for the map, we would have gotten lost → there was a map; we didn't get lost",
    C('Were it not for the map, we would have gotten lost. → There was a map, and we didn’t get lost.', 320, 36)),
  "\"Were it not for the map, we would have gotten lost.\" If there hadn't been a map - lost. What really happened? There was a map, and we didn't get lost.",
  "With these words, everything flips - and that's exactly what makes the sentence hard to follow.",
 ]),
 dict(mode='concept', active=2, title='Reality is reversed', script=[
  "Notice what's common to both kinds.",
  A("What really happened = the reverse of what's written appears", C('What really happened = the reverse of what is written', 150, 44)),
  "Positive or negative - what really happened is exactly the reverse of what's written.",
  "\"If the bus had come on time…\" - it didn't. \"Were it not for the map…\" - there was one.",
  "And the result part flips too: I didn't catch the train. We didn't get lost.",
 ]),
 dict(mode='concept', active=3, title='Solve with a skeleton', script=[
  "So how do we solve these?",
  "Like every complicated question - skeleton, in your own words.",
  A("Replace the condition words: had → if · had it not been for → if not appears",
    C('Replace the condition words: had / were → “if” · had it not been for / but for → “if not”', 150, 38)),
  "Replace the condition words: had or were - write \"if\". Had it not been for, but for - write \"if not\".",
  A("Two parts: condition (if… / if not…) → result (…would / would not…) appears",
    C('Two parts: the condition (if… / if not…) → the result (…would / would not…)', 260, 38)),
  "A hypothetical sentence always has two parts: the condition - if something had or hadn't happened - and the result - something else would or wouldn't have happened.",
 ]),
 dict(mode='concept', active=4, title='The because trick', script=[
  "One more trick to see what really happened - for the negative words.",
  A("Had it not been for X, Y would… → Because of X, not Y appears",
    C('Had it not been for X, Y would have happened → Because of X, Y did not happen', 150, 40)),
  "Replace the negative condition with \"because\" - and negate the second part.",
  "\"Were it not for the map, we would have gotten lost\" → because of the map, we did not get lost.",
  A("Because + negate the second part = what really happened appears",
    C('“because” + negate the second part = what really happened', 260, 40)),
  "Now you're reading what actually happened - and it's much easier to check whether the sentence makes sense.",
 ]),
], T41),
# ------------------------------------------------------------------ guided: the two hypothetical examples
guided(0, 'vo-41-004', 'Completion Questions II', SBQ,
 ["Question three - a hypothetical condition.", "A hard one. Skeleton, and our two tricks."],
 [('Skeleton', [
   "As usual - skeleton first.",
   D("Bracket 'according to which the old building is safe' and write 'says: safe' above"),
   "\"the inspector's report, according to which the old building is safe\" - in my words: the report that says \"safe\".",
   A("___ the engineer found the \"safe\" report ___, the residents would not have been ___ their apartments appears",
     P('___ the engineer found the “safe” report ___ → the residents would not have been ___ their apartments', y=160)),
   "So: blank the engineer found the \"safe\" report blank - the residents would not have been blank their apartments.",
   D("Underline 'Had the engineer not' in choices 2 and 4"),
   "And in the choices - \"Had the engineer not\": our negative condition. If not.",
  ]),
  ('Plug in with "if not"', [
   D("Write choice 1: had the engineer / reliable / allowed to stay in"),
   "Choice 1: if the engineer had found the \"safe\" report reliable, the residents would not have been allowed to stay in their apartments.",
   "A reliable report that says the building is safe - and that's what would stop them staying? The reverse. Out.",
   D("Cross out choice 1"),
   D("Write choice 2: if the engineer had not / inaccurate / allowed to stay in"),
   "Choice 2, with \"if not\": if the engineer had not found the report inaccurate, the residents would not have been allowed to stay.",
   "Hard to follow? Use the because trick.",
   A("Because the engineer found it inaccurate → the residents were allowed to stay? appears",
     P('because: the engineer found the “safe” report inaccurate → the residents were allowed to stay?', y=200)),
   "Because the engineer found the \"safe\" report inaccurate - the residents were allowed to stay? No. If the report that says \"safe\" is wrong, you get them out.",
   D("Cross out choice 2"),
   "Out.",
  ]),
  ('The answer', [
   D("Write choice 3: had the engineer / inaccurate / ordered to leave"),
   "Choice 3: if the engineer had found the report inaccurate, the residents would not have been ordered to leave.",
   "An inaccurate \"safe\" report - and because of that they would stay? The reverse again. Out.",
   D("Cross out choice 3"),
   D("Write choice 4: had the engineer not / inaccurate / ordered to leave"),
   "Choice 4: if the engineer had not found the report inaccurate, the residents would not have been ordered to leave.",
   A("Because the engineer found it inaccurate → the residents were ordered to leave ✓ appears",
     P('because: the engineer found the “safe” report inaccurate → the residents were ordered to leave ✓', y=200)),
   "Because trick: because the engineer found the report that says \"safe\" inaccurate - the residents were ordered to leave. Makes perfect sense.",
   D("Circle choice 4"),
   "Choice 4.",
  ])], T41),
guided(1, 'vo-41-005', 'Completion Questions II', SBQ,
 ["Question four - a hypothetical condition, and a pile of negatives.", "Let's untangle it."],
 [('Untangle the negatives', [
   "Besides the hypothetical condition, this one stacks negatives: had I not known… I would not have been surprised… she refuses to lend.",
   A("Turn negatives into plain statements: refuses to lend = doesn't lend appears",
     P('Make it plain: “generally refuses to lend her tools” = she usually doesn’t lend them', y=160)),
   "First - say each piece plainly. \"Generally refuses to lend her tools\" - she usually doesn't lend them.",
   D("Write 'doesn't lend' above 'generally refuses to lend her tools'"),
   A("Skeleton: ___ [she doesn't lend], ___ when she ___ her new drill appears",
     P('Skeleton: ___ [she doesn’t lend], ___ when she ___ her new drill', y=230)),
   "Skeleton: blank that she doesn't lend, blank, when she blank her new drill.",
  ]),
  ('Plug in', [
   D("Write choice 1: Had I known / I would have been hurt / refused to lend me"),
   "Choice 1: if I had known she doesn't lend, I would have been hurt when she refused to lend me her drill.",
   "If I knew she doesn't lend - why be hurt when she refuses? Knowing is exactly what would stop me being hurt. Out.",
   D("Cross out choice 1"),
   "Choice 2: if I had not known, I would have been hurt when she offered to lend me her drill. Hurt by an offer? Out.",
   D("Cross out choice 2"),
   D("Write choice 3: Had I not known / I would not have been surprised / offered to lend me"),
   "Choice 3: if I had not known she doesn't lend, I would not have been surprised when she offered to lend me her new drill.",
   A("Because I knew she doesn't lend → I was surprised when she offered ✓ appears",
     P('because: I knew she doesn’t lend → I was surprised when she offered me her drill ✓', y=200)),
   "Because trick: because I knew she doesn't lend - I was surprised when she offered me her drill. Perfect.",
   D("Circle choice 3"),
   "Choice 3.",
  ]),
  ('For the lesson: choice 4', [
   "On the exam - mark it and move on. For the lesson, let's see why the last one fails.",
   "Choice 4: if I had known she doesn't lend, I would not have been surprised when she agreed to lend me the drill. Knowing - I would be surprised. Out.",
   A("Plug straight into the skeleton - never reread the whole sentence appears",
     P('Plug every option straight into the skeleton - no rereading the whole sentence', y=180)),
   "Notice: every option went straight into the skeleton. I never reread the full sentence.",
   "On the exam you don't write the skeleton separately - you just cross out words inside the sentence until the bones are left.",
   "These if-not questions are hard. You'll meet them now and then in practice tests. \"If not\" and the because trick - that's what makes them easier.",
  ])], T41),
]

MEMORY = [
 dict(id='mem-sentence-completion', after='vr41-hypothetical', title='Sentence completion - connectors and method',
  intro='The link between the parts of the sentence decides the answer. Know the connectors by what they do.',
  tables=[
   dict(title='Connectors by function', head=['Link', 'English connectors'], rows=[
    ['Contrast', 'but · however · although · even though · despite · nevertheless · yet · whereas · unlike'],
    ['Concession', 'admittedly … but · does not deny … but · even if · even so'],
    ['Cause / result', 'because · since · owing to · therefore · thus · for this reason · so'],
    ['Addition', 'and · moreover · and even · likewise · not only … but also'],
    ['Detail / example', 'for example · such as · that is · a colon ( : ) · a dash ( - )'],
    ['Condition', 'if · unless · only if · provided that'],
    ['Hypothetical', 'had … / were … (= if) · had it not been for · were it not for · but for (= if not)'],
   ]),
   dict(title='The method', head=['Step', 'What to do'], rows=[
    ['1', 'Shrink the sentence to its skeleton: cross out noise, rewrite hard parts briefly'],
    ['2', 'Read with an option in place - never with holes'],
    ['3', 'Plug in by similar beginnings; predict how the sentence should go on'],
    ['4', 'Parts contradict each other → eliminate (the sentence’s logic, not world knowledge)'],
    ['5', 'It fits → mark it and move on; don’t check the rest'],
   ]),
  ],
  tips=['Hypothetical: what really happened is the reverse of what is written.',
        'Had it not been for X, Y would… → because of X, not Y.',
        'A hunch may choose which option to try first - never mark without checking.']),
]
