# Verbal Reasoning · Topic 50 · Writing Task · part D: the content rubric.
# Backbone: the teacher's Hebrew lessons seg15-seg19 (content rubric overview, relevance to the task and the central
# idea, development of ideas, focus and coherence, critical thinking), translated with the teacher's running example
# (face-recognition cameras in public spaces). Official facts and criteria: nite_verbal_guide.txt (content table).
# Extra lesson (vr50-d-strong): the lessons of writing_src/findings.md, shown only with ORIGINAL paragraphs
# (free city buses) - no real exam task or sample essay is named, quoted or retold.
from dsl import *
from writing_assets import TASK_PAGE, ANSWER_SHEET, task_page, prompt_box, EXAMPLE_PROMPT, EXAMPLE_QUESTION

T50 = 50

CAM_PROMPT = [
    'Face-recognition cameras can identify a person automatically within',
    'seconds. Some countries allow security authorities to place such cameras',
    'in streets, stations and other public spaces. Supporters claim that the',
    'system will reduce crime and security incidents. Opponents warn that it',
    'violates privacy and that the data collected could be misused.',
]
CAM_QUESTION = ('In your opinion, should security authorities be allowed to install '
                'face-recognition cameras in public spaces? Give reasons.')

BUS_PROMPT = [
    'Several cities around the world have stopped charging fares on local',
    'buses. Supporters argue that free buses will take cars off the roads and',
    'help residents who cannot afford to travel. Opponents point out that',
    'fares pay for part of the service and that the money will have to come',
    'from somewhere else.',
]
BUS_QUESTION = 'In your opinion, should cities make local buses free of charge? Give reasons.'

SB_RUBRIC = ['What raters check', 'Words vs. criteria', 'Four rows, 1 to 6', 'Relevance + main idea',
             'Development', 'Focus', 'Coherence', 'Critical thinking', 'Opinion vs. fact',
             'Several perspectives', 'Opposing views', 'Next lessons']

SB_REL = ['Two terms', 'Say where you stand', 'Read the task closely', 'The background text', 'Use its ideas',
          'The question itself', 'Positions that fit', 'The complex position', 'The near miss', 'Reasons that fit',
          'The central idea', 'Inside each paragraph', 'Where it is scored']

SB_DEV = ['Two components', 'Variety', 'Same angle twice', 'A new angle', 'Finding varied reasons',
          'Logical and full', 'Too thin', 'What is missing', 'A full argument', 'Step by step', 'The official row',
          'Summary']

SB_FOC = ['Two terms', 'A long paragraph', 'Repeated words', 'Repeated ideas', 'Padding', 'Short but focused',
          'A jumpy paragraph', 'Linking, part 1', 'Linking, part 2', 'The fixed version', 'The wrong connector',
          'The official row']

SB_CRIT = ['Four components', 'Precise issue', 'Near miss: custody', 'Near miss: flights', 'Opinion vs. fact',
           'Why tasks are 50-50', 'Reasonable assumption', 'An opinion-only chain', 'Facts and assumptions',
           'Completing the chain', 'Several perspectives', 'Opposing views', 'What comes next']

SB_STRONG = ['Three levels', 'The exact question', 'Every part of it', 'Reasons that support', 'Add a step',
             'The missing link', 'Weak version', 'Adequate version', 'Strong version', 'The other side fairly',
             'Answer its worry', 'Claims and facts', 'Examples and length']


def para(t, y=120, size=29):
    """One long example paragraph, full width."""
    return T(t, size=size, x=410, y=y, w=1140)


MODULES = [
# ------------------------------------------------------------------ lesson 1: the content rubric (seg15)
lesson('vr50-d-content-rubric', 'The Content Rubric', SB_RUBRIC, [
 dict(mode='title', title='The Content Rubric', script=[
  "Let's meet the content rubric.",
  "This is the table the raters use to score the content of your essay.",
  "First a quick tour of everything in it. Then, lesson by lesson, we go deep into each part.",
 ]),
 dict(mode='concept', active=0, title='What raters check', script=[
  "Two raters read your essay. Each one gives content a score from one to six, and language a score from one to six.",
  A("Two raters · content 1-6 · language 1-6", T('Two raters · each gives content 1-6 and language 1-6', size=40, x=410, y=100, w=1140)),
  "The two components are rated separately. Great English does not rescue weak content, and the other way round.",
  A("Content is rated on its own", T('Content and language are rated independently of each other', size=34, x=410, y=190, w=1140)),
  "So what do they look at in content? Here is what the official guide says, in short.",
  A("The official list appears", T('Does the essay stay on the assigned topic?', size=32, x=440, y=280, w=1100)),
  A("Clarity", T('Are the ideas clear?', size=32, x=440, y=340, w=1100)),
  A("Logic", T('Are the arguments lucid, logically connected, and do they support the main idea?', size=32, x=440, y=400, w=1100)),
  A("No repetition", T('Is it free of unnecessary repetitions and vague statements?', size=32, x=440, y=500, w=1100)),
  A("Critical thinking", T('Does it show critical thinking?', size=32, x=440, y=560, w=1100)),
  "Keep this list in mind. Everything in the next lessons comes back to one of these questions.",
  A("They read a first draft", T('Raters know it is a first draft written in 35 minutes', size=34, x=410, y=660, w=1140)),
  "And one comforting fact: the raters are told to treat your essay as a first draft written under time pressure.",
 ]),
 dict(mode='concept', active=1, title='Words vs. criteria', script=[
  "Now, I'll be honest with you. The detailed wording in the table doesn't really help us.",
  A("The table's wording appears", T('"Very impressive" · "impressive" · "adequate" · "insufficient" · "very little"', size=34, x=410, y=110, w=1140)),
  "For critical thinking, for example, it says: very impressive, impressive, adequate, insufficient, very little.",
  "What is impressive? What is very little? You have nothing to compare with.",
  A("Only after thousands of essays", T('These words mean something only to someone who has rated thousands of essays', size=36, x=410, y=220, w=1140)),
  "A rater who has read thousands of essays knows exactly what impressive looks like. You and I can't use that.",
  A("We focus on the criteria", T('So we focus on the criteria - what is being checked', size=42, x=410, y=360, w=1140)),
  "So we'll focus on the criteria themselves: the left column of the table. What exactly is being checked.",
  D("teacher circles the left column of the table"),
 ]),
 dict(mode='concept', active=2, title='Four rows, 1 to 6', script=[
  "The content table has four rows.",
  A("Row 1", T('1 · Main idea and central thesis - relevant to the task, clear, well supported', size=34, x=410, y=100, w=1140)),
  "One: the main idea and the central thesis. Is it relevant to the task, and is it well supported?",
  A("Row 2", T('2 · Development of the thesis - full explanations, convincing and varied arguments', size=34, x=410, y=200, w=1140)),
  "Two: development of the thesis. Are the explanations full, and are the arguments convincing and varied?",
  A("Row 3", T('3 · Focus and coherence - no jumps, no unnecessary repetition', size=34, x=410, y=300, w=1140)),
  "Three: focus and coherence. Does one idea lead to the next, without jumps and without repeating yourself?",
  A("Row 4", T('4 · Critical thinking', size=34, x=410, y=400, w=1140)),
  "Four: critical thinking.",
  A("Scale", T('Each row: from 1 (very poor) to 6 (very good). The rater picks the description that fits best.', size=32, x=410, y=500, w=1140)),
  "Each row goes from one, very poor, to six, very good. Often no description fits perfectly, so the rater picks the closest one.",
  A("Our names", T('In our lessons: relevance + main idea · development · focus and coherence · critical thinking', size=32, x=410, y=640, w=1140)),
  "In our lessons we'll call them: relevance and the main idea, development, focus and coherence, and critical thinking.",
 ]),
 dict(mode='concept', active=3, title='Relevance + main idea', script=[
  "Let's start at the top. Relevance to the task, and the main idea.",
  A("Relevance to the task", T('Relevance to the task: how much does your content relate to the issue the task is about?', size=36, x=410, y=110, w=1140)),
  "Relevance to the task means: how closely is what you wrote connected to the issue the task deals with?",
  "Does what you wrote really answer what you were asked?",
  A("The central idea", T('The central idea: are your arguments clear, well explained, logically linked to each other - and do they express your position?', size=36, x=410, y=260, w=1140)),
  "The central idea is about your arguments. Are they clear? Well explained? Connected to each other logically? And do they express your position?",
  "That's the general idea. Now let's break it into the criteria that are checked.",
 ]),
 dict(mode='concept', active=4, title='Development', script=[
  "Development of ideas is mainly about two things.",
  A("Varied arguments", T('1 · How varied are your arguments?', size=40, x=410, y=110, w=1140)),
  "How varied your arguments are.",
  A("Fully and logically explained", T('2 · How fully and logically is each one explained?', size=40, x=410, y=190, w=1140)),
  "And how fully and logically each one is explained.",
  A("Claim + explanation", T('Claiming is not enough. You must explain why the claim is true - that explanation is the development.', size=36, x=410, y=300, w=1140)),
  "Look: you made a claim. Fine. But you need to explain why that claim is true. That explanation is called the development.",
  A("Take nothing for granted", T('Full · detailed · clear · takes nothing for granted', size=42, x=410, y=450, w=1140)),
  "It has to be full, detailed and clear, and it takes nothing for granted.",
 ]),
 dict(mode='concept', active=5, title='Focus', script=[
  "Next: focus and coherence. First, focus.",
  A("Focus", T('Focus: how precise and concise your text is - no repetitions, no padding', size=38, x=410, y=110, w=1140)),
  "Focus is how precise and concise your text is. You write what you want to say, without pouring out words.",
  A("The trap", T('"I have nothing more to say, but I need more lines..."', size=36, x=410, y=240, w=1140)),
  "Many students feel they have to write more, but they have nothing more to say.",
  A("What happens", T('→ the same sentences again · the same ideas in other words', size=36, x=410, y=330, w=1140)),
  "So they repeat sentences they already wrote, or the same ideas in other words. Padding and repetition.",
  A("Costs points", T('Raters take off a lot for this', size=42, x=410, y=450, w=1140)),
  "And that is something raters take off a lot of points for.",
 ]),
 dict(mode='concept', active=6, title='Coherence', script=[
  "Coherence means the text holds together.",
  A("Coherence", T('Coherence: a continuous line of thought - clear links between sentences and between ideas', size=36, x=410, y=110, w=1140)),
  "There is a continuous line of thought, and a clear connection between the sentences and between the ideas.",
  A("Don't jump", T('No jumping: one paragraph for, one paragraph against, and the rater has no idea where you stand', size=34, x=410, y=240, w=1140)),
  "You don't jump from topic to topic. One paragraph for, one paragraph against, and the rater doesn't even know your position.",
  "Are you for the cameras? Against the cameras? What's going on here?",
  A("Inside the text too", T('Also between sentences: a connector that does not fit, a conclusion that does not follow', size=34, x=410, y=380, w=1140)),
  "It's about your position, but also about the text itself. We use connectors between sentences, and sometimes they miss.",
  "I say one thing, and then I draw a conclusion that isn't connected to it.",
 ]),
 dict(mode='concept', active=7, title='Critical thinking', script=[
  "And the last row: critical thinking. Here the table spells out exactly what it means.",
  A("Four parts", T('Critical thinking =', size=40, x=410, y=100, w=1140)),
  A("Precise issue", T('· a precise definition of the issue', size=36, x=440, y=180, w=1100)),
  "A precise definition of the issue. That is really relevance again: are you talking about the issue you were asked about?",
  A("Opinion vs fact", T('· distinguishing between opinion and fact', size=36, x=440, y=250, w=1100)),
  "Distinguishing between opinion and fact.",
  A("Several perspectives", T('· examining the issue from several perspectives', size=36, x=440, y=320, w=1100)),
  "Examining the issue from several perspectives.",
  A("Opposing views", T('· dealing with opposing views (refuting them)', size=36, x=440, y=390, w=1100)),
  "And dealing with opposing views. Let's go over them one by one.",
 ]),
 dict(mode='concept', active=8, title='Opinion vs. fact', script=[
  "Opinion versus fact.",
  A("The mistake", T('A common mistake: stating your opinions as if they were facts', size=38, x=410, y=110, w=1140)),
  "Many students simply state things that are their opinion, but treat them as facts.",
  A("House of cards", T('Build a whole house of cards on an opinion...', size=36, x=410, y=230, w=1140)),
  "And then they build a whole house of cards on top of that opinion.",
  A("It collapses", T('...and one reader saying "that is not a fact, it is just your opinion" brings it all down', size=36, x=410, y=310, w=1140)),
  "All it takes is someone saying: wait, your first assumption isn't really a fact. It's just your opinion. And the whole tower collapses.",
 ]),
 dict(mode='concept', active=9, title='Several perspectives', script=[
  "Several perspectives.",
  A("Not one narrow angle", T('Not one narrow angle: "money, money, money"', size=40, x=410, y=110, w=1140)),
  "They want to see that you can look at the issue not from one very narrow angle. Only money. Economic, economic, economic.",
  A("Different angles", T('Different angles → different consequences', size=40, x=410, y=210, w=1140)),
  "No. You look from different points and see different consequences. We'll go deeper into this later.",
 ]),
 dict(mode='concept', active=10, title='Opposing views', script=[
  "And dealing with opposing views.",
  A("No right and wrong", T('There is no "right" and "wrong" here - there are positions, each with advantages and disadvantages', size=36, x=410, y=110, w=1140)),
  "It means you see the other side. You understand there's no right and wrong here. There are two positions, sometimes more, each with its advantages and disadvantages.",
  A("Respect and answer", T('See the issue from the other side\'s point of view · treat it with respect · answer it', size=36, x=410, y=260, w=1140)),
  "You can look at the issue from the other side's point of view, treat it with respect, and deal with it.",
  A("Think ahead", T('Know the weak points of your own arguments - and deal with them in advance', size=36, x=410, y=390, w=1140)),
  "There are counter-arguments. I want to weaken them. I took them into account. I don't just throw an argument into the air.",
  "I think about the weak points of my own arguments, and I deal with them in advance.",
 ]),
 dict(mode='concept', active=11, title='Next lessons', script=[
  "That was the general tour of the content rubric.",
  A("Coming up", T('Next: each criterion in depth, with examples', size=42, x=410, y=110, w=1140)),
  A("List", T('Relevance and the central idea → development → focus and coherence → critical thinking', size=34, x=410, y=210, w=1140)),
  "Now we go deep into each of these criteria, with examples. As usual, I'll see you in the next lesson.",
 ]),
], T50),

# ------------------------------------------------------------------ lesson 2: relevance and the central idea (seg16)
lesson('vr50-d-relevance', 'Relevance and the Central Idea', SB_REL, [
 dict(mode='title', title='Relevance and the Central Idea', script=[
  "Now we go deep into the content rubric.",
  "We start with relevance to the task, and the central idea.",
 ]),
 dict(mode='concept', active=0, title='Two terms', script=[
  "First, two terms.",
  A("Relevance", T('Relevance to the task = the link between what you write and the issue the task deals with', size=36, x=410, y=110, w=1140)),
  "Relevance to the task is the link between what we write and the issue the task deals with.",
  A("Central idea", T('The central idea = how clear your arguments are, how logically they connect, and how well they explain your position', size=36, x=410, y=250, w=1140)),
  "The central idea is how clear our arguments are, how logically they connect to each other, and how well they explain our position.",
 ]),
 dict(mode='concept', active=1, title='Say where you stand', script=[
  "Here's a common problem.",
  A("The problem", T('No position in the opening paragraph → one paragraph for, one against → the reader is lost', size=36, x=410, y=110, w=1140)),
  "Students don't state their position in the opening paragraph, as we recommend.",
  "Then one paragraph is for the cameras, the next is against the cameras, and the reader no longer understands what you want. For? Against?",
  A("Discussing both sides is fine", T('Discussing both sides is fine - and even needed', size=38, x=410, y=260, w=1140)),
  "Now, it is fine to discuss the issue from several angles, for and against, and to deal with the opposing view.",
  A("But first...", T('But before anything else, the reader must know what you want', size=42, x=410, y=360, w=1140)),
  "But before anything else, the reader has to understand what you want from him.",
 ]),
 dict(mode='concept', active=2, title='Read the task closely', script=[
  "It is really, really important to read the task. And to read it carefully.",
  A("Read, don't skim", T('Read it - don\'t skim it', size=44, x=410, y=110, w=1140)),
  "I don't skim the background. I actually give it time. We'll have a whole lesson on analysing the task later.",
  A("Two parts", T('Two parts: the background text + the discussion question', size=40, x=410, y=210, w=1140)),
  "The task has two parts: the background text, and the discussion question at the end.",
  A("Look for", T('Look for: hints · important words · ideas for arguments', size=38, x=410, y=310, w=1140)),
  "Pay attention to everything there: hints, important words, ideas for arguments.",
  A("Answer the question", T('Above all: answer the discussion question - the bold line at the end', size=38, x=410, y=420, w=1140)),
  "And above all, answer the discussion question. The line in bold at the end.",
 ]),
 dict(mode='concept', active=3, title='The background text', script=[
  "Let's take the example we already know: face-recognition cameras in public spaces.",
  A('The task appears', dict(prompt_box(CAM_PROMPT, CAM_QUESTION, w=1140), x=410, y=50)),
  "The first part is the background text. Think of it as a teaser.",
  A("A teaser", T('The background text is a teaser: "here is what your essay is going to be about"', size=34, x=410, y=420, w=1140)),
  "A teaser says: come, let me show you what you're about to read. The background tells us what the essay is going to contain.",
  A("Then the question", T('Then comes the discussion question - that is the issue itself', size=34, x=410, y=520, w=1140)),
  "Then comes the discussion question. And that is the actual issue.",
  D("teacher underlines 'Supporters claim that the system will reduce crime and security incidents'"),
 ]),
 dict(mode='concept', active=4, title='Use its ideas', script=[
  "Why did I mention the teaser? Because the background often contains ideas for arguments.",
  A("Ideas inside", T('"Supporters claim that the system will reduce crime and security incidents" = an idea for an argument', size=34, x=410, y=110, w=1140)),
  "Look here: supporters claim the system will reduce crime and security incidents.",
  A("Don't be afraid", T('Don\'t be afraid to use it', size=44, x=410, y=240, w=1140)),
  "Some students are afraid to take ideas from here. They say: no, I need to show creativity, I want to think of arguments myself.",
  "Thinking of arguments yourself is fine. But the background is there to help you start writing.",
  A("An idea is not a 6", T('An idea handed to you is not a 6. You still have to develop it and support it.', size=36, x=410, y=340, w=1140)),
  "The message is: take what's here and build an essay from it. Giving you an idea for an argument doesn't mean you now get a six.",
  "You still have to take the idea, develop it and support it.",
  A("Why the background is long", T('Short background → many students drift away from the issue. So tasks come with a fuller background that points you in a direction.', size=32, x=410, y=480, w=1140)),
  "Why is the background there at all? With only a short background, many students drifted completely away from the issue.",
  "That's why tasks come with a fuller background: it gives context and points you towards what to write about.",
 ]),
 dict(mode='concept', active=5, title='The question itself', script=[
  "In fact, they could have asked us only the question.",
  A("The question", T(CAM_QUESTION, size=38, x=410, y=110, w=1140)),
  "In your opinion, should security authorities be allowed to install face-recognition cameras in public spaces? Give reasons.",
  "I could write an essay on that alone. But the background helps: it gives directions where to start and roughly what they want us to discuss.",
  A("Mark words", T('Read the background, analyse it, and mark the important words', size=38, x=410, y=300, w=1140)),
  "So read the background, analyse it, and mark the important words that will help you later.",
  D("teacher underlines 'should ... be allowed' and 'in public spaces'"),
 ]),
 dict(mode='concept', active=6, title='Positions that fit', script=[
  "Since we know this task, let's just look at possible opening positions.",
  A("For", T('"In my opinion, security authorities should be allowed to install face-recognition cameras in public spaces."  ✓', size=32, x=410, y=100, w=1140)),
  "In my opinion, they should be allowed. That's my opinion. Of course I'll need to explain why. But it's fine.",
  A("Against", T('"In my opinion, security authorities should not be allowed to install face-recognition cameras in public spaces."  ✓', size=32, x=410, y=230, w=1140)),
  "In my opinion, they should not be allowed. Also fine. Again, I'll have to explain why.",
  A("With conditions", T('"In my opinion, security authorities should be allowed to install face-recognition cameras in public spaces, but only under certain conditions."  ✓', size=32, x=410, y=360, w=1140)),
  "In my opinion, they should be allowed, but only under certain conditions.",
  "Many students are afraid of this one. They asked yes or no, didn't they? So is it yes or no?",
  A("That's fine", T('A complex position - perfectly fine', size=40, x=410, y=520, w=1140)),
  "We'll see that it's perfectly fine. It's simply a complex position.",
 ]),
 dict(mode='concept', active=7, title='The complex position', script=[
  "Why is the complex position fine, and even more logical?",
  A("Not black and white", T('Life is not black and white - every position has advantages and disadvantages', size=38, x=410, y=110, w=1140)),
  "Because we don't see life in black and white. There's grey too. Each position has advantages and disadvantages.",
  A("What it says", T('"In principle I support the cameras, but I see the problem, and I want safeguards and limits to reduce the harm to privacy."', size=34, x=410, y=240, w=1140)),
  "It says: in principle, I lean towards installing the cameras. But I understand there's a problem here, and I want to deal with it.",
  "I want safeguards, protections and limits, to reduce the harm to privacy as much as possible.",
  A("Critical thinking", T('It shows critical thinking - as long as you state clearly what you support and where the limit is', size=34, x=410, y=400, w=1140)),
  "That shows critical thinking. Just make sure you say clearly what you support and where your limit is.",
  "One more thing: a middle position is not a bonus in itself. Yes, no, or yes-with-conditions: any of them can score high if it is well argued.",
 ]),
 dict(mode='concept', active=8, title='The near miss', script=[
  "Now look at this last sentence.",
  A("The sentence", T('"In my opinion, security authorities can be trusted to do their job ethically and not to misuse face-recognition cameras."  ✗', size=32, x=410, y=100, w=1140)),
  "In my opinion, security authorities can be trusted to do their job ethically and not to misuse face-recognition cameras.",
  "Nobody asked whether they will do it ethically. This sentence misses the discussion question. The relevance is very weak.",
  A("Same topic ≠ same question", T('Same topic ≠ the question you were asked', size=40, x=410, y=240, w=1140)),
  "Yes, it's the same topic. And it could lead to a legitimate argument: maybe the people watching the cameras will leak the database.",
  "Maybe they'll follow people they know, their neighbours. Maybe that really could happen. It's a legitimate concern.",
  A("The question was", T('They asked: should the cameras be allowed? - not: are security authorities ethical?', size=34, x=410, y=340, w=1140)),
  "But they didn't ask us whether security people are ethical. They asked whether to allow the cameras.",
  A("Where it belongs", T('Where the concern belongs: inside the complex position - "some staff may misuse the data, so I want these limits..."', size=32, x=410, y=460, w=1140)),
  "In the complex position I can use it: I understand that some security staff may abuse their access, so I propose limits to prevent or reduce it.",
  "But as a position, this sentence does not answer the question.",
 ]),
 dict(mode='concept', active=9, title='Reasons that fit', script=[
  "Relevance is not only about your position.",
  A("Also the arguments", T('Relevance is checked in your arguments too - not only in your position', size=38, x=410, y=110, w=1140)),
  "During the essay you also present arguments. Make sure they clearly support your position.",
  A("Key sentences", T('Each argument paragraph opens with a key sentence: position + reason', size=38, x=410, y=220, w=1140)),
  "The arguments in the body of the essay are called key sentences. Each argument paragraph starts with one.",
  A("Then development", T('After it: the development - why the key sentence is true', size=38, x=410, y=320, w=1140)),
  "After each key sentence, we explain it: why we think our argument, our key sentence, is true.",
 ]),
 dict(mode='concept', active=10, title='The central idea', script=[
  "Now, the central idea.",
  A("Definition", T('The central idea: your arguments are clear, logically linked to each other, and support your position', size=36, x=410, y=110, w=1140)),
  "How clear the arguments in your essay are. Whoever reads them understands what you want to say. They connect logically, and they support your position.",
  A("Official wording", T('The official guide: the central idea must be clearly worded, and all other ideas and arguments in the essay must relate to it', size=32, x=410, y=260, w=1140)),
  "The official guide says it clearly: the central idea must be clearly worded, and every other idea and argument in the essay must relate to it.",
  A("Whole essay", T('Opening paragraph → argument 1 → argument 2 → ... → closing paragraph', size=34, x=410, y=400, w=1140)),
  "That's the line of the whole essay: opening paragraph, argument one, argument two, and so on.",
 ]),
 dict(mode='concept', active=11, title='Inside each paragraph', script=[
  "But the central idea isn't only the line of the whole essay.",
  A("Inside each paragraph", T('Inside every paragraph there is a line too', size=42, x=410, y=110, w=1140)),
  "Inside every paragraph there's also a line: the development of my key sentence must be in logical order.",
  A("Links", T('A  →  B  →  C  →  D  →  the result', size=48, x=410, y=220, w=1140)),
  "The development is made of steps, links, like mini-arguments. A leads to B, B leads to C, C leads to D, and here I am at the result I wanted.",
  A("The chain", T('This is the chain - we plan it before we write', size=38, x=410, y=340, w=1140)),
  "That is exactly the chain we plan before writing. We'll see it in the lesson on development.",
 ]),
 dict(mode='concept', active=12, title='Where it is scored', script=[
  "Where does all this show up in the rubric?",
  A("Central idea", T('The central idea shows in three criteria: development · focus and coherence · critical thinking', size=34, x=410, y=110, w=1140)),
  "The central idea shows up in three criteria: development, focus and coherence, and critical thinking.",
  A("Relevance", T('Relevance shows mainly in development: are my arguments really about what I was asked?', size=34, x=410, y=240, w=1140)),
  "Relevance shows up mainly in development: I make sure my arguments really relate to what I was asked.",
  A("Mapping", T('Focus and coherence ≈ the central idea · critical thinking = covers everything', size=34, x=410, y=370, w=1140)),
  "Focus and coherence fit the central idea more. And critical thinking covers everything.",
  "So we understand broadly what they want from the content. Next, the criteria one by one. See you in the next lesson.",
 ]),
], T50),

# ------------------------------------------------------------------ lesson 3: development of ideas (seg17)
lesson('vr50-d-development', 'Development of Ideas', SB_DEV, [
 dict(mode='title', title='Development of Ideas', script=[
  "We continue with the content rubric.",
  "Development of ideas: how varied your arguments are, and how logical and full each one is.",
 ]),
 dict(mode='concept', active=0, title='Two components', script=[
  "Development of ideas has two components.",
  A("Variety", T('1 · Variety - arguments from different points of view, not one narrow angle', size=38, x=410, y=110, w=1140)),
  "Variety. The arguments come from different points of view, not from one very narrow angle.",
  A("Logical and full", T('2 · Logical and full - the reader says: "Ah, I see why you think that"', size=38, x=410, y=240, w=1140)),
  "And logic and fullness: how well I explain my argument, so that the reader says: ah, OK, I understand why you think this is true.",
 ]),
 dict(mode='concept', active=1, title='Variety', script=[
  "Let's start with variety. Say my first argument paragraph is against the cameras.",
  A("Argument 1", T('Argument 1: "In my opinion, security authorities should not be allowed to install face-recognition cameras in public spaces, since this will violate the public\'s right to privacy."', size=32, x=410, y=110, w=1140)),
  "In my opinion, they should not be allowed, since it will violate the public's right to privacy.",
  "That's true, and of course I'd have to go on and explain it. But right now we're not talking about the explanation. We're talking about variety.",
 ]),
 dict(mode='concept', active=2, title='Same angle twice', script=[
  "Now the second paragraph.",
  A("Argument 2", T('Argument 2: "In addition, installing face-recognition cameras in public spaces may give security authorities the personal information of private people without their consent."', size=32, x=410, y=110, w=1140)),
  "In addition, installing face-recognition cameras may give security authorities the personal information of private people without their consent.",
  "Wait. We have a problem here. No variety.",
  A("The same thing", T('Privacy (general)  ≈  personal information without consent (specific) → the same point of view', size=34, x=410, y=290, w=1140)),
  D("teacher links 'right to privacy' and 'personal information without their consent'"),
  "One talks about the right to privacy. The other talks about personal information taken without consent. It's the same thing in other words.",
  "Privacy is general; the second is a bit more specific. But it's not a different angle. It's the same narrow point of view.",
 ]),
 dict(mode='concept', active=3, title='A new angle', script=[
  "Let's see how to improve it.",
  A("Better argument 2", T('Argument 2: "In addition, installing face-recognition cameras in public spaces may not reduce crime, since criminals will not stop committing crimes but will move their activity to unmonitored areas."', size=32, x=410, y=110, w=1140)),
  "In addition, the cameras may not reduce crime, since criminals won't stop. They'll move their activity to unmonitored areas.",
  A("Two angles", T('Argument 1: harm to privacy  ·  Argument 2: it will not even work', size=38, x=410, y=290, w=1140)),
  "Now this is a varied argument. First I was against the cameras because they harm privacy.",
  "Now I'm against the cameras because they won't help. There won't be less crime. It'll just move: not in the public space? Fine, let's do it next door.",
  A("Critical thinking", T('Different points of view → higher critical thinking', size=38, x=410, y=400, w=1140)),
  "That's a nice example of arguments from different points of view. It shows high critical thinking.",
  "Of course all of this is very condensed. We still need to develop, detail and explain it.",
 ]),
 dict(mode='concept', active=4, title='Finding varied reasons', script=[
  "So our arguments need to be varied.",
  A("Hard part", T('Finding varied arguments is one of the hardest parts for students', size=38, x=410, y=110, w=1140)),
  "Finding varied arguments is one of the things students struggle with most.",
  A("Techniques ahead", T('Coming later: rights (of the person and of society) · zoom out · zoom in', size=36, x=410, y=220, w=1140)),
  "Later we have lessons with techniques for finding arguments: rights, which I'm sure you know, human rights and society's rights, and zoom out and zoom in.",
  "I won't say more about those names now. They make finding varied arguments much, much easier.",
 ]),
 dict(mode='concept', active=5, title='Logical and full', script=[
  "The next step: how logical and full our arguments are. How good the explanation is.",
  A("The test", T('The reader must see how you got from your claim to your result', size=40, x=410, y=110, w=1140)),
  "Whoever reads what we wrote must understand how we got from what we think to the result we reached.",
  "Let's look at some examples.",
 ]),
 dict(mode='concept', active=6, title='Too thin', script=[
  A("Thin paragraph", para('"In my opinion, security authorities should be allowed to install face-recognition cameras in public spaces, since installing cameras will reduce the level of crime. When a person\'s behaviour is monitored, the chance that he will behave according to accepted social norms increases. Therefore, installing face-recognition cameras will cause criminals to avoid committing crimes and will protect the population."', y=100)),
  "In my opinion, they should be allowed, since the cameras will reduce crime. When a person's behaviour is monitored, the chance that he'll behave according to accepted social norms increases.",
  "Therefore, the cameras will cause criminals to avoid committing crimes and will protect the population.",
  A("Verdict", T('Too short · not full · not detailed enough', size=40, x=410, y=470, w=1140)),
  "This paragraph is a bit too short. The argument isn't full enough, not detailed enough.",
 ]),
 dict(mode='concept', active=7, title='What is missing', script=[
  "Where exactly is the gap?",
  A("The jump", T('"social norms"  → ? →  "criminals avoid crimes"  → ? →  "protects the population"', size=38, x=410, y=110, w=1140)),
  "It talks about social norms, and suddenly I jump straight to criminals, crimes and protecting the population.",
  A("Questions", T('Why would an ordinary person\'s norms explain a criminal\'s decision? How exactly does that protect the population?', size=34, x=410, y=240, w=1140)),
  "Why would norms of behaviour explain what a criminal decides? And how exactly does that protect the population? The steps are missing.",
  A("The fix", T('Fill the missing links - each step must lead to the next', size=40, x=410, y=390, w=1140)),
  "The fix: fill in the missing links, so that each step leads to the next.",
 ]),
 dict(mode='concept', active=8, title='A full argument', script=[
  "Now an argument that is full and detailed.",
  A("Full paragraph", para('"In my opinion, security authorities should not be allowed to install face-recognition cameras in public spaces, since doing so will not reduce the level of crime. The cameras will not be installed secretly; the public will know that its actions in public spaces are being recorded. Assuming that criminals will know this too, they may not stop committing crimes but simply move their activity to unmonitored areas, particularly to private property. The result would be a situation in which crime does not decrease but merely moves to places that the face-recognition cameras do not cover."', y=100)),
  "In my opinion, they should not be allowed, since it will not reduce crime.",
  "When I read only this key sentence, it sounds strange. Really? It sounds logical to me that cameras reduce crime. How can that be? Explain it to me.",
  "So he explains. The cameras won't be installed secretly. The public will know it's being recorded. OK, true.",
  "Assuming criminals know it too, and they will, they may not stop. A criminal still 'needs his salary'. Stealing is his job.",
  "So he won't steal here. He'll steal there. That doesn't mean he steals less. Crime doesn't shrink, it just moves.",
 ]),
 dict(mode='concept', active=9, title='Step by step', script=[
  "Look at the steps he gave us.",
  A("Step 1", T('1 · The cameras will not be secret - the public will know', size=34, x=440, y=100, w=1100)),
  A("Step 2", T('2 · Criminals will know too', size=34, x=440, y=170, w=1100)),
  A("Step 3", T('3 · So they may move their activity to unmonitored areas', size=34, x=440, y=240, w=1100)),
  A("Step 4", T('4 · So crime does not decrease - it only moves', size=34, x=440, y=310, w=1100)),
  "If this, then this, then this. And here we are at the result: crime won't really go down.",
  A("Verdict", T('An opinion - but an explained opinion', size=42, x=410, y=420, w=1140)),
  "Maybe. It's his opinion. But it's an opinion he explained, step by step.",
  A("Notice", T('The stranger the key sentence sounds, the more the reader needs the steps', size=36, x=410, y=520, w=1140)),
  "Notice: the stranger the key sentence sounds at first, the more the reader needs these steps.",
 ]),
 dict(mode='concept', active=10, title='The official row', script=[
  "Here is what the official table says for development at the top levels.",
  A("Level 4", T('4: explanations mostly adequate · fairly convincing arguments · appropriate examples', size=32, x=410, y=110, w=1140)),
  "At level four: mostly adequate explanations, fairly convincing arguments, appropriate examples.",
  A("Level 5", T('5: relevant and detailed · full explanations · convincing arguments', size=32, x=410, y=210, w=1140)),
  "At five: relevant and detailed, full explanations, convincing arguments.",
  A("Level 6", T('6: relevant, detailed and insightful · full explanations · convincing and varied arguments', size=32, x=410, y=310, w=1140)),
  "And at six: insightful, with full explanations and convincing and varied arguments.",
  A("Low levels", T('Low levels: inadequate explanations · unconvincing arguments · inappropriate examples', size=32, x=410, y=430, w=1140)),
  "At the low levels the words are: inadequate explanations, unconvincing arguments, inappropriate examples.",
  D("teacher circles 'full explanations' and 'varied'"),
  "Our two components, full and varied, are right there in the wording.",
 ]),
 dict(mode='concept', active=11, title='Summary', script=[
  "Let's sum up development of ideas.",
  A("Varied", T('Varied arguments - from different points of view', size=40, x=410, y=110, w=1140)),
  "We want varied arguments, from different points of view. We'll learn how to find them.",
  A("Logical and full", T('Logical, full explanations - every step from the claim to the result', size=40, x=410, y=210, w=1140)),
  "And logical, full explanations: the reader understands how we got from what we think to the result.",
  "Next criterion: focus and coherence. See you there.",
 ]),
], T50),

# ------------------------------------------------------------------ lesson 4: focus and coherence (seg18)
lesson('vr50-d-focus', 'Focus and Coherence', SB_FOC, [
 dict(mode='title', title='Focus and Coherence', script=[
  "Focus and coherence.",
  "Two of the easiest places to lose points, and two of the easiest to fix.",
 ]),
 dict(mode='concept', active=0, title='Two terms', script=[
  A("Focus", T('Focus: the text is concise and precise - no repetition, no padding', size=38, x=410, y=110, w=1140)),
  "Focus: how concise and precise our text is, with no repetition and no padding. We write exactly what we want, and we don't ramble.",
  A("Coherence", T('Coherence: a continuous line of thought - clear links between ideas, sentences and parts of sentences; no jumping', size=36, x=410, y=240, w=1140)),
  "Coherence: the line of thought. Everything is clear. There's a clear link between the ideas, between the sentences, between the parts of sentences. No jumping from topic to topic.",
  "Let's see some examples.",
 ]),
 dict(mode='concept', active=1, title='A long paragraph', script=[
  "Read this paragraph.",
  A("The paragraph", para('"In my opinion, face-recognition cameras should be installed, because their presence in public spaces will provide law-enforcement agencies with unequivocal proof, beyond any doubt, of the offence and of the offender\'s identity, a fact that will deter citizens from breaking the law in public spaces and will reduce crime in the country. For example, a person who is considering breaking the law, whether by committing a minor offence such as stealing an ice lolly from a kiosk or a more serious offence such as violence or even murder, will be afraid to commit the offence because the presence of cameras in public spaces increases the chance that he will be caught. In this way, the cameras will deter potential offenders, who will be afraid to break the law in case they are caught and punished, and therefore many of them will avoid committing the offence. Thus, fewer crimes will occur in the country."', y=90, size=28)),
  "Long, right? It looks rich. Let's go through it again and look for the repetition and the padding.",
 ]),
 dict(mode='concept', active=2, title='Repeated words', script=[
  "First, words that repeat.",
  A("Words", T('public spaces × 3 · offence × 5 · break the law × 3', size=40, x=410, y=110, w=1140)),
  D("teacher highlights every 'public spaces', 'offence' and 'break the law'"),
  "Public spaces, public spaces, public spaces. Offence, offence, offence. Break the law, break the law.",
  A("Language fix", T('Fix with pronouns and rewording (the language rubric): "there", "such acts", "it"...', size=34, x=410, y=220, w=1140)),
  "That's not good, and you know it from the language lessons: we fix it with pronouns and rewording.",
  A("But more", T('The bigger problem here: repeated IDEAS', size=42, x=410, y=340, w=1140)),
  "But the problem here goes beyond repeated words. The repetition is at the level of ideas.",
 ]),
 dict(mode='concept', active=3, title='Repeated ideas', script=[
  "Let's mark the sentences by idea.",
  A("Doubled phrase", T('"unequivocal" = "beyond any doubt"', size=34, x=440, y=100, w=1100)),
  "Unequivocal and beyond any doubt: the same thing. Repeating it doesn't really emphasise anything. It's just repetition.",
  A("Deterrence 1", T('"will deter citizens from breaking the law"', size=34, x=440, y=180, w=1100)),
  A("Deterrence 2", T('= "will be afraid to commit the offence ... increases the chance that he will be caught"', size=34, x=440, y=240, w=1100)),
  A("Deterrence 3", T('= "will deter potential offenders ... in case they are caught and punished"', size=34, x=440, y=340, w=1100)),
  A("Result", T('"reduce crime" = "avoid committing the offence" = "fewer crimes will occur"', size=34, x=440, y=440, w=1100)),
  "Deter citizens from breaking the law. Afraid to commit the offence because he might be caught. Deter offenders in case they are caught. The same idea in three colours.",
  "Reduce crime, avoid committing the offence, fewer crimes. The same result, again and again.",
  A("Verdict", T('A long paragraph - but really about one and a half sentences, repeated', size=38, x=410, y=560, w=1140)),
  "It looks long and rich, but in practice it's about one and a half sentences, repeated in different words. No real development.",
 ]),
 dict(mode='concept', active=4, title='Padding', script=[
  "And this sentence:",
  A("The padding", T('"...whether by committing a minor offence such as stealing an ice lolly from a kiosk or a more serious offence such as violence or even murder..."', size=34, x=410, y=110, w=1140)),
  D("teacher crosses out the ice lolly and the murder"),
  "We don't need all this detail. It's padding. Its only purpose is to make the paragraph bigger. It tells us nothing new.",
  A("The idea of focus", T('Focus = say it once, precisely - not again in other words, style or wording', size=38, x=410, y=300, w=1140)),
  "The whole idea of focus: be concise. Don't return to the same idea again and again in other words or other wording.",
 ]),
 dict(mode='concept', active=5, title='Short but focused', script=[
  "So what should you do?",
  A("Better", T('Better a shorter, focused paragraph', size=46, x=410, y=110, w=1140)),
  "Better to write a shorter paragraph that is focused and concise.",
  A("Why", T('Even if your development isn\'t perfect - at least you won\'t lose extra points for repetition and padding', size=36, x=410, y=220, w=1140)),
  "Even if it isn't perfect, even if you feel your development isn't good enough, at least you won't lose extra points for repetition and padding.",
  A("Length", T('Need more lines? Add a new step, not the same step again.', size=38, x=410, y=370, w=1140)),
  "Need more lines? Add a new step to the explanation, not the same step again.",
  "This paragraph gets a big X for repetition and padding.",
 ]),
 dict(mode='concept', active=6, title='A jumpy paragraph', script=[
  "Now coherence: the line of thought. Read this one.",
  A("The paragraph", para('"I believe that installing face-recognition cameras in public spaces is a desirable step. Installing face-recognition cameras in public spaces can reduce crime. The law-abiding public will benefit from constant monitoring of what happens in public spaces and from a real-time response to unusual events. The justice system will be able to do its work more efficiently, since the identification cameras will be able to provide it easily and quickly with evidence that can be used against criminals who committed crimes in public spaces. When a criminal knows that there is a system that follows his actions and a police team that will go after him if he commits a crime, he will think carefully before he acts."', y=90, size=28)),
  "Did you notice? Even I got stuck reading it. It's hard to read. There are jumps. There's no clear line of thought.",
  A("Verdict", T('Every sentence is fine on its own - but they are not connected', size=36, x=410, y=560, w=1140)),
  "Each sentence on its own is fine. But they're not connected to each other. Let's fix it.",
 ]),
 dict(mode='concept', active=7, title='Linking, part 1', script=[
  "Sentence one: installing the cameras is a desirable step. Why? Why is it desirable?",
  A("Step 1", T('"...is a desirable step, since it can reduce crime."', size=36, x=410, y=110, w=1140)),
  "Because it can reduce crime. So we join them with 'since', a connector of explanation. The second part explains the first.",
  "And we also drop the repeated 'installing face-recognition cameras in public spaces'. We just say 'it'.",
  A("Step 2", T('"Consequently, the law-abiding public will benefit from constant monitoring of what happens in the monitored areas..."', size=34, x=410, y=240, w=1140)),
  "Next: the public will benefit. How is that connected? It's the result. We reduced crime, and that leads to the public benefiting.",
  "So we add 'consequently'. And instead of 'public spaces' yet again, 'the monitored areas'.",
 ]),
 dict(mode='concept', active=8, title='Linking, part 2', script=[
  "Next sentence: the justice system will work more efficiently.",
  A("Step 3", T('"In addition, the justice system will be able to work more efficiently, since the cameras will provide it quickly and easily with evidence against those who broke the law."', size=34, x=410, y=100, w=1140)),
  "That's another advantage, another reason it's desirable. So: 'In addition'. And 'the cameras', not 'the identification cameras' again. 'Those who broke the law', not 'in public spaces' again.",
  A("Step 4", T('"Moreover, when a person knows that a system follows his actions and that a police team will go after him if he commits a crime, he will think carefully before he acts."', size=34, x=410, y=300, w=1140)),
  "Last sentence. Is it connected to the justice system? No. It's one more advantage, deterrence.",
  "I already used 'in addition', so I vary it: 'Moreover'. And 'a person', not 'a criminal'. He isn't a criminal yet.",
 ]),
 dict(mode='concept', active=9, title='The fixed version', script=[
  A("Fixed paragraph", para('"I believe that installing face-recognition cameras in public spaces is a desirable step, since it can reduce crime. Consequently, the law-abiding public will benefit from constant monitoring of what happens in the monitored areas and from a real-time response to unusual events. In addition, the justice system will be able to work more efficiently, since the cameras will provide it quickly and easily with evidence against those who broke the law. Moreover, when a person knows that a system follows his actions and that a police team will go after him if he commits a crime, he will think carefully before he acts."', y=90, size=29)),
  "We didn't make this paragraph perfect. But the line of thought is now much clearer.",
  A("The skeleton", T('desirable → since: less crime → consequently: the public benefits → in addition: courts → moreover: deterrence', size=32, x=410, y=500, w=1140)),
  "A desirable step, since it reduces crime. Consequently, the public benefits. In addition, the justice system. Moreover, deterrence.",
 ]),
 dict(mode='concept', active=10, title='The wrong connector', script=[
  A("The paragraph", para('"In my opinion, face-recognition cameras in public spaces will make it possible to reduce the number of offences and crimes in public spaces. These cameras will help detect suspicious activity before an offence is committed, and security forces will be able to catch offenders and prevent the incident before serious damage is done. Likewise, installing cameras in public spaces may violate citizens\' privacy. The database of recordings may contain information that could harm innocent passers-by, from recording an embarrassing act in public, such as picking one\'s nose, to recording credit-card numbers or other personal details."', y=90, size=28)),
  "Yes, 'public spaces' repeats again. But now we're after a different problem.",
  "The first part is positive: fewer crimes. Then 'Likewise', a connector of addition. And the second part is negative: harm to privacy.",
  A("The fix", T('"Likewise" (addition) ✗   →   "However," / "On the other hand," (contrast) ✓', size=36, x=410, y=560, w=1140)),
  D("teacher crosses out 'Likewise' and writes 'However,'"),
  "The link between the parts is wrong. We need contrast: 'However', 'On the other hand'. That's also a break in the line of thought.",
 ]),
 dict(mode='concept', active=11, title='The official row', script=[
  "Here's how the official table describes focus and coherence.",
  A("Low", T('Low: jumps from one idea to the next without continuity · unnecessarily repetitive', size=34, x=410, y=110, w=1140)),
  "At the bottom: jumps from one idea to the next without any continuity, and unnecessary repetition.",
  A("High", T('High: continuity of thought through the entire essay · explicit connections among the ideas', size=34, x=410, y=230, w=1140)),
  "At the top: continuity of thought throughout the whole essay, and explicit connections among the ideas.",
  A("Two checks", T('Check 1: does each sentence add something new?   Check 2: does its connector show the real relationship?', size=34, x=410, y=360, w=1140)),
  "So when you proofread, two checks: does each sentence add something new? And does the connector show the real relationship?",
  "That's focus and coherence. See you in the next lesson, on critical thinking.",
 ]),
], T50),

# ------------------------------------------------------------------ lesson 5: critical thinking (seg19)
lesson('vr50-d-critical', 'Critical Thinking', SB_CRIT, [
 dict(mode='title', title='Critical Thinking', script=[
  "Critical thinking.",
  "The last row of the content rubric, and the one that covers everything.",
 ]),
 dict(mode='concept', active=0, title='Four components', script=[
  "According to the official table, critical thinking means four things.",
  A("1", T('1 · A precise definition of the issue', size=38, x=410, y=110, w=1140)),
  A("2", T('2 · Distinguishing between opinion and fact', size=38, x=410, y=190, w=1140)),
  A("3", T('3 · Examining the issue from several perspectives', size=38, x=410, y=270, w=1140)),
  A("4", T('4 · Dealing with opposing views - the ability to refute them', size=38, x=410, y=350, w=1140)),
  "A precise definition of the issue. Opinion versus fact. Several perspectives. And dealing with opposing views. Let's understand each one.",
 ]),
 dict(mode='concept', active=1, title='Precise issue', script=[
  "A precise definition of the issue. We already talked about it: it's relevance to the task. But let's see examples.",
  A("The rule", T('Answer the issue you were asked about - not the issue next to it', size=40, x=410, y=110, w=1140)),
  "The students in these examples don't miss completely. They don't start writing about horse racing. They land next to the issue.",
  A("The cost", T('Missing the issue ≈ writing an essay on another topic', size=40, x=410, y=230, w=1140)),
  "And next to it is not good enough. If you miss what you were asked, it's as if you wrote an essay on a different topic.",
  A("Official", T('Officially: content not relevant to the task → the essay is disqualified (lowest score); little relevance → the bottom of the content table', size=32, x=410, y=340, w=1140)),
  "Officially, content that doesn't relate to the task gets the lowest score, and 'little relevance' is at the very bottom of the table. This is critical.",
 ]),
 dict(mode='concept', active=2, title='Near miss: custody', script=[
  "Example one.",
  A("The question", T('"In your opinion, should the \'tender years presumption\' be abolished? (Under this rule, when divorced parents cannot agree on custody, the court gives custody of children under six to the mother.)"', size=32, x=410, y=100, w=1140)),
  "Custody means who the child lives with, on which days, and so on. Until age six, the child is with the mother; only then do they start discussing shared custody.",
  A("The answer", T('"In my opinion, it is not appropriate for a legal body to decide the fate of children of divorced parents, since such decisions should be made by child-development psychologists and other professionals."  ✗', size=32, x=410, y=300, w=1140)),
  "What do you say? This misses the issue.",
  A("Why", T('Asked: should this rule be abolished?  Answered: should courts decide at all?', size=36, x=410, y=500, w=1140)),
  "The issue is the tender years presumption. The student started discussing whether a court should decide at all, or psychologists. That's next to the issue, not the issue.",
 ]),
 dict(mode='concept', active=3, title='Near miss: flights', script=[
  "Another example.",
  A("The question", T('"In your opinion, should the number of weekly flights be limited because of the damage to the ozone layer?"', size=34, x=410, y=100, w=1140)),
  A("The answer", T('"In my opinion, all people must share responsibility for protecting the planet and make every effort to recycle and protect the environment."  ✗', size=32, x=410, y=230, w=1140)),
  "The question is about limiting the number of weekly flights. The answer talks about the environment in general and about recycling. Not about flights.",
  A("Second miss", T('Also a miss: limiting flights for a different reason (not the ozone layer)', size=36, x=410, y=420, w=1140)),
  "By the way, another way to miss this task: arguing for limiting flights for some other reason, not the damage to the ozone layer. It seems to answer the question, but it misses the task.",
  A("So", T('Check: the decision · who is affected · the conditions in the question', size=36, x=410, y=540, w=1140)),
  "So always check: what exactly is being decided, who it affects, and which conditions the question sets.",
 ]),
 dict(mode='concept', active=4, title='Opinion vs. fact', script=[
  "Opinion versus fact. This is one of the main problems in students' essays. Many present their opinions as facts.",
  A("The axis", T('FALSE  ←——————————————→  TRUE', size=46, x=410, y=110, w=1140)),
  "Picture an axis from not true to true.",
  A("Fact", T('A fact: true for certain → at the "true" end', size=36, x=410, y=210, w=1140)),
  "A fact is true for certain. It sits at the true end.",
  A("Opinion", T('An opinion: somewhere in the middle - maybe true, maybe not; you would need to check, test, research', size=36, x=410, y=290, w=1140)),
  "And an opinion? I don't know where it sits. Maybe it's true, maybe it isn't. I can't decide. I'd need experiments, research.",
  "If you ask many people, some will say yes, some will say no.",
  D("teacher marks the middle of the axis 'opinion' and the right end 'fact'"),
 ]),
 dict(mode='concept', active=5, title='Why tasks are 50-50', script=[
  "By the way: exam tasks are chosen so that the opinions on each side are around fifty-fifty.",
  A("Near 50%", T('Exam tasks sit near the middle: roughly half would say yes, half no', size=38, x=410, y=110, w=1140)),
  "If almost everyone agreed with one side, or it were a fact, there would be no discussion. The task would be useless.",
  A("What they want", T('They want to see how you build, develop and support arguments', size=38, x=410, y=240, w=1140)),
  "They want to see how we argue, how we build arguments and develop them. A factual question doesn't serve that.",
  A("And so", T('So your position will always be an opinion - what you build it from is what counts', size=36, x=410, y=360, w=1140)),
  "So your position will always be an opinion. What matters is what you build it from.",
 ]),
 dict(mode='concept', active=6, title='Reasonable assumption', script=[
  "Between opinion and fact there's another idea: a reasonable assumption.",
  A("Definition", T('A reasonable assumption: not a checked fact - but what a reasonable person would most likely do', size=36, x=410, y=110, w=1140)),
  "It's not a fact. I didn't go and check it. But I can say: it's reasonable to assume that...",
  A("Example", T('"It is reasonable to assume that criminals who know an area is monitored by cameras will avoid committing crimes there."', size=34, x=410, y=240, w=1140)),
  "For example: it's reasonable to assume that criminals who know an area is monitored will avoid committing crimes there.",
  "Not a fact. Maybe there's a criminal who doesn't care about the cameras. But the reasonable person would probably act this way.",
  A("Strength", T('fact  >  reasonable assumption  >  opinion', size=46, x=410, y=400, w=1140)),
  "A fact has amazing power, because it's true. A reasonable assumption has more power than an opinion.",
 ]),
 dict(mode='concept', active=7, title='An opinion-only chain', script=[
  "When I develop an argument, I rely on steps, links, mini-arguments. The ideal is to build them from facts and reasonable assumptions.",
  A("Weak chain", T('I think A causes B → I think B causes C → I think C causes D → result', size=36, x=410, y=150, w=1140)),
  "If my whole development is: I think this causes that, I think that causes this, I think this causes that, and here's the result...",
  A("Reply", T('The reader: "I think A does not cause B. Or C. Or D."', size=36, x=410, y=270, w=1140)),
  "That is very weak. It's hard to convince anyone. Someone else says: I think it won't. And that won't either. And that won't either.",
  A("The fix", T('Build the steps from facts and reasonable assumptions', size=42, x=410, y=390, w=1140)),
  "But if I use facts and reasonable assumptions more than opinions, I make the argument and its development stronger.",
 ]),
 dict(mode='concept', active=8, title='Facts and assumptions', script=[
  "Say my argument is an opinion: installing cameras in public spaces will reduce crime. How do I explain it with facts and reasonable assumptions?",
  A("Fact", T('FACT: the cameras will be installed with the public\'s knowledge, not secretly', size=34, x=410, y=110, w=1140)),
  "Fact: the cameras will be installed with the public's knowledge. Not secretly.",
  A("Assumption", T('REASONABLE ASSUMPTION: people who know there are cameras are likely to avoid committing crimes there', size=34, x=410, y=200, w=1140)),
  "Reasonable assumption: people who know there are cameras will probably avoid crime in those areas.",
  A("Conclusion", T('CONCLUSION: crime decreases', size=34, x=410, y=320, w=1140)),
  A("Comparison", T('Support by comparison: "similarly to speed cameras on the roads, which deter drivers"', size=34, x=410, y=410, w=1140)),
  "And I can strengthen it with a comparison: similarly to speed cameras on the roads.",
  "Some speed cameras are even on brightly painted poles, so we won't miss them. Why? Because their aim is less to catch drivers and more to deter. Knowing a camera is there, we drive slower.",
  "I don't need to repeat the explanation in other words. That would be repetition and padding. The comparison says it for me.",
 ]),
 dict(mode='concept', active=9, title='Completing the chain', script=[
  "Another reason, the same method.",
  A("1", T('FACT: enforcement agencies will be able to use the footage in their work', size=32, x=410, y=100, w=1140)),
  "Fact: enforcement agencies will be able to use the footage. Obviously; that's why we build the database.",
  A("2", T('REASONABLE ASSUMPTION: it will be easier to identify offenders', size=32, x=410, y=180, w=1140)),
  "Therefore, it's reasonable to assume it'll be easier to identify offenders. Compare that to asking witnesses: 'He wore a hat... maybe an eye patch?'",
  A("Gap", T('CONCLUSION: crime decreases?  - not yet! Catching someone afterwards does not yet explain less crime.', size=32, x=410, y=260, w=1140)),
  "Conclusion: crime goes down? Wait. My argument isn't full yet. I caught him after the fact. Why would that reduce crime?",
  A("3", T('REASONABLE ASSUMPTION: it will be easier to prove their guilt', size=32, x=410, y=380, w=1140)),
  A("4", T('REASONABLE ASSUMPTION: they will go to prison instead of being released', size=32, x=410, y=450, w=1140)),
  A("5", T('CONCLUSION: they cannot go back to crime - crime decreases', size=32, x=410, y=520, w=1140)),
  "So I complete it. It'll be easier to prove their guilt. So they'll go to prison instead of being released. So crime decreases.",
  A("Point", T('The claim is an opinion - but its development is built from facts and reasonable assumptions', size=34, x=410, y=620, w=1140)),
  "My argument was an opinion. But I built its development from facts and reasonable assumptions, and that makes it much stronger. This is the chain, with every arrow tested.",
 ]),
 dict(mode='concept', active=10, title='Several perspectives', script=[
  "Examining the issue from several perspectives.",
  A("Areas", T('Social · educational · economic · health · rights that are affected...', size=38, x=410, y=110, w=1140)),
  "We'll have a whole lesson on looking at an issue from different areas: social, educational, economic, the rights involved.",
  A("Techniques", T('Finding arguments: rights · zoom out · zoom in', size=38, x=410, y=220, w=1140)),
  "And lessons on finding arguments with rights, and with zoom out.",
  A("Why", T('Several perspectives → more impressive critical thinking than one very narrow view', size=36, x=410, y=330, w=1140)),
  "When I examine the issue from several perspectives, it shows more impressive critical thinking than someone who looks very, very narrowly.",
 ]),
 dict(mode='concept', active=11, title='Opposing views', script=[
  "And dealing with opposing views.",
  A("Legitimate", T('No right and wrong: different positions, both legitimate, each with advantages and disadvantages', size=34, x=410, y=100, w=1140)),
  "Remember: there's no such thing as right and wrong here. There are different positions. Both are legitimate.",
  A("Know four things", T('Know: your advantages · your weak points · their advantages · their weak points', size=36, x=410, y=220, w=1140)),
  "Know the advantages of your position, but also its disadvantages, so you can deal with them if they come up.",
  "And know the other side's advantages and disadvantages, so you can weaken their counter-arguments.",
  A("Rebuttal paragraph", T('Later: the rebuttal paragraph - the opposing view + our answer (weakening)', size=36, x=410, y=360, w=1140)),
  "Later we'll learn the recommended essay structure. It has a rebuttal paragraph: we present an opposing argument, weaken it and answer it.",
  "That shows we took the counter-arguments into account and have a way to deal with them.",
  A("Why it matters", T('Without dealing with the other side, a high content score is very hard to reach', size=36, x=410, y=500, w=1140)),
  "This matters a lot to the raters. Without dealing with the opposing view, the score may be medium, but it's very hard for it to be high.",
 ]),
 dict(mode='concept', active=12, title='What comes next', script=[
  "That's it: the content rubric is done.",
  A("Next stage", T('Next: analysing and planning the essay', size=42, x=410, y=110, w=1140)),
  "Next, we move to analysing and planning the essay. Before we run to write, we plan. And before we plan, we analyse.",
  A("The questions", T('Which arguments can I use? Which are strong? How will I explain each one? What are the counter-arguments? Where are the weak points - mine and theirs?', size=34, x=410, y=210, w=1140)),
  "Analyse the task. Which arguments could I use? Which are strong? How will I explain each one? What counter-arguments are there? What are the weak points, on my side and on theirs?",
  "As usual, I'll see you there.",
 ]),
], T50),

# ------------------------------------------------------------------ lesson 6: what strong essays do differently
# Built from writing_src/findings.md; all paragraphs are original (free city buses).
lesson('vr50-d-strong', 'What Strong Essays Do Differently', SB_STRONG, [
 dict(mode='title', title='What Strong Essays Do Differently', script=[
  "What makes a strong essay strong?",
  "We compared many official sample essays marked strong, adequate and weak. In this lesson: what really separates them.",
  "I won't show you those essays. We'll use our own examples, on a new topic.",
 ]),
 dict(mode='concept', active=0, title='Three levels', script=[
  "Here's the big picture.",
  A("Strong", T('STRONG: the reasoning is easy to follow - every step is on the page', size=36, x=410, y=100, w=1140)),
  "In a strong essay, the reasoning is easy to follow. Every step is written down.",
  A("Adequate", T('ADEQUATE: starts with a relevant idea, but leaves part of the explanation for the reader to fill in', size=36, x=410, y=200, w=1140)),
  "An adequate essay usually starts with a relevant idea, but leaves part of the explanation for the reader to supply.",
  A("Weak", T('WEAK: may have a good idea - but loses the exact question, contradicts its own answer, or cannot be followed', size=36, x=410, y=320, w=1140)),
  "A weak essay may also contain a good idea. But it loses the exact question, contradicts its own answer, or explains so unclearly that the reader can't rebuild it.",
  A("No preferred opinion", T('No opinion is preferred. Yes, no or "yes, under conditions" - each can be strong if it is well argued.', size=34, x=410, y=460, w=1140)),
  "And notice: no opinion is the 'right' one. A strong essay isn't strong because of the side it chose.",
  A("Our topic", T('Our practice topic: free local buses', size=40, x=410, y=590, w=1140)),
  "For this lesson, one original topic: should cities make local buses free?",
 ]),
 dict(mode='concept', active=1, title='The exact question', script=[
  A('The task appears', dict(prompt_box(BUS_PROMPT, BUS_QUESTION, w=1140), x=410, y=40)),
  "Here's our task. The first difference between the levels: answering the exact question.",
  A("Three checks", T('Before any reason: the decision · the people affected · the conditions', size=34, x=410, y=380, w=1140)),
  "Before you look for reasons, pin down three things: what is being decided, who is affected, and what conditions the question sets.",
  A("Drift 1", T('"Should students get cheaper bus passes?"  → changes the people', size=32, x=440, y=460, w=1100)),
  A("Drift 2", T('"Should cities build more bike lanes?"  → changes the decision', size=32, x=440, y=530, w=1100)),
  A("Drift 3", T('"Are buses better than cars?"  → changes the question', size=32, x=440, y=600, w=1100)),
  "An essay can sound thoughtful and still answer one of these. Cheaper passes for students changes the people. Bike lanes changes the decision. Buses versus cars changes the question.",
  A("Verdict", T('That is a reasoning problem, not a wording problem', size=36, x=410, y=690, w=1140)),
  "These aren't small wording problems. They're reasoning problems.",
 ]),
 dict(mode='concept', active=2, title='Every part of it', script=[
  "Second: every part of the question needs an answer.",
  A("A two-part question", T('"What are the benefits of school gardens for students and for the school community?"', size=36, x=410, y=110, w=1140)),
  "Say a question asks about benefits for students and for the school community.",
  A("Half an answer", T('A clear, well-explained paragraph on students only = half the task is missing', size=36, x=410, y=240, w=1140)),
  "A clear explanation of the benefits for students alone still leaves half the task unfinished.",
  A("Plan from the question", T('Build your outline from what the question asks - not from a memorized essay shape', size=36, x=410, y=370, w=1140)),
  "So your plan comes from what the question asks, not from a memorized shape.",
  A("Not always yes/no", T('Not every task is a yes-or-no debate - read what it actually asks for', size=34, x=410, y=500, w=1140)),
  "Not every task is a for-or-against debate. Our structure is a tool. It has to serve this question.",
 ]),
 dict(mode='concept', active=3, title='Reasons that support', script=[
  "Third: a clear opinion at the start is not enough. The reasons must actually support it.",
  A("Position", T('Position: "Cities should make local buses free."', size=36, x=410, y=110, w=1140)),
  A("Reason that drifts", T('Reason: "Bus drivers work long shifts and deserve better pay."  ✗', size=36, x=410, y=200, w=1140)),
  "Does that support free buses? Maybe it's true. But it points somewhere else: to drivers' pay, not to the fare.",
  A("Reason against", T('Reason: "Fares teach passengers to value the service."  ✗ - this supports keeping fares!', size=34, x=410, y=300, w=1140)),
  "Even worse: a reason that actually supports the other side.",
  A("Test", T('Test: read the key sentence, then the position. Does "because..." really lead to it?', size=36, x=410, y=420, w=1140)),
  "The test: read each key sentence, then your position. Does 'because' really lead there?",
  A("Closing can't fix it", T('A closing paragraph cannot fix reasons that point the other way', size=36, x=410, y=540, w=1140)),
  "And a closing paragraph can't rescue it. If the reasons point to keeping fares, you can't just end by saying 'make them free'.",
 ]),
 dict(mode='concept', active=4, title='Add a step', script=[
  "Fourth: development means adding something, not saying the same thing differently.",
  A("Repeat", T('"The service improves. Passengers enjoy a better service. The travel experience becomes better."', size=34, x=410, y=110, w=1140)),
  "Three sentences, one idea. Several versions of 'the service is better' don't deepen the argument.",
  A("A new sentence must...", T('Every new sentence must do a job:', size=38, x=410, y=260, w=1140)),
  A("Jobs", T('explain a cause · show a consequence · make a distinction · illustrate · state a meaningful limit', size=34, x=440, y=340, w=1100)),
  "Every new sentence needs a job: explain a cause, show a consequence, make a distinction, illustrate something, or state a real limit.",
  A("Otherwise", T('If it does none of these jobs - it is probably repetition', size=38, x=410, y=470, w=1140)),
  "If it does none of these, it's probably repetition. And a second paragraph must add a different reason too, not the same one with new people or new words.",
 ]),
 dict(mode='concept', active=5, title='The missing link', script=[
  "Fifth, and the most useful thing to repair: the missing link.",
  A("Outcome only", T('"Free buses will reduce traffic."  - names an outcome, does not explain it', size=36, x=410, y=110, w=1140)),
  "This names an outcome. It doesn't explain how the policy produces it.",
  A("The chain", T('no fare → the bus is cheaper than driving for short trips → some drivers switch → fewer cars at peak hours → less traffic', size=34, x=410, y=230, w=1140)),
  "Here is the chain. Each arrow is a step the reader needs.",
  A("Test the arrows", T('Test every arrow: why would this step lead to the next?', size=38, x=410, y=380, w=1140)),
  "Now test every arrow. Cheaper, so drivers switch? Only if the bus is a real alternative: frequent enough and going where they go.",
  A("A condition", T('Weak arrow → add an explanation or a condition: "...provided the service is frequent"', size=34, x=410, y=480, w=1140)),
  "A weak arrow needs an explanation or a condition. And don't add arrows that just rename the same thing: 'fewer cars' and 'less traffic' are almost the same step.",
 ]),
 dict(mode='concept', active=6, title='Weak version', script=[
  "Let's write the same reason three times: weak, adequate, strong. First, weak.",
  A("Weak", para('"In my opinion I think free buses are a great idea because everybody loves free things and everyone will use them. Free buses are the best solution because people will use them more. Everyone knows that pollution is terrible, so the city must do it now!"', y=100, size=30)),
  A("Problems", T('"In my opinion I think" · "everybody", "everyone" · the same point twice · no route from the fare to the result · emotion instead of explanation', size=32, x=410, y=420, w=1140)),
  "'In my opinion I think': a classic doubled phrase. 'Everybody', 'everyone': claims far bigger than the support.",
  "The same point twice. No route from removing the fare to any result. And emotion, an exclamation mark, pressure on the reader, instead of an explanation.",
 ]),
 dict(mode='concept', active=7, title='Adequate version', script=[
  "Now adequate.",
  A("Adequate", para('"Free buses would reduce traffic in the city centre. When the bus is free, more people will choose it. As a result, there will be fewer cars on the roads. This means that traffic will be reduced and the city will be less crowded, and the roads will also be less busy."', y=100, size=30)),
  A("Better", T('Relevant ✓ · clear position ✓ · a connector for each step ✓', size=34, x=410, y=420, w=1140)),
  "It's relevant, clear, and it uses connectors. Much better.",
  A("But", T('But: "free → more people choose it" is assumed, not explained · the last sentence says the same thing three times', size=32, x=410, y=500, w=1140)),
  "But the key link, why a free bus makes drivers switch, is assumed, not explained. And the last sentence says 'less traffic' three times.",
  "That's the typical adequate paragraph: a good idea, but the reader has to fill in part of the explanation.",
 ]),
 dict(mode='concept', active=8, title='Strong version', script=[
  "And now strong.",
  A("Strong", para('"Making local buses free is likely to reduce traffic in the city centre, provided that the service is frequent enough to be a real alternative. For many short trips, the fare is one of the few costs that a driver compares directly with the price of parking; once it disappears, the bus becomes the cheaper option. Some drivers, especially those whose daily route is already well served, would therefore leave the car at home, and each of them removes a car from the busiest roads at the busiest hours. Fewer cars at peak times, in turn, mean shorter delays for those who still need to drive, including delivery vans and emergency vehicles."', y=90, size=29)),
  "Look what changed. Each sentence adds a step: why the fare matters, who would switch, where and when it helps, and who else benefits.",
  A("What makes it strong", T('the missing link is written · a condition on the weak arrow · a careful claim ("likely", "some drivers") · effects beyond the obvious people', size=31, x=410, y=520, w=1140)),
  "The missing link is on the page. The weak arrow has its condition. The claim is careful: 'likely', 'some drivers'. And it follows the effect beyond the bus passenger, to delivery vans and emergency vehicles.",
  "No invented numbers. No big words. Just the steps.",
 ]),
 dict(mode='concept', active=9, title='The other side fairly', script=[
  "Now the other side. Mentioning it is not the same as answering it.",
  A("Dismissive", T('"Some people say free buses are too expensive, but they only care about money, and people\'s health is more important."  ✗', size=33, x=410, y=100, w=1140)),
  "This makes the other side sound selfish, then walks away. Easy to write, but it shows very little critical thinking.",
  A("Fair", T('"Opponents rightly point out that fares pay for part of the service, so free travel means the city must find that money elsewhere, possibly by cutting other services."  ✓', size=33, x=410, y=280, w=1140)),
  "This states the other side's actual reason, not just its conclusion, and states it fairly.",
  A("Why fair", T('Name their reason, not only their conclusion - and admit what is reasonable in it', size=36, x=410, y=470, w=1140)),
  "You can disagree firmly and still admit that the other side has a reasonable concern.",
 ]),
 dict(mode='concept', active=10, title='Answer its worry', script=[
  "And the reply has to target that concern.",
  A("The question", T('Ask: what exactly does the other side worry will happen?  → answer THAT', size=36, x=410, y=100, w=1140)),
  "Ask yourself: what exactly is the other side worried will happen? Here: lost income, and cuts to other services.",
  A("Reply", para('"This concern is serious. However, part of the lost income may be offset by costs the city already bears: fewer cars mean less wear on the roads, and fares no longer need to be collected or checked. Where a gap remains, the city can introduce free travel gradually, starting with the most crowded routes, so that the real cost is measured before the policy is extended."', y=220, size=30)),
  "Notice: the reply deals with money. It doesn't change the subject to health. It even explains how the safeguard works: start small, measure, then extend.",
  A("Not this", T('"Clean air matters more" / "health is more important" = repeating your side, not answering theirs', size=32, x=410, y=590, w=1140)),
  "Just repeating that your side matters more is not an answer.",
 ]),
 dict(mode='concept', active=11, title='Claims and facts', script=[
  "The strength of your wording must match your support.",
  A("Too strong", T('"Free buses will end traffic jams completely."  ✗', size=34, x=410, y=100, w=1140)),
  A("Matched", T('"Free buses are likely to reduce traffic on well-served routes."  ✓', size=34, x=410, y=170, w=1140)),
  "One plausible consequence doesn't prove what will always happen. 'Many', 'most', 'everyone' are claims too, and they need support. But 'may' can't rescue an explanation that makes no sense.",
  A("Invented", T('"A 2019 study found that free buses cut traffic by 43%."  ✗ - invented', size=34, x=410, y=280, w=1140)),
  "Never make up studies, statistics or experts to sound convincing. The official guide warns explicitly against incorrect or fabricated information.",
  A("Instead", T('Use accurate knowledge you really have - or careful reasoning: "It is reasonable to expect that..."', size=34, x=410, y=370, w=1140)),
  "Use knowledge you really have, or explain a plausible consequence carefully. That is enough for a strong argument.",
  A("Reported ≠ proved", T('"Supporters say it will reduce traffic" (in the task) is a claim to examine, not a proven fact', size=34, x=410, y=490, w=1140)),
  "And keep facts, assumptions and reported opinions apart. When the task says supporters believe something, that's their prediction, not proof.",
 ]),
 dict(mode='concept', active=12, title='Examples and length', script=[
  "Last two points. Examples, and length.",
  A("Story", T('"Last summer I took a free bus in my city and it was amazing..."  ✗ personal story', size=32, x=410, y=100, w=1140)),
  "A personal story is easy to picture, but it doesn't explain anything, and the guide advises against a personal, narrative style.",
  A("Explaining example", T('"For example, a worker who drives a short distance to the centre pays for fuel and parking; if the bus is free and frequent, it becomes both cheaper and nearly as fast - a clear reason to switch."  ✓', size=32, x=410, y=190, w=1140)),
  "A short, general illustration that shows the mechanism is useful. It explains the reason instead of replacing it.",
  A("Limit", T('One example shows HOW something can happen - not how OFTEN it happens', size=34, x=410, y=390, w=1140)),
  "But one example shows how it could happen, not that it happens to most people.",
  A("Length", T('25-50 lines · good essays are usually 30-40 · more lines ≠ more explanation', size=36, x=410, y=500, w=1140)),
  "And length: at least twenty-five lines, at most fifty; good essays are usually thirty to forty. But length alone is not quality.",
  "Long weak essays often just drift further. More lines should mean more steps, not more words.",
 ]),
], T50),
]

MEMORY = [dict(
  id='mem-wr-content-rubric', after='vr50-d-strong', title='Content rubric - what raters look for',
  intro='Two raters, content 1-6 each (rated separately from language). A timed first draft - clarity of reasoning is what counts.',
  tables=[
   dict(title='The four content criteria', head=['Criterion', 'What raters look for', 'Typical loss'], rows=[
    ['Relevance + main idea', 'Answers the exact question, every part of it; a clear position; all reasons support it',
     'A near miss (same topic, different question); reasons that point elsewhere'],
    ['Development', 'Varied arguments from different angles; full, logical explanations - every step from claim to result',
     'Two reasons from the same angle; a missing link ("will reduce crime" with no route)'],
    ['Focus and coherence', 'Each sentence adds something; a continuous line of thought; connectors that show the real relationship',
     'The same idea in other words; padding; jumps; "Likewise" where contrast is needed'],
    ['Critical thinking', 'Precise issue; opinion vs fact (steps built from facts and reasonable assumptions); several perspectives; dealing with opposing views',
     'Opinions stated as facts; one narrow angle; no answer to the other side'],
   ]),
   dict(title='Strong vs adequate vs weak', head=['Feature', 'Strong', 'Adequate', 'Weak'], rows=[
    ['The question', 'Stays with the exact decision and people', 'Relevant, some drifting', 'Changes the decision, people or setting'],
    ['Reasons', 'Each one supports the position', 'Some thin or loosely aligned', 'Reasons and position point different ways'],
    ['Development', 'Adds a step each sentence; the missing link is written', 'Names results, assumes the link, repeats', 'Lists claims or tells stories'],
    ['Other side', 'States its real reason fairly and answers that worry', 'Mentions it, answers partly', 'Dismisses or ignores it'],
    ['Claims', 'Wording matches support; no invented facts', 'Some overstatement', '"Everyone", "always", made-up numbers'],
   ]),
  ],
  tips=['Test: does each new sentence explain a cause, a consequence, a distinction, an illustration or a limit?',
        'Examples explain a reason - they do not replace it, and one example does not show how common something is.',
        'Length is not quality: 25-50 lines, good essays usually 30-40; more lines must mean more steps.'])]
