# Verbal Reasoning · Topic 50 · Writing Task · Part H
# Sources: writing_src/seg43-seg51 (the teacher's Hebrew lessons: opening paragraph + its two templates, closing
# paragraph + its three templates, the recommended structure, the essay skeleton with the worked example,
# proofreading and corrections, reviewing an essay) · nite_verbal_guide.txt (official facts: 35 minutes, 25-50 lines,
# two raters, first draft) · writing_src/findings.md 21-24 (short introduction, conclusion follows the body, the
# structure is a teaching aid, paragraph jobs matter more than counts) and 25, 34.
# The camera task is the teacher's own running example (translated). The full essay and the practice tasks are ORIGINAL.
from dsl import *
from writing_assets import prompt_box, vis, answer_sheet_svg

T50 = 50


def L(label, text, y, size=32, x=410, w=1140):
    """A pop-in line of text."""
    return A(label, T(text, size=size, x=x, y=y, w=w))


# ---------------------------------------------------------------- the teacher's running example (translated)
CAM_PROMPT = [
    'In recent years, security authorities have been promoting a plan to set up a',
    'national network of face-recognition cameras in public spaces. The cameras',
    'can identify people, vehicles and objects in real time with high accuracy,',
    'provided that their images already appear in a database. Supporters say the',
    'system will help prevent crimes and security incidents, stop them while they',
    'happen, or catch offenders afterwards, and so reduce crime or even eliminate',
    'it. Opponents fear serious harm to privacy and constant tracking of citizens.',
]
CAM_Q = 'In your opinion, should face-recognition cameras be installed in public spaces? Give reasons.'
# one shared version of every task (writing_tasks.py, shaped like the real English tasks)
from writing_tasks import T as _T, split_task_slides, PRACTICE
CAM_PROMPT, CAM_Q = _T['camera']['paras'], _T['camera']['q']


# ================================================================= lesson 1: the opening paragraph (seg43)
SB_OPEN = ['Two jobs', 'The rater\'s first look', 'Same content for all', 'Three parts',
           'Position at the end', 'Take it from the task', 'Copying segments', 'No empty phrases',
           'Don\'t try to impress', 'The horse drawing']

OPEN = lesson('vr50-h-opening', 'The Opening Paragraph', SB_OPEN, [
 dict(mode='title', title='The Opening Paragraph', script=[
  "We've learned how to write the heart of the essay: argument paragraphs and the rebuttal paragraph.",
  "Now we wrap it. First, the paragraph that opens the essay: the opening paragraph.",
 ]),
 dict(mode='concept', active=0, title='Two jobs', script=[
  "What is the opening paragraph for? It has two jobs. One for the essay, and one for the rater.",
  L("For the essay: background", 'For the essay: it gives the background to the discussion', 110, 40),
  "For the essay, it sets the scene. We're about to discuss an issue, so the opening gives the background to the dispute,",
  L("... and the dispute itself", 'It presents the dispute, and then the discussion can begin', 210, 40),
  "presents the dispute itself, and then, off we go, the discussion begins.",
  L("For the rater: the first impression", 'For the rater: it creates the first impression', 330, 40),
  "For the rater, it has another job. This is where you make your first impression.",
  "The rater picks up your essay, starts reading, and this is the first time they meet your writing.",
 ]),
 dict(mode='concept', active=1, title='The rater\'s first look', script=[
  "Let me take you into a rater's head for a moment.",
  L("Reading = tuning in to a score", 'While reading, a rater gradually tunes in to a content score and a language score', 110, 36),
  "As they read, paragraph by paragraph, they tune in more and more to the scores they want to give: content and language.",
  L("Officially: score only at the end", 'Officially, the score is given at the end, using the rubric', 230, 36),
  "Officially, a rater should score only at the end, after reading everything and going through the rubric.",
  L("In practice: a tentative score early", 'In practice, an experienced rater has a tentative score in mind early on', 330, 36),
  "But after hundreds and thousands of essays, it happens automatically. There's already a score in their head.",
  L("Opening -> 'Language: 5'", 'After the opening:  "Language: about 5. Let\'s move on."', 450, 36),
  "They finish your opening and think: okay, language five, let's continue.",
  L("Each paragraph: still 5? up? down?", 'Each next paragraph:  still 5?  up to 6?  down to 4?', 540, 36),
  "And with every paragraph after that, they ask: am I still at five? Wow, this impressed me, it's six now. Or: hmm, this dropped to four.",
 ]),
 dict(mode='concept', active=2, title='Same content for all', script=[
  "So what can the rater learn from your opening? Language: clearly. They see the language you use and fix a starting level.",
  L("Language: yes, a starting level", 'Language: yes. The rater fixes a starting level', 110, 38),
  "And content? That's hard to judge from an opening paragraph. Why?",
  L("Content: hardly", 'Content: hardly. Almost everyone\'s opening looks the same', 200, 38),
  "Because almost everyone's opening is very similar. Background, the dispute. Everyone writes more or less the same thing,",
  "often in nearly the same sentences, because they all take it from the task text.",
  L("The differences are in the body", 'The differences appear in the body: different arguments, examples, comparisons, weakenings', 300, 34),
  "Where do essays differ? In the body. Different arguments, different explanations, different examples, comparisons and weakenings.",
  L("So: its job for the rater = your language level", 'So, for the rater, the opening sets your starting language level.\nGive its language a little extra care.', 430, 36),
  "So for the rater, the opening fixes your starting language level. If you can give its language a little extra attention, do it.",
 ]),
 dict(mode='concept', active=3, title='Three parts', script=[
  "What goes into the opening paragraph? Three parts.",
  L("1 · Background", '1 · Background: what led to the dispute, where it started', 110, 36),
  "One: background. What came before the dispute, why there is a dispute now, where it started.",
  L("2 · The dispute", '2 · The dispute: the question under discussion', 190, 36),
  "Two: the dispute. We describe the question under discussion.",
  L("Optional: the sides", 'Optional: the two sides, with or without a main argument each', 270, 36),
  "Sometimes we also add the sides' positions, with or without a main argument. You don't have to. Some add one side, some both, some neither.",
  L("Argument = key sentence only", 'If you add an argument: the claim only, no explanation.\nThe explanation belongs in the argument paragraphs.', 350, 34),
  "If you do add an argument, give only the claim itself, just the key sentence. Don't start explaining or developing it here. That comes later, in the argument paragraphs.",
  L("3 · Your position", '3 · Your position, at the end of the paragraph', 490, 36),
  "And three: at the end of the paragraph, we write our own position.",
 ]),
 dict(mode='concept', active=4, title='Position at the end', script=[
  "A small reservation about the position.",
  L("You may place it anywhere", 'Technically, the position may appear anywhere: start of the next paragraph, middle, even the closing', 110, 34),
  "You don't have to write it at the end of the opening. You could write it at the start of the next paragraph, somewhere in the middle, even in the closing.",
  L("Recommended: end of the opening", 'Our recommendation: the last sentence of the opening', 230, 40),
  "But our recommendation is: write it at the end of the opening paragraph.",
  L("Otherwise: the thread jumps", 'Otherwise the main thread tends to jump, cohesion suffers,\nand the rater wonders: "Wait, is the writer for or against?"', 320, 34),
  "Many students who don't do this end up with an essay whose main thread jumps from one side to the other. Cohesion gets lost, and the rater thinks: wait, are you for or against?",
  L("No suspense needed", 'You lose nothing. No suspense, no surprise ending.\nState your position as clearly as possible.', 460, 34),
  "You lose nothing by saying it early. You don't need to keep the rater in suspense, and you don't need to surprise anyone in the closing.",
  "Tell them your position as clearly as possible, and carry on from there.",
 ]),
 dict(mode='concept', active=5, title='Take it from the task', script=[
  "Remember: the opening's content is the same for everyone. It's a template. Don't be creative. Write what's needed and move on.",
  L("Everything is in the task text", 'Everything you need is in the task text:\nbackground, sides, dispute, even arguments', 110, 38),
  "Everything you need for it is already in the task text. The background, the sides, the dispute, even arguments if you want to add them.",
  L("The task text = an almost perfect opening", 'The task text is almost a perfect opening paragraph', 240, 38),
  "Think about it: the task text is almost a perfect opening. It gives the background, it describes the dispute.",
  L("It ends with a question, you end with an answer", 'It ends with the question "In your opinion ...?"\nYour opening ends with the answer: your position', 330, 36),
  "The only difference: instead of a personal position at the end, it asks you: what is your opinion? And that's exactly where your opening ends, with your position.",
  L("Rewrite the relevant parts", 'Recommended: rewrite the relevant parts in your own words', 470, 36),
  "So the recommendation is to rewrite the relevant parts in your own words.",
 ]),
 dict(mode='concept', active=6, title='Copying segments', script=[
  "But you can also copy parts. Is there a phrase or a sentence that's worded really well? Take it.",
  L("Copying segments is fine", 'Copying segments of the task text is fine', 110, 38),
  "Copying segments of the task text is fine. A well-worded phrase, a key term, one sentence.",
  L("Not the whole thing word for word", 'But not the whole task word for word: select, shorten and connect it in your own words', 210, 34),
  "But don't copy the whole task word for word. Choose the parts you need, shorten them, and connect them with your own words.",
  "The opening should show that you understood the issue. A copied block of text doesn't show that.",
  L("For you: don't get stuck", 'What it means for you: can rewrite well? Great.\nStruggling? Copy the key segments, link them, and get to the body.', 360, 36),
  "What does this mean for you? Don't get stuck. You can rewrite it? Excellent. You can't? Take the key segments, link them in a sentence or two of your own, and move on to the essay.",
  L("Complex position: here, if you can", 'Option: a complex position here (instead of a bridging recommendation later),\nif you can keep its boundary coherent', 600, 30),
  "And as we said in the bridging recommendation lesson: a complex position can go here, instead of a bridging recommendation in the rebuttal paragraph. It's a good option if you can keep its boundary coherent.",
 ]),
 dict(mode='concept', active=7, title='No empty phrases', script=[
  "Avoid sentences that don't move you forward.",
  L("Empty phrase 1", '"This is a problematic issue."', 120, 40),
  L("Empty phrase 2", '"This is indeed a complex dilemma."', 200, 40),
  L("Empty phrase 3", '"This question has always divided society."', 280, 40),
  "Okay. How does that help? It doesn't. It adds nothing to the content and it hurts the focus.",
  D("Cross out all three phrases"),
  L("Every sentence must add something", 'Every sentence in the opening should add information:\nthe background, the dispute, or your position', 400, 36),
  "Every sentence should add something: background, the dispute, or your position. Nothing else.",
 ]),
 dict(mode='concept', active=8, title='Don\'t try to impress', script=[
  "And don't try to impress or be creative in the opening.",
  L("Creativity: save it for the body", 'Want to impress? Do it in the body of the essay', 110, 40),
  "Why? Because the content is the same for everyone. How much creativity can you show in an opening? So let it go.",
  L("Rewrite the task simply, then run", 'The opening: rewrite the task text in the simplest, most standard way, then move on', 210, 36),
  "Rewrite the task text in the simplest, most standard way you can, and run forward. Want to impress? Impress in the body.",
  L("One exception: a small language lift", 'One small exception: if you can lift the language a little, the opening is a good place,\nbecause it is the first impression', 340, 32),
  "One small reservation: if there's something in your language you can lift a little, the opening is a good place for it. It's the first impression.",
  L("Example of a lift", 'Plain: "Many people are against it."\nLifted: "This proposal has met with considerable opposition."', 480, 32),
  "For example, instead of 'many people are against it': 'this proposal has met with considerable opposition'. Precise, formal, not flowery.",
 ]),
 dict(mode='concept', active=9, title='The horse drawing', script=[
  "Do you know that famous drawing of a horse? Try to guess from which side the artist started.",
  L("The tail: a perfect drawing", 'The back: every hair of the tail drawn in detail', 110, 38),
  "The artist started from the back. A perfect tail, almost like a photograph. Lots and lots of time invested.",
  L("... then the deadline", 'Then the deadline approaches: less detail, less colour ...', 200, 38),
  "And slowly: wait, the time, the deadline. Let's colour a little less. Let's hurry.",
  L("The front leg: one thin line", 'The front leg: one thin line', 290, 38),
  "And what always kills me: the front leg, which is just one thin line. Let it go and run.",
  L("You have 35 minutes", 'You have 35 minutes for the whole essay', 400, 40),
  "That is what happens when the deadline gets close. You have thirty-five minutes for the whole essay.",
  L("Don't draw a perfect tail", 'Don\'t write a perfect, polished opening ... and then lose the rest of the essay', 490, 36),
  "You don't want a perfect, polished opening, maybe even creative, and then the rest of the essay falls apart.",
  L("Most important: don't waste time", 'The most important rule for the opening: don\'t waste time', 600, 38),
  "So maybe the most important thing about the opening: don't waste time on it. Take the background, describe the dispute briefly, state your position, and run to the essay. Impress there.",
  "In the next lesson: two templates that make it quick.",
 ]),
], T50)


# ================================================================= lesson 2: the two opening templates (seg44)
SB_OTPL = ['Two templates', 'Minimal template', 'Minimal: options', 'Minimal example', 'Rewrite template',
           'Rewrite: options', 'Rewrite example', 'Why rewrite', 'The downside']

OPEN_TPL = lesson('vr50-h-opening-tpl', 'Opening Paragraph Templates', SB_OTPL, [
 dict(mode='title', title='Opening Paragraph Templates', script=[
  "There are two recommended templates for the opening paragraph. Each has its advantages. Let's go through them.",
 ]),
 dict(mode='concept', active=0, title='Two templates', script=[
  L("Template 1: minimal", 'Template 1 · The minimal opening', 110, 44),
  "The first: the minimal template.",
  L("Minimal = background + 'some oppose' + position", 'Rewrite the background briefly + "However, some oppose ..." + your position', 190, 34),
  "Rewrite the background, describe the dispute very briefly, add a sentence that there are opponents, and your position. That's it.",
  L("Template 2: rewrite", 'Template 2 · The rewritten task', 320, 44),
  "The second: rewriting the whole task text.",
  L("Rewrite = everything, shortened + position", 'Rewrite every sentence of the task text, a little shorter + your position', 400, 34),
  "Background, positions, arguments, everything that's there, shortened a little, and your position at the end.",
 ]),
 dict(mode='concept', active=1, title='Minimal template', script=[
  "The minimal template. Here it is with the slots you fill in.",
  L("Slot 1: background", '[Recently / In recent years], [who] [has proposed / has begun / is planning] [what].', 110, 32),
  "First slot: what is happening. Who is doing or proposing what.",
  L("Slot 2: its purpose", '[It / This step] is intended to [purpose], and thus [expected result].', 210, 32),
  "Second slot: what it's for. Notice: while rewriting the background, I'm actually presenting side A, because the purpose of the plan is side A's argument.",
  L("Slot 3: the other side + you", 'However, some oppose this [move / proposal], and I [agree with them / do not].', 310, 32),
  "And then just one sentence: however, some oppose this move. And my position.",
  L("No arguments, no details", 'No arguments for each side, no details, no explanations', 430, 36),
  "I don't go into arguments. I don't say supporters say this and opponents say that. Minimal.",
 ]),
 dict(mode='concept', active=2, title='Minimal: options', script=[
  "Several ways to phrase that last sentence. Pick one and make it yours.",
  L("Option A", 'However, some people oppose this move, and I agree with them.', 110, 32),
  L("Option B", 'Nevertheless, the proposal has its critics, and I share their concerns.', 180, 32),
  L("Option C", 'However, some oppose this step. In my view, it should [nevertheless] be [adopted].', 250, 32),
  L("Option D", 'Not everyone supports this plan; I believe that it should [not] be [carried out].', 320, 32),
  "Four options. Opposing or supporting, you can always fit your position into the last clause.",
  "And careful with the English: it's 'I agree', never 'I am agree'.",
 ]),
 dict(mode='concept', active=3, title='Minimal example', script=[
  "Let's see an example with our running task: face-recognition cameras in public spaces.",
  A("The minimal opening appears", T('Recently, security authorities have begun setting up a national network of face-recognition cameras to be placed in public spaces. These cameras, which can identify people and objects in real time with high accuracy, are meant to help the security forces catch offenders during or after illegal activity, and thus to reduce, or even eliminate, crime in the country. However, some people oppose this move, and I agree with them.', size=30, x=410, y=110, w=1140)),
  D("Bracket the first two sentences: background (and side A)"),
  "The first part is simply the background, rewritten. And while rewriting it, I'm presenting side A: it's meant to help catch offenders.",
  D("Underline: However, some people oppose this move, and I agree with them."),
  "Then I add one sentence: however, some people oppose this move. And my position: I agree with them.",
  L("Short, quick, complete", 'Short, fast, no heavy thinking, and it can be part of a top-scoring essay', 560, 34),
  "Minimal, short, a fine paragraph. If the rest of your essay is excellent, the whole essay is excellent. This paragraph is perfect for the job.",
  "Its advantage: it's short and quick. I don't have to think too much. Rewrite the background, 'however, some oppose', position, go.",
 ]),
 dict(mode='concept', active=4, title='Rewrite template', script=[
  "The second template: rewriting the task text.",
  "I said the task text is a kind of perfect opening, maybe a bit long, but perfect. So let's rewrite it.",
  L("Slot 1: background", '[Background: every sentence of the task text, shortened a little]', 110, 32),
  L("Slot 2: side A", '[Supporters of X / Those in favour] argue that [their main claim].', 190, 32),
  L("Slot 3: side B", '[Opponents / Critics], on the other hand, [fear / argue] that [their main claim].', 270, 32),
  L("Slot 4: your position", 'I agree with the [former / latter], [although I recognize the need for (safeguard)].', 350, 32),
  "Everything in the task text goes in. Some task texts give arguments for one side only; then I rewrite one side. If they give both, both.",
  L("No thinking: run on automatic", 'No decisions about what to keep: everything goes in', 470, 36),
  "The advantage: I don't need to decide what's background and what's an argument. No risk. I run on automatic: every sentence there, I rewrite and shorten a bit.",
 ]),
 dict(mode='concept', active=5, title='Rewrite: options', script=[
  "Some phrase options for each slot.",
  L("Side A options", 'Side A:  Supporters argue that ... · Those in favour claim that ... · Proponents believe that ...', 110, 30),
  L("Side B options", 'Side B:  Opponents, however, fear that ... · Critics warn that ... · Others object that ...', 200, 30),
  L("Position options", 'Position:  I agree with the former. · I side with the critics. · In my view, the plan should [not] be adopted.', 290, 30),
  L("Complex position options", 'Complex:  ..., provided that [condition]. · ..., although [safeguard] would be needed to [limit the risk].', 380, 30),
  "'The former' means the first group you mentioned, 'the latter' the second. Precise and short.",
  "And for a complex position: I take this side, provided that, or although we'd need some safeguard.",
 ]),
 dict(mode='concept', active=6, title='Rewrite example', script=[
  "Let's see the rewrite version for the cameras.",
  A("The rewritten opening appears", T('In recent years, security authorities have been working to set up a national network of face-recognition cameras in public spaces. These cameras can identify people and objects in real time with high accuracy, as long as their images are stored in a database. The information will make it possible to fight criminal and security offences by identifying and foiling suspicious activity before or during an offence, or by catching offenders afterwards. Supporters of the plan argue that the system will reduce, and even eliminate, crime and security incidents in the monitored areas. Opponents, however, fear serious harm to privacy and the constant tracking of every step we take. I agree with the former, although I recognize the need for safeguards that would reduce the risk to privacy.', size=28, x=410, y=110, w=1140)),
  "Notice: 'as long as their images are stored in a database' wasn't in the minimal version. Nor 'before or during an offence, or afterwards'.",
  "Here I don't decide what's important. Everything in the task text goes in, reworded a little.",
  D("Underline: I agree with the former, although I recognize the need for safeguards"),
  "Who are 'the former'? The supporters. And look: I'm already showing a complex position. I choose this side, but I understand I need some reservations, to protect the other side's concern too.",
 ]),
 dict(mode='concept', active=7, title='Why rewrite', script=[
  "So one advantage of the rewrite template: no thinking. The task text goes in, whole.",
  L("Advantage 1: no decisions", 'Advantage 1 · No decisions: rewrite everything', 110, 38),
  L("Advantage 2: a richer essay", 'Advantage 2 · A longer, richer essay, with relevant content only', 190, 38),
  "Another advantage: it enriches the essay. The paragraph comes out much longer than the minimal one, and not through padding or repetition. All of it is relevant.",
  L("Who it helps", 'Helps if you struggle to reach 25 lines, or if you dropped a paragraph', 290, 34),
  "Who does it help? Students whose essays are too short, who barely reach twenty-five lines. And, as we'll see, anyone who drops an argument paragraph.",
  L("The rater's impression", 'A thin essay makes a rater wonder: "Could all the arguments really be developed in so few lines?"', 390, 32),
  "There's also a small psychological effect. Raters know a well-developed essay tends to be longer. A very short one makes them wonder whether the arguments were really developed.",
  L("But length is not the goal", 'But length alone never raises a score: good essays are usually about 30-40 lines', 510, 32),
  "Just remember: extra length only helps when it's relevant content. More writing that drifts is not better. Good essays are usually about thirty to forty lines.",
 ]),
 dict(mode='concept', active=8, title='The downside', script=[
  "And the downside.",
  L("Not everyone rewrites well", 'Not every student rewrites easily', 110, 40),
  "Not every student can rewrite well. Some try, get stuck, and spend ages on it.",
  L("Stuck? Use the minimal", 'Find rewriting hard? Use the minimal template', 200, 40),
  "If rewriting is hard for you, leave it. Work with the minimal template.",
  L("Otherwise: the horse's tail", 'Otherwise you will be drawing the horse\'s tail for a very long time', 290, 36),
  "Otherwise you'll be stuck on the horse's tail for a very, very long time, and you won't finish the rest of the essay.",
  "That's it for the opening. Now we go to the other end, the one that closes the essay: the closing paragraph.",
 ]),
], T50)


# ================================================================= lesson 3: the closing paragraph (seg45)
SB_CLOSE = ['Its job', 'The score is set', 'The sandwich', 'Built from the body', 'No new arguments',
            'No counterargument']

CLOSE = lesson('vr50-h-closing', 'The Closing Paragraph', SB_CLOSE, [
 dict(mode='title', title='The Closing Paragraph', script=[
  "Now the other end of the essay: the closing paragraph.",
 ]),
 dict(mode='concept', active=0, title='Its job', script=[
  L("For the essay: sum it up", 'For the essay: to sum it up', 110, 44),
  "What is the closing paragraph for? For the essay, we want to sum it up.",
  L("For the rater: no mistakes", 'For the rater: to sum it up, and to make no mistakes', 200, 44),
  "For the rater too, it sums up. But we also want to avoid mistakes. What do I mean by that?",
 ]),
 dict(mode='concept', active=1, title='The score is set', script=[
  L("By now the rater has a score", 'By the closing paragraph, the rater already has your scores in mind', 110, 38),
  "By the time the rater reaches your closing, they already have your score in mind, for content and for language.",
  L("Content is measured in the body", 'Content and critical thinking are measured in the body:\narguments, weakenings, dealing with the other side', 220, 34),
  "Your content score, your critical thinking, are measured in the body: the arguments, the weakenings, the opposing arguments and how you deal with them.",
  L("Language: maybe a small bite", 'Language: they have read the whole essay. At most, one good phrase may add a little', 360, 34),
  "And language? They've read a whole essay, they know where you stand. At most you can give it a small bite: a phrase or a word or two that suits most closings.",
  L("So: just don't make mistakes", 'Your only goal here: don\'t make mistakes', 480, 42),
  "So all you need to do here: no mistakes, no embarrassing slips.",
 ]),
 dict(mode='concept', active=2, title='The sandwich', script=[
  "It's no accident we teach the opening and the closing last, after arguments, weakenings and the rebuttal.",
  L("Top slice: the opening", 'Top slice of bread: the opening paragraph', 110, 38),
  L("The filling: the body", 'The filling: the body (arguments, rebuttal) - this is what earns the score', 190, 36),
  L("Bottom slice: the closing", 'Bottom slice of bread: the closing paragraph', 280, 38),
  "They are the bread of the sandwich. Inside is everything we actually want to make, but we need a slice on top and a slice below to hold it, or the sandwich falls apart.",
  "The opening on top, the closing below. The filling is what gives the taste, and the score.",
 ]),
 dict(mode='concept', active=3, title='Built from the body', script=[
  "What do we do in the closing? We summarize the essay: things we've already written.",
  L("Opening: content from the task", 'Opening: its content comes from the task text', 110, 38),
  L("Closing: content from your essay", 'Closing: its content comes from your own essay', 190, 38),
  "The opening takes its content from the task text. The closing takes its content from the essay itself.",
  L("Like Lego", 'Like Lego: whole pieces of sentences from your paragraphs build the closing', 290, 36),
  "You don't need to reinvent the wheel. Go to the relevant paragraphs. There are real pieces of sentences there that build the closing, like Lego. In the next lesson I'll show you exactly which ones.",
 ]),
 dict(mode='concept', active=4, title='No new arguments', script=[
  L("No new arguments", 'Do not add a new argument in the closing', 110, 44),
  "We don't present new arguments. There's no new content in a closing.",
  "Even if you suddenly think of an argument that seems really, really good: don't.",
  L("A new argument = an unsupported argument", 'A new argument here is an argument without support,\nand that costs points', 210, 36),
  "Because then you've added an argument without support. The rater won't think 'wow, a good argument'. They'll see an unsupported claim, and it hurts you.",
 ]),
 dict(mode='concept', active=5, title='No counterargument', script=[
  L("Don't repeat the counterargument", 'Don\'t bring back the opposing argument at the end', 110, 40),
  "I also don't present the opposing argument again, the one from the rebuttal paragraph.",
  "I want to leave the rater with a good taste. They've already read the opposing argument, and they've seen me weaken it. Done.",
  L("Leave them with your position", 'End with your position and your reasons:\n"In conclusion, I support X because of A and B."', 230, 36),
  "So let's sum up: I support the cameras because of A and because of B. Goodbye.",
  "The score has already been set. Just don't make mistakes. That's all.",
 ]),
], T50)


# ================================================================= lesson 4: the three closing templates (seg46)
SB_CTPL = ['Three templates', 'Benefits summary', 'Where the parts are', 'Benefits: options', 'Benefits example',
           'Essay summary', 'Why this order', 'Example: for', 'Example: against', 'Time-pressure line',
           'Never skip it']

CLOSE_TPL = lesson('vr50-h-closing-tpl', 'Closing Paragraph Templates', SB_CTPL, [
 dict(mode='title', title='Closing Paragraph Templates', script=[
  "Now I'll show you three recommended templates for the closing paragraph.",
 ]),
 dict(mode='concept', active=0, title='Three templates', script=[
  L("1 · Benefits summary", '1 · Benefits summary: the default', 110, 42),
  "One: the benefits summary. This is the default, the one to use.",
  L("2 · Essay summary", '2 · Essay summary: for advanced writers', 200, 42),
  "Two: the essay summary. For more advanced writers.",
  L("3 · Time-pressure line", '3 · The time-pressure line: one sentence that saves you', 290, 42),
  "Three: my favourite. The time-pressure line.",
 ]),
 dict(mode='concept', active=1, title='Benefits summary', script=[
  "The benefits summary. First, my position: the answer to the question under discussion.",
  L("The template", 'In conclusion, [your position], since [benefit / harm 1], and also because [benefit / harm 2].', 110, 36),
  "Then the first benefit or harm, from argument paragraph one. Then the second, from argument paragraph two.",
  L("Part 1", '[your position]  =  the last sentence of your opening', 260, 34),
  L("Part 2", '[benefit / harm 1]  =  the second half of key sentence 1', 330, 34),
  L("Part 3", '[benefit / harm 2]  =  the second half of key sentence 2', 400, 34),
  "Simple as that.",
 ]),
 dict(mode='concept', active=2, title='Where the parts are', script=[
  "Let's see where each part comes from.",
  L("Opening -> position", 'Opening paragraph, last sentence: "In my view, X should be done."', 110, 32),
  "Your position is the last sentence of the opening. Go there, and take it: that's the start of your closing.",
  L("Key sentence 1", 'Key sentence 1:  "X should be done, because  [it will bring benefit 1]."', 200, 32),
  "Then go to the key sentence of argument one. Remember its form: I'm for or against something, because it will bring this benefit or that harm.",
  D("Circle the second half of key sentence 1"),
  "Take its second half, the benefit, and put it here.",
  L("Key sentence 2", 'Key sentence 2:  "Moreover, X  [will prevent harm 2]."', 290, 32),
  D("Circle the second half of key sentence 2"),
  "The same with paragraph two. Copy the second half of its key sentence: the benefit or the harm. That's all.",
  L("Result", 'Position + benefit 1 + benefit 2  =  a complete closing', 400, 38),
 ]),
 dict(mode='concept', active=3, title='Benefits: options', script=[
  "Some phrase options, so it's not always the same sentence.",
  L("Opening words", 'Opening words:  In conclusion, ... · To sum up, ... · All things considered, ...', 110, 32),
  L("Cause connectors", 'Cause:  since ... · because ... · as ... · given that ...', 200, 32),
  L("Adding the second", 'Adding the second:  ..., and also because ... · ..., as well as ... · Moreover, ...', 290, 32),
  "The idea is the right connectors: cause and effect, then addition.",

 ]),
 dict(mode='concept', active=4, title='Benefits example', script=[
  "Here's an example for the cameras.",
  A("The example appears", T('In conclusion, face-recognition cameras should be installed in public spaces, since they would deter offenders and thus reduce harm to citizens in these areas, and also because they would save law-enforcement resources.', size=32, x=410, y=110, w=1140)),
  D("Underline: face-recognition cameras should be installed in public spaces"),
  "I answered the question under discussion. That's exactly the last line of my opening.",
  D("Underline: they would deter offenders and thus reduce harm to citizens"),
  "Benefit one: deterrence, which reduces harm to citizens. Taken from argument paragraph one, the second half of its key sentence.",
  D("Underline: they would save law-enforcement resources"),
  "Benefit two: saving resources.",
  L("Short, zero mistakes", 'Short, complete, zero mistakes. Nothing more is needed.', 380, 36),
  "A short, excellent closing. No complaints, zero mistakes. As the saying goes: less is more. That's the place for it.",
 ]),
 dict(mode='concept', active=5, title='Essay summary', script=[
  "The second template summarizes the whole essay, and that's really the job of a closing. But it suits more advanced structures.",
  "My recommendation: don't start with it. Start with the benefits summary. Move to this one only when you feel you're progressing and want to push higher.",
  L("The template", 'In conclusion, although [counterargument], I believe that [your position], since [weakening]. Moreover, [benefit / harm 1], and [benefit / harm 2].', 110, 32),
  L("Counterargument", '[counterargument]  =  the first line of your rebuttal paragraph', 290, 30),
  L("Position", '[your position]  =  the last sentence of your opening', 350, 30),
  L("Weakening", '[weakening]  =  the weakening in your rebuttal paragraph (after the counterargument\'s explanation)', 410, 30),
  L("Benefits", '[benefit / harm 1, 2]  =  the second halves of key sentences 1 and 2', 500, 30),
  "Remember the rebuttal paragraph? The opposing argument, its explanation, and then the weakening. I take the weakening from there.",
  L("Options", 'Options:  Although / While / Admittedly, ... ; Moreover / In addition / Furthermore, ...', 590, 30),
 ]),
 dict(mode='concept', active=6, title='Why this order', script=[
  "A full, rich paragraph that really sums up the essay. But notice: not in the essay's order.",
  L("Essay order", 'The essay:  argument 1 -> argument 2 -> counterargument -> weakening', 110, 34),
  L("Closing order", 'The closing:  counterargument -> position -> weakening -> benefit 1 -> benefit 2', 190, 34),
  "In the essay it was argument one, argument two, then the counterargument, then the weakening. Why reorder?",
  L("It reads better", 'It reads more smoothly: "although ... I believe ... since ..."', 300, 34),
  "First, it fits together better, as you'll see in the example.",
  L("People remember the end", 'People remember the end best, so end with your own reasons', 380, 34),
  "And second: people remember the end best. I want to leave the rater with my position. I open with the counterargument, give my view, weaken it, add benefit one and benefit two, and that's the feeling they're left with.",
 ]),
 dict(mode='concept', active=7, title='Example: for', script=[
  "An example, for the cameras.",
  A("The example appears", T('In conclusion, although there is a risk of harm to privacy, I believe that face-recognition cameras should nevertheless be installed in public spaces, since safeguards can be put in place to keep that harm to a minimum. Moreover, the cameras would deter offenders and thus reduce harm to citizens in these areas, and they would lead to considerable savings in law-enforcement resources.', size=30, x=410, y=110, w=1140)),
  D("Label: counterargument - position - weakening - benefit 1 - benefit 2"),
  "The counterargument: a risk to privacy. My position: despite it, install the cameras.",
  "Why? The weakening: safeguards can keep the harm minimal.",
  "Moreover: I didn't only weaken the counterargument, I have more advantages. Deterrence, and savings in resources.",
 ]),
 dict(mode='concept', active=8, title='Example: against', script=[
  "It's not that we're always for the cameras. Here's the other side.",
  A("The example appears", T('In conclusion, although crime in the monitored areas would decrease, this is, in my view, a zero-sum game, since offenders would not stop breaking the law; they would simply move to areas that are not monitored. Moreover, the constant tracking of law-abiding citizens would seriously harm their privacy, and there is a real danger that the database could leak and be used to harm people.', size=30, x=410, y=110, w=1140)),
  "The counterargument: crime in the monitored areas would drop.",
  "Here I didn't write 'but in my view, cameras should not be installed'. I used an expression: a zero-sum game.",
  L("Zero-sum game", 'A zero-sum game: what one side gains, the other side loses (+5 and -5 = 0)', 470, 32),
  "What is a zero-sum game? One side pulls here, the other pulls there, and we end up at zero. Plus five, minus five. The offender stops stealing in the monitored area, so he steals somewhere else, just as often as before.",
  "That's my weakening, explained. Then harm one: serious harm to privacy. Harm two: the danger that the database leaks and the information is used to hurt people.",
 ]),
 dict(mode='concept', active=9, title='Time-pressure line', script=[
  "And now a template I think is really cool: the time-pressure line.",
  "Often you reach the end of the essay with no time left. You got stuck somewhere. Planning and writing an essay in thirty-five minutes isn't easy. Many students barely finish the closing.",
  L("The template", 'In conclusion, [your position], since, as shown above, its advantages outweigh its disadvantages.', 110, 36),
  "You state your position and say its advantages outweigh its disadvantages. A fixed wording. One sentence.",
  L("Against?", 'Against:  ..., since, as shown above, its disadvantages outweigh its advantages.', 250, 32),
  L("Example", 'In conclusion, face-recognition cameras should be installed in public spaces, since, as shown above, the advantages of doing so outweigh the disadvantages.', 340, 32),
  "Example: in conclusion, face-recognition cameras should be installed in public spaces, since, as shown above, the advantages outweigh the disadvantages. That's it.",
  L("Memorize it", 'Memorize it. It may save you one day.', 500, 40),
  "If your essay up to the closing is excellent, with this line and a half it stays excellent. The closing doesn't add points; the score was set before the rater got there.",
 ]),
 dict(mode='concept', active=10, title='Never skip it', script=[
  "We've seen quite a few essays that arrive with no closing at all.",
  L("No closing = lost points", 'An essay without a closing loses points, however good the rest is', 110, 38),
  "So know this: even an excellent essay without a closing loses points.",
  L("Don't write half a paragraph", 'Short on time? Not half a paragraph that stops mid-sentence', 210, 36),
  "If you're short on time: don't give up, don't panic, and don't write half a paragraph: a position, then a benefit, and stopping in the middle of the sentence. No.",
  L("Choose by the clock", 'Time left?  Benefits summary (or essay summary)\nNo time?  The time-pressure line', 320, 38),
  "Not under time pressure? Use the benefits summary, or the essay summary if you want something more advanced. Under time pressure? The one-line template.",
 ]),
], T50)


# ================================================================= lesson 5: the recommended structure (seg47 + findings 21-24)
SB_STRUCT = ['No required structure', 'It saves time', 'It covers the rubric', 'It keeps the length',
             'Bowling bumpers', 'Basic structure 1', 'One card, one use', 'Basic structure 2',
             'Short on time?', 'Plan it first']

STRUCT = lesson('vr50-h-structure', 'The Recommended Structure', SB_STRUCT, [
 dict(mode='title', title='The Recommended Structure', script=[
  "We know how to write every paragraph. Now: how to arrange them into an essay.",
 ]),
 dict(mode='concept', active=0, title='No required structure', script=[
  L("No required structure", 'There is no structure you must use', 110, 44),
  "Look: there is no structure you must write in.",
  L("Opening, body, closing", 'Yes: an opening, a body, a closing. The body can be arranged in many ways', 200, 36),
  "Yes, you need an opening and a closing, and the body in the middle. But the body can be arranged in all sorts of ways. Mixed paragraphs, this before that. There's almost nothing forbidden.",
  L("We recommend one, to keep it simple", 'But to keep things simple, we recommend one structure.\nGood content + good language in it = a top score', 320, 36),
  "But so you don't get tangled up, we recommend one structure. If the content and the language you pour into it are good, it can reach the top score.",
 ]),
 dict(mode='concept', active=1, title='It saves time', script=[
  "A recommended structure has several advantages.",
  L("Advantage 1: it saves time", 'Advantage 1 · It saves time', 110, 42),
  "One: it saves time. You don't have to think, for every essay: which structure fits? Two arguments or one? Rebuttal before or after? Split it?",
  L("Fixed connectors and phrases", 'Fixed connectors and phrases for every spot:\nIn my opinion, ... · Moreover, in my opinion, ... · On the other hand, some argue that ... · Admittedly, ..., but ...', 220, 32),
  "More than that: you have fixed connectors for every spot: the start of a paragraph, the middle, the weakening. Even fixed phrases, like 'Admittedly, there is some truth in this, but ...'.",
 ]),
 dict(mode='concept', active=2, title='It covers the rubric', script=[
  L("Advantage 2: it contains the whole rubric", 'Advantage 2 · It contains everything the rubric checks', 110, 40),
  "Two: it contains everything in the rubric. Your score depends on how well you meet each of the rubric's criteria.",
  L("Without it: easy to miss something", 'Without it, it is easy to miss something, for example:', 210, 36),
  "Without a recommended structure, you might build an essay that misses part of it. For example:",
  L("No rebuttal", '· No rebuttal paragraph: you never dealt with the opposing view', 290, 34),
  "no rebuttal paragraph. The raters expect you to deal with the other side, and a separate rebuttal paragraph is our way of doing it. Without it, your score drops, even with excellent arguments.",
  L("Position only at the end", '· The position only at the end: the thread wobbles', 360, 34),
  "Or you decided to reveal your position only at the end of the essay. These are just a few examples.",
  L("It prevents mistakes", 'A huge advantage: you don\'t miss things, you don\'t make these mistakes', 460, 34),
 ]),
 dict(mode='concept', active=3, title='It keeps the length', script=[
  L("Advantage 3: the right length", 'Advantage 3 · It keeps the essay at the right length', 110, 40),
  "Three: writing in the recommended structure keeps you at the right length.",
  L("Too short", 'Invent your own structure: maybe too short (under 25 lines) ...', 210, 34),
  "Someone who invents their own structure may end up too short,",
  L("... or out of lines", '... or four argument paragraphs, line 50, and no room for the closing', 290, 34),
  "or reach fifty lines without finishing, because they wrote four argument paragraphs. Wait, what? I'm at line fifty, there's nowhere to write the closing, and I can't close the essay.",
  L("The official limits", 'Minimum 25 lines · maximum 50 (the answer sheet) · good essays: usually about 30-40', 400, 32),
 ]),
 dict(mode='concept', active=4, title='Bowling bumpers', script=[
  "And maybe the thing I love most about the recommended structure: it simply prevents mistakes. It gives you boundaries.",
  L("A template with fixed openers", 'A template with fixed openers:  In my opinion, ... · Moreover, in my opinion, ... · On the other hand, ... · Admittedly, ..., but ...', 110, 32),
  "You get a template, a real stencil. You pour the content in and move inside those boundaries.",
  L("Bumpers on a children's bowling lane", 'Like the bumpers on a children\'s bowling lane', 230, 38),
  "I compare it to children's bowling. When kids play, so the ball doesn't fall into the gutter, they raise barriers on both sides.",
  L("The ball bounces back in", 'The ball drifts, hits the bumper, and comes back into the lane', 310, 36),
  "When the ball drifts, it hits the barrier and comes back in. That is the recommended structure. Wherever you'd have drifted out, it keeps you in the lane.",
  L("Maybe no strike, but no gutter", 'Maybe not a strike, but you knock down pins, not a gutter ball', 400, 36),
  "Maybe it won't be a strike in the end. But you'll knock down pins, instead of an essay that misses completely.",
 ]),
 dict(mode='concept', active=5, title='Basic structure 1', script=[
  "From this shape we derive the recommended structure. Opening and closing, same as before. The body:",
  L("1 · Opening", '1 · Opening paragraph: background + dispute + your position', 110, 32),
  L("2 · Argument 1", '2 · Argument paragraph 1: the first benefit of your side', 175, 32),
  L("3 · Argument 2", '3 · Argument paragraph 2: a second benefit of your side (or a harm of the other side)', 240, 32),
  L("4 · Rebuttal", '4 · Rebuttal paragraph: the opposing argument + a weakening with a NEW, third argument', 330, 32),
  L("5 · Closing", '5 · Closing paragraph: the summary', 420, 32),
  "Argument one: why my side brings a benefit. Argument two: a second benefit, or the harm of the other side, which is the same thing: one side's harm is the other's benefit.",
  "Then I confront an opposing view, and weaken it with a third argument. A new one, not one I've already used. Using one of those again would be repetition.",
  L("A clear main thread", 'I am for the cameras -> a reason for -> another reason for -> some are against, but ... -> summary', 500, 30),
  "Everything is here: dealing with the opposing view, developed and explained arguments, and a very clear main thread. Let's call it basic structure one.",
 ]),
 dict(mode='concept', active=6, title='One card, one use', script=[
  "Students often tell me: I tried, but my weakening in the rebuttal turned out to be argument two again. Is that okay?",
  L("No: that's repetition", 'No. Once you have used an argument, you do not use it again', 110, 40),
  "No. That's repetition. Once you've used something in the essay, you don't use it again.",
  L("The card game War", 'Like the card game War: each player throws a card, the highest wins', 210, 36),
  "Think of the card game War. Everyone throws a card, the highest card wins.",
  L("Throw your ace first", 'Throw your ace first: the strongest argument goes in argument paragraph 1', 300, 36),
  "I throw my first argument: an ace. Great, because I want my strongest argument first. It's the first time the rater sees my content. The opening didn't show any.",
  L("A thrown card is gone", 'Then a king or a queen. But you can\'t pick up the ace and throw it again', 390, 36),
  "Then a king or a queen. And when I get to the rebuttal, I have no good cards left. I can't pick up the ace and throw it again.",
 ]),
 dict(mode='concept', active=7, title='Basic structure 2', script=[
  "So what do I do? I simply drop argument paragraph two, and keep argument two for the rebuttal.",
  L("1 · Opening (the longer, rewrite version)", '1 · Opening paragraph (use the longer, rewrite template)', 110, 32),
  L("2 · Argument 1", '2 · Argument paragraph 1', 175, 32),
  L("3 · Rebuttal with argument 2", '3 · Rebuttal paragraph: the opposing argument + a weakening that uses argument 2\n(a richer paragraph, with support)', 240, 32),
  L("4 · Closing", '4 · Closing paragraph', 370, 32),
  "Dealing with an opposing argument matters more to me than one more argument for my side.",
  "And in the rebuttal, argument two does more: it supports my side and it also weakens the opposing argument. Let's call it basic structure two.",
  L("Enrich the others", 'One paragraph fewer, so enrich the others: the rewrite opening, a fuller argument paragraph', 450, 32),
  "By the way, with one paragraph fewer, you can enrich the opening and the argument paragraph. That's exactly when the longer, rewrite opening is useful.",
  "And again: written in this structure, with good content and language, it can reach the top score. It's not that they give fewer points for it.",
 ]),
 dict(mode='concept', active=8, title='Short on time?', script=[
  "A tip for anyone who struggles to finish, or who's always borderline with time.",
  L("Swap argument 2 and the rebuttal", 'Always short on time? Swap argument 2 and the rebuttal:', 110, 38),
  L("The order", 'Opening -> Argument 1 -> Rebuttal -> (Argument 2, if there is time) -> Closing', 200, 34),
  "Start with argument one, go straight to the rebuttal. Now you've already dealt with an opposing view.",
  "Then, depending on the time left: if you make it, add argument two. If not, skip it. You still have a complete essay, including the opposing view.",
  L("Better than a rushed rebuttal", 'Better than: argument 1, argument 2, and no time for the rebuttal', 300, 34),
  "That's better than argument one, argument two, and no time for the rebuttal, or a rushed weakening.",
 ]),
 dict(mode='concept', active=9, title='Plan it first', script=[
  "But how do I know, when I write the opening, that I need the longer one? I start writing, argument one, argument two, and only at the end discover I'm using the same argument again?",
  L("Plan before the first word", 'You plan the essay before you write the first word', 110, 40),
  "No. Before we start writing, we plan. Before the first word of the opening, I already know exactly what the essay will look like:",
  L("Which paragraphs, which arguments", 'Which paragraphs, which argument in each, which structure, which opening template', 200, 34),
  "which paragraphs, which argument in each paragraph. We do all that in the planning stage: the essay skeleton. That's the next lesson.",
  L("A tool, not a rule", 'The structure is a tool, not an exam rule; what the raters do expect is that you deal with the other side', 330, 32),
  "And one note: this structure is a tool, not an exam rule. What the raters do expect is that you deal with the other side, and this structure makes sure you do.",
 ]),
], T50)


# ================================================================= lesson 6: the essay skeleton (seg48 + seg49)
SB_SKEL = ['Plan, then write', 'How to build it', 'What goes in', 'Just a few words', 'Relevance check',
           'Flow check', 'The task', 'Analyse, find ideas', 'Skeleton: against']

SKEL = lesson('vr50-h-skeleton', 'The Essay Skeleton', SB_SKEL, [
 dict(mode='title', title='The Essay Skeleton', script=[
  "Before we write the essay itself, we plan it. Planning comes before writing.",
  "And the product of planning is the essay skeleton.",
 ]),
 dict(mode='concept', active=0, title='Plan, then write', script=[
  L("Planning", 'Planning: analyse the task, find arguments, choose a side, build the skeleton', 110, 34),
  "In the planning stage we analyse the task, think of arguments, and choose a side. There are lessons on each of these.",
  "Then, before we really start writing, we build ourselves a skeleton.",
  L("The skeleton separates the stages", 'The skeleton separates content from writing', 210, 38),
  "What is it? With the skeleton I separate the two stages. First I plan everything I want to write:",
  L("Know everything in advance", 'Before writing, I know: each argument, how I will explain it, which example I will use,\nthe counterargument, and how I will weaken it', 300, 32),
  "my argument, my explanation, which example, in every argument paragraph. The counterargument, and how I'll weaken it. I know everything in advance.",
  L("Then the writing flows", 'Then the writing flows: no stopping to ask "What now? Which example?"', 440, 34),
  "Then when I write, it flows. I don't have to stop and ask: wait, what now? Which example? How do I explain this? It's in the skeleton.",
  L("Better content and better language", 'The result: better content AND better language', 530, 38),
  "This way we improve both the content and the language.",
 ]),
 dict(mode='concept', active=1, title='How to build it', script=[
  "How do we build a skeleton?",
  L("Step 1", '1 · Analyse the task and find arguments (from the task, who is involved, points of view)', 110, 34),
  "We start from the analysis of the task, and find arguments in the three ways we learned: from the task, who is involved, and points of view.",
  L("Step 2", '2 · Confirm your first position, or change it, based on the arguments you found', 190, 34),
  "Then we confirm the first position we chose, our leaning, or change it, based on the arguments we found.",
  L("Step 3", '3 · Choose: the arguments for your argument paragraphs,\nthe counterargument, and the weakening', 270, 34),
  "Then we build the skeleton: out of all the arguments I found, which ones actually go into my essay? I choose the arguments for my argument paragraphs, the counterargument, and how I'll weaken it.",
  L("Step 4", '4 · Check relevance to the task and the flow of ideas', 390, 34),
  "And then we check each one: relevance to the task, and the flow.",
 ]),
 dict(mode='concept', active=2, title='What goes in', script=[
  "In the skeleton, I don't settle for the argument alone.",
  L("Argument paragraphs", 'Each argument paragraph:  the argument + its explanation (the chain) + the example or comparison', 110, 32),
  "For each argument paragraph I write the argument, its explanation, and the example or comparison I intend to use.",
  L("Rebuttal paragraph", 'Rebuttal paragraph:  the counterargument + the weakening\n(support there is optional, depending on time)', 220, 32),
  "In the rebuttal: the counterargument and the weakening. Support, an example or comparison, is optional there, depending on how much time you think you have.",
  L("Basic structure 2", 'Using basic structure 2? Then the rebuttal is richer and fuller, with support', 350, 32),
  "Unless, for example, you have only one argument paragraph and the second argument is used for the weakening. Then you drop argument paragraph two and make the rebuttal richer, with support.",
 ]),
 dict(mode='concept', active=3, title='Just a few words', script=[
  L("A few words, not sentences", 'I do not write it all out: a few words that remind me what I planned', 110, 36),
  "Pay attention, I'll say it again: I don't write everything out. Just a few words that remind me what I planned.",
  L("Your own level of detail", 'As short as you like, as long as you will understand it later', 210, 36),
  "How short? As short as works for you. A word or two, half a sentence, even a full sentence if you need it.",
  "What matters is that when you get to the writing, you don't say: wait, what did I mean? What's the link? I don't remember.",
  L("Know yourself", 'Everyone knows how much detail they need to remember what they meant', 330, 34),
  "Everyone knows themselves, and how much detail they need.",
 ]),
 dict(mode='concept', active=4, title='Relevance check', script=[
  "After we've chosen what goes into each paragraph, we check. First: is each argument really relevant to the task?",
  L("Relevance", 'Is each argument about the exact question? Remember the near miss from the relevance lesson', 110, 36),
  "Remember the near miss from the relevance lesson: an argument can be close to the topic and still miss the question. Check each one.",
 ]),
 dict(mode='concept', active=5, title='Flow check', script=[
  "Second: the flow of ideas. It shows in two places.",
  L("In the whole essay", '1 · The whole essay: arguments -> counterargument -> weakening: do they follow in sequence?', 110, 34),
  "In the whole essay: I look at my arguments, then the counterargument, then the weakening. Does it fit together in sequence?",
  L("Inside each argument", '2 · Inside each argument: is there a chain from the argument to its result?', 220, 34),
  "And inside each argument: does my explanation have a chain, a logical sequence from my argument to the benefit or harm I think we'll reach?",
  L("The chain", 'The chain:  [what the task asks about] -> step -> step -> [the final result]', 330, 34),
  "That's exactly the chain you already know: short steps from the thing the task asks about to the final result. Test every arrow: why would this step lead to the next?",
  "Let's build a sample skeleton.",
 ]),
 dict(mode='concept', active=6, title='The task', script=[
  "Here's our example task, which we already know. If you need to, pause and read it again.",
  A("The task appears", dict(prompt_box(CAM_PROMPT, CAM_Q), x=410, y=60)),
  "We start with the analysis of the task. I mark the important things.",
  D("Underline: help prevent crimes ... reduce crime or even eliminate it"),
  D("Underline: serious harm to privacy and constant tracking"),
  "'Reduce crime or even eliminate it.' And: 'serious harm to privacy'.",
 ]),
 dict(mode='concept', active=7, title='Analyse, find ideas', script=[
  L("Analysis", 'Analysis: clashing interests (security vs privacy). "No" is absolute; "yes" is the flexible end', 90, 30),
  "A quick analysis: clashing interests, security against privacy. 'No cameras' is absolute; 'yes' is the flexible end.",
  L("For", 'For:  deterrence -> less crime  ·  saves resources (catch, convict)  ·  a safe country attracts tourists', 190, 30),
  L("Against", 'Against:  privacy  ·  a database breach (blackmail)  ·  tracking someone\'s routine  ·  high cost, unproven benefit', 290, 30),
  "Then I throw out ideas, a word or two each. For: deterrence, saving resources, even tourism. Against: privacy, a database breach, tracking someone's routine, and a high cost.",
  L("Weakenings", 'Weakenings:  privacy? phones already record where we are (does not hold)  ·  deterrence? offenders move to private spaces (the reversal)', 390, 30),
  "And weakenings: privacy? Our phones already record where we are. Deterrence? Offenders may just move to private spaces. Some of these take a moment, so give the analysis time.",
  L("Position", 'Now confirm your first position, or change it', 520, 34),
  "Now I confirm my first position, or change it. Say I chose: against the cameras.",
 ]),
 dict(mode='concept', active=8, title='Skeleton: against', script=[
  "The skeleton against the cameras. Opening and closing aren't in the skeleton: their content is known. Only the body. In the next lesson we'll see a 'for' skeleton, written as chains.",
  L("Argument 1", 'Argument 1 · Privacy:  tracking = harm to privacy -> a basic right -> harming it needs\na very strong reason -> this reason is not strong enough', 110, 30),
  "Argument one: this is tracking, a harm to privacy. Privacy is a basic right, and harming it needs a very, very good reason. Here the reason isn't good enough.",
  L("Argument 2", 'Argument 2 · The database:  cameras -> a database of sensitive data -> breach or leak\n-> harm, blackmail.  Example: government databases have leaked before', 240, 30),
  "Argument two: the cameras create a database with a lot of very sensitive data. A breach or leak could lead to harm, to blackmail.",
  "Example: there have been real cases of government databases that leaked, with ID numbers, addresses and names circulating online. If it has happened before, who says it won't happen again?",
  L("Rebuttal", 'Rebuttal · Counter: cameras protect security, and security matters more (explain why)\nWeakening, turned around: offenders move to private spaces -> people may be hurt more', 380, 30),
  "Counterargument: cameras protect security, and security matters more. Of course we explain why.",
  "And my weakening turns it around: you want more security, but by installing cameras, offenders move elsewhere: to private spaces. People may even be hurt more. You protect one place and harm another.",
  L("And that's an essay", 'Now: paragraph 1, paragraph 2, the rebuttal. The opening and closing are standard.', 530, 32),
  "And there it is: an essay. I turn this into paragraph one, paragraph two, the rebuttal paragraph. The opening and the closing are standard.",
 ]),
], T50)


# ================================================================= lesson 7: from skeleton to essay (seg49 end + the chain + 35-minute plan)
ESSAY_P = [
 ('Opening paragraph (rewrite template, shortened)',
  'In recent years, security authorities have been working to set up a national network of face-recognition cameras in public spaces. These cameras can identify people and objects in real time, provided that their images already appear in a database. Supporters believe that the system will help to prevent crimes, to stop them while they are happening and to catch offenders afterwards, while opponents fear that constant monitoring will seriously harm the privacy of ordinary citizens. In my view, such cameras should be installed, as long as the data they collect is strictly protected.'),
 ('Argument paragraph 1 (deterrence)',
  'In my opinion, face-recognition cameras are likely to deter potential offenders. When people know that a public area is filmed and that they can be identified within seconds, the risk of being caught becomes real to them. As a result, many of those who are considering breaking the law may decide that the risk is not worth taking, which in turn reduces the number of offences in the monitored areas. Traffic-light cameras illustrate this effect: at junctions where drivers know that every car is recorded, few of them run a red light, not because they have become more careful by nature, but because they expect to be fined. In the same way, a network of cameras can prevent crimes before they occur, and thus protect potential victims instead of merely punishing offenders later.'),
 ('Argument paragraph 2 (resources)',
  'Moreover, in my opinion, the cameras would allow the police to use their limited resources more efficiently. At present, identifying a suspect may require many officers to collect statements and search through hours of footage. A system that recognizes a face automatically could shorten this process considerably, and once the process is shorter, officers are free to deal with other cases. Moreover, clear footage makes it easier to prove guilt in court. Airport security offers a useful comparison: scanners now check luggage that staff once had to open by hand, so the same level of safety can be maintained with shorter queues and fewer workers.'),
 ('Rebuttal paragraph (counterargument + weakening)',
  'On the other hand, some argue that a national camera network would seriously harm privacy, since the authorities could follow every step that citizens take in public. This concern deserves attention, because a database of faces and locations could be misused. However, a great deal of location data already exists: many people carry smartphones that record where they are at almost every moment. The real question, therefore, is not whether such information exists, but who may access it and under what conditions. If the database were encrypted, and only a small, supervised unit could search it, the risk of misuse would be considerably reduced, while the benefits to public safety would remain.'),
 ('Closing paragraph (benefits summary)',
  'In conclusion, face-recognition cameras should be installed in public spaces, since they would deter offenders and thus reduce crime in the monitored areas, and also because they would save the police valuable resources.'),
]

SB_ESSAY = ['Skeleton with chains', 'The 35-minute plan', 'Why 8-10 minutes', 'One sentence ahead', 'The full essay',
            'On the answer sheet']


def essay_slide(i, active, intro, notes):
    head, text = ESSAY_P[i]
    return dict(mode='concept', active=active, title=SB_ESSAY[active], script=[
        intro,
        L(head + ' appears', head, 70, 30),
        A("The paragraph appears", T(text, size=29, x=410, y=130, w=1140)),
    ] + notes)


ESSAY = lesson('vr50-h-essay', 'From Skeleton to Essay', SB_ESSAY, [
 dict(mode='title', title='From Skeleton to Essay', script=[
  "We have a skeleton. Now let's turn it into a full essay, within thirty-five minutes.",
 ]),
 dict(mode='concept', active=0, title='Skeleton with chains', script=[
  "Here's a skeleton for the other side, for the cameras, written as chains: about ten words per argument, from the thing the task asks about to the final result.",
  L("P2 chain", 'P2 · cameras visible -> offenders expect to be identified -> fear of being caught -> fewer offences\n     support: traffic-light cameras', 110, 29),
  "Paragraph two: visible cameras, offenders expect to be identified, they fear being caught, fewer offences. Support: traffic-light cameras.",
  L("P3 and P4", 'P3 · a second reason, as a chain (resources)    P4 · their chain + its weakest arrow (privacy)', 230, 29),
  "Paragraph three: a second reason, resources, as its own chain. Paragraph four: the opponents' chain, privacy, with its weakest arrow circled.",
  L("Each chain = one paragraph's job", 'Each chain is one paragraph\'s job. Writing = "pasting" the chain into sentences, with varied connectors', 350, 30),
  "Each chain is the job of one paragraph. When you write, you paste the chain into the paragraph, with varied connectors, so it doesn't sound pasted.",
 ]),
 dict(mode='concept', active=1, title='The 35-minute plan', script=[
  "The whole task is thirty-five minutes. Here's a recommended plan.",
  L("0-10", '0-10   Read the task, analyse it, find arguments, choose a side, skeleton + chains   (8-10 min)', 110, 30),
  L("10-13", '10-13  Opening paragraph   (2-3 min)', 180, 30),
  L("13-19", '13-19  Argument paragraph 1   (about 6 min)', 240, 30),
  L("19-25", '19-25  Argument paragraph 2   (about 6 min)', 300, 30),
  L("25-31", '25-31  Rebuttal paragraph   (about 6 min)', 360, 30),
  L("31-33", '31-33  Closing paragraph   (about 2 min; no time? the time-pressure line)', 420, 30),
  L("33-35", '33-35  Proofreading   (2-3 min)', 480, 30),
  "Up to ten minutes of planning. Two or three for the opening. About six for each body paragraph. Two for the closing, and two or three for proofreading.",
  L("Check the clock at 19 and 25", 'Check the clock after each paragraph. Behind at minute 25? Shorten, but keep the rebuttal and the closing.', 560, 30),
  "Look at the clock after every paragraph. These are guidelines; in practice you'll find your own times, and we'll see how to measure them when we review an essay.",
 ]),
 dict(mode='concept', active=2, title='Why 8-10 minutes', script=[
  L("Skeleton: no more than 8-10 minutes", 'Planning and the skeleton: no more than 8-10 minutes', 110, 40),
  "In terms of time, we want to finish the skeleton in no more than eight to ten minutes.",
  L("That's a lot, and it should be", 'That is a lot of time, on purpose', 210, 38),
  "Eight to ten minutes is a lot. Why? Because finding the right arguments, the right explanations, the right weakenings takes time. It doesn't always jump out in the first minute.",
  L("The official advice agrees", 'The official guide: devote the first few minutes to formulating ideas and planning', 300, 34),
  "The official guide says the same: devote the first minutes to formulating ideas and planning the structure.",
  L("A polished skeleton -> writing goes tick-tock", 'A well-built skeleton makes the writing faster, easier, and higher in language', 400, 36),
  "Once your skeleton is polished and sits well, the writing itself goes tick-tock: faster, easier, and in better language, because now you have time to think about wording.",
 ]),
 dict(mode='concept', active=3, title='One sentence ahead', script=[
  "Here's a tip for the writing itself.",
  L("Don't write non-stop", 'Don\'t write the whole paragraph in one go', 110, 38),
  "When I write, I don't just write the whole paragraph straight through.",
  L("Step 1", '1 · Form the key sentence in your head, as well as you can. Then write it.', 200, 34),
  "I think about the first sentence, the key sentence. I word it in my head as well as I can, and then I write it.",
  L("Step 2", '2 · While writing it, form the next sentence in your head, and polish it.', 280, 34),
  "While I'm writing it, I'm already forming the next sentence in my head. If I want, I rewrite it a little in my head, and then write it.",
  L("Step 3", '3 · Write it, while forming the one after. And so on.', 360, 34),
  "And while writing that one, I form the next.",
  L("Why", 'You fix a sentence before it is on paper: a clearer thread, higher language, fewer corrections later', 460, 32),
  "Why? It lets me rewrite and fix a sentence before it's on paper. A clearer thread, better language, and fewer corrections afterwards.",
 ]),
 dict(mode='concept', active=4, title='The full essay', script=[
  "And the full essay from this skeleton? You've already seen it: it's the model camera essay from the two lessons 'What Is Expected of Me', at the start of the course.",
  L("Back to the model essay", 'The full essay from this skeleton = the model camera essay in "What Is Expected of Me" (both parts)', 110, 36),
  "Go back and read it again. Now you'll recognise every part: the opening, the two chains pasted into argument paragraphs, the rebuttal at the weakest arrow, and the closing.",
  L("Read only the key lines", 'Read only the key lines: position -> reason 1 -> reason 2 -> the other side, answered -> the same position', 250, 32),
  "Read only its key lines, and you see the whole thread: position, reason, reason, the other side answered, and the same position at the end.",
 ]),
 dict(mode='concept', active=5, title='On the answer sheet', script=[
  "How long is that on the answer sheet?",
  A("The filled answer sheet appears", dict(vis(answer_sheet_svg(filled_lines=37)), x=400, y=20, w=640, h=832)),
  L("About 37 lines", 'In average handwriting: about 35-40 lines', 110, 34, x=1070, w=470),
  "In average handwriting, a full essay like the model essay fills roughly thirty-five to forty lines.",
  L("Inside the limits", 'Above the 25-line minimum, below the 50-line maximum', 260, 30, x=1070, w=470),
  "Well above the twenty-five-line minimum, comfortably below fifty.",
  L("Blank line between paragraphs", 'Plus a blank line between paragraphs, for corrections', 400, 30, x=1070, w=470),
  "And remember to leave a blank line between paragraphs. We'll use it for corrections.",
  L("Length is not the goal", 'The length comes from explained reasons, not from padding', 540, 30, x=1070, w=470),
  "The length came from explained reasons, not from padding.",
 ]),
], T50)


# ================================================================= lesson 8: proofreading and corrections (seg50)
SB_PROOF = ['Three stages', 'A first draft', 'Two to three minutes', 'Language, not content', 'What to check',
            'Cut repetition', 'Focus and cohesion', 'How to correct', 'Handwriting', 'Proofread as you go',
            'Go to the weak spot']

PROOF = lesson('vr50-h-proofread', 'Proofreading and Corrections', SB_PROOF, [
 dict(mode='title', title='Proofreading and Corrections', script=[
  "I mentioned this in one of the first lessons, but I'll repeat it, because this is the place.",
 ]),
 dict(mode='concept', active=0, title='Three stages', script=[
  L("Three stages of writing", 'Writing has three stages:  planning · producing the text · checking (proofreading)', 110, 34),
  "Writing an essay has three stages: planning, producing the text, and checking, which is proofreading and corrections.",
  L("Time limits hurt them", 'With a short time limit, the stages are squeezed', 210, 34),
  "When you're short of time, and thirty-five minutes to plan, write and check is short, these stages get squeezed. You'll feel it in your first timed essay.",
  L("Most hurt: checking", 'Hurt most: proofreading.  Then: planning.  Least: producing the text', 300, 34),
  "The stage hurt most is proofreading. Next, planning, because planning takes time. Producing the text is hurt least; we basically know how to write.",
 ]),
 dict(mode='concept', active=1, title='A first draft', script=[
  L("Raters read a first draft", 'The official guide: raters are instructed to view the essay as a first draft', 110, 36),
  "The test makers understand this. So raters are instructed to view the essay as a first draft only, and evaluate it accordingly.",
  L("Not the perfect essay", 'You are not scored against the perfect essay,\nbut against a good draft written in 35 minutes', 220, 36),
  "Your essay doesn't have to be perfect. It's not scored against the most perfect essay possible, but against a draft written in thirty-five minutes with little or no proofreading.",
  L("So: proofreading matters less", 'So proofreading is useful, but it does not need much time', 360, 36),
  "The conclusion: proofreading is almost unnecessary. I won't say completely, because that's not true. You can still improve things, and it's worth doing. But not with much time.",
 ]),
 dict(mode='concept', active=2, title='Two to three minutes', script=[
  L("2-3 minutes, no more", 'Leave 2-3 minutes for proofreading. No more.', 110, 42),
  "Leave two to three minutes for it. No more.",
  L("You can't check everything", 'In 2-3 minutes you cannot fix the whole essay, so be selective', 210, 36),
  "And in two or three minutes, you really can't go over the whole essay and fix everything. So let's see how to do it well.",
 ]),
 dict(mode='concept', active=3, title='Language, not content', script=[
  L("Mainly language", 'Correct mainly language, not content', 110, 42),
  "Mainly, I correct language, and less content.",
  L("Content is hard to fix now", '"This argument isn\'t good enough, let\'s replace it"? Not in 2-3 minutes', 200, 36),
  "Content is hard to fix now. 'This argument isn't good enough, let's swap it'? You really can't.",
  L("The skeleton finished the content", 'If you planned well, the content was finished in the skeleton', 290, 36),
  "And in principle, if I planned correctly in the skeleton, there should be almost no content corrections. The skeleton splits the writing: content is finished in planning, and the writing itself is language.",
  "So the mistakes you can still catch are most likely language mistakes.",
 ]),
 dict(mode='concept', active=4, title='What to check', script=[
  "So what do I check?",
  L("Punctuation", 'Punctuation: full stops · a comma after an opening phrase · no comma splices', 110, 32),
  "Punctuation. Maybe I missed a full stop or a comma. And no comma splices: two full sentences joined by just a comma.",
  L("Agreement", 'Agreement: "the cameras is" -> "the cameras are" · "this data ... they" -> "it"', 190, 32),
  "Agreement: singular and plural. Subject and verb. A pronoun that matches what it refers to.",
  L("Articles", 'Articles: "Government should ..." -> "The government should ..."', 270, 32),
  "Articles, a classic for Hebrew speakers: 'government should' becomes 'the government should'.",
  L("Missing words", 'Missing words, especially "not": one lost "not" reverses your position', 350, 32),
  "Missing words, especially 'not'. One missing 'not' turns your position upside down.",
  L("Examples tied back", 'Every example or comparison ends by tying back to the topic', 430, 32),
  "If I used an example or comparison in an argument paragraph, I make sure there's a sentence that ties it back to the topic. That's something you can add in ten or twenty seconds.",
 ]),
 dict(mode='concept', active=5, title='Cut repetition', script=[
  L("Repetition and padding", 'Repetition and padding: the same idea again, in other words', 110, 36),
  "I check there's no repetition or padding. Reminder: that's when I repeat the same idea in different words.",
  L("Before", '... which reduces the number of offences in the monitored areas. In other words, there will be less crime where the cameras are.', 210, 30),
  D("Cross out: In other words, there will be less crime where the cameras are."),
  "For example: I notice that at the end of a paragraph I have a sentence saying almost the same as before. Simply delete the whole sentence.",
  L("Just cross it out", 'Delete it with one clean line. No need to erase a whole sentence', 360, 34),
  "You don't need to fight with the eraser. To delete a whole sentence, just draw a line through it. It's not the neatest, but that's fine. They know it's a draft.",
 ]),
 dict(mode='concept', active=6, title='Focus and cohesion', script=[
  L("Focus and cohesion", 'Focus and cohesion: skim for missing connectors between sentences', 110, 36),
  "Focus and cohesion. I skim the essay and look for a missing connector between sentences, or something like that.",
  L("One connector can close a gap", 'Cameras identify faces instantly.  [ As a result, ]  investigations become shorter.', 220, 32),
  "Again, I can't fix the whole essay. It's a quick check. But skimming, maybe I find a spot where one connector closes the gap.",
  L("Choose the right relationship", 'Choose the connector by the relationship: cause, result, contrast, concession, example, addition', 330, 32),
  "And choose it by the relationship: cause, result, contrast. A connector signals a relationship; it can't create one.",
 ]),
 dict(mode='concept', active=7, title='How to correct', script=[
  "How do we make corrections?",
  L("Blank line + indent", 'Leave a blank line between paragraphs, and indent each first line', 110, 36),
  "First, we leave a blank line between paragraphs. We also indent the first line of each paragraph, so strictly we don't need the blank line. But we add it anyway, to have room for corrections.",
  L("Erase and rewrite", 'Where possible: erase and rewrite (you may use an eraser)', 210, 36),
  "Where possible, we erase and rewrite. You're allowed an eraser. Bring one that really erases, and test it. Not the one on the end of the pencil that tears the page and smears the graphite.",
  L("Insert with a caret", 'To insert a word: a caret  ^  and the word above it, written clearly', 310, 36),
  "You can also use that little insertion mark, the caret, and write the word above. But make it clear, so the rater understands you added a word here.",
  L("Only on the lines", 'Remember: write only on the lines. Anything outside them is not read.', 420, 34),
  "And remember: the sheets are scanned. Anything written outside the lines, including the margins, is not read.",
 ]),
 dict(mode='concept', active=8, title='Handwriting', script=[
  L("Hard to read = may hurt", 'An essay that\'s hard to read may hurt your score', 110, 38),
  "And while we're on clarity: an essay that's hard to read may hurt your score. If your handwriting is a problem, start practising now.",
 ]),
 dict(mode='concept', active=9, title='Proofread as you go', script=[
  "I talked about leaving two or three minutes at the end. But if you practise and see you're fine with time, there's another option.",
  L("Check each paragraph as you finish it", 'Option: proofread each paragraph right after you finish it', 110, 38),
  "Proofread during the writing. Every time you finish a paragraph, stop for a second, read it, check it's fine, and move on.",
  L("Why it works", 'Each paragraph has one clear job, so you can judge it on its own', 210, 36),
  "Why does this work? Yes, a main thread runs through the whole essay. But each paragraph has a very specific, clear job. Think of all our lessons: here's the opening, here's argument paragraph one, here's the rebuttal. We checked each one on its own.",
  L("Pro and con", 'Pro: easier to fix, even add two sentences.  Con: it can eat your time', 320, 36),
  "The advantage: you can fix things with less mess, you can even add two sentences. The disadvantage: you may run out of time if you spend too long. Practise it and see if it suits you.",
 ]),
 dict(mode='concept', active=10, title='Go to the weak spot', script=[
  L("Don't reread everything", 'With 2-3 minutes, you may not reread the whole essay', 110, 38),
  "With only two or three minutes at the end, we may not go over the whole essay.",
  L("Go to the paragraph that felt off", 'Go straight to the paragraph that felt weaker while you wrote it', 210, 38),
  "Often it's even better to go straight to a paragraph that felt a bit off while writing. Usually you can feel which paragraph sat well and which didn't.",
  "If you know you have a problematic paragraph, go and fix it. The rest of the essay is probably fine.",
  "That's the exam. When you practise, you'll also review each essay properly afterwards. That's the next lesson.",
 ]),
], T50)


# ================================================================= lesson 9: reviewing an essay (seg51)
SB_REV = ['Review, fix, rewrite', 'Why review yourself', 'Time each stage', 'Read the key lines',
          'Paragraph by paragraph', 'Lift the language', 'Wait a day', 'Sample essays', 'Strong samples',
          'Adequate samples', 'Weak samples', 'Write the other side']

REVIEW = lesson('vr50-h-review', 'Reviewing Your Essay', SB_REV, [
 dict(mode='title', title='Reviewing Your Essay', script=[
  "When you finish a practice essay, you don't just put it away. You review it, fix it, and rewrite it.",
 ]),
 dict(mode='concept', active=0, title='Review, fix, rewrite', script=[
  L("The order", 'Write -> wait a day -> review with the checklist -> fix -> rewrite  (-> a second reader, if you have one)', 110, 36),
  "Why? While learning, just like in the quantitative sections, we don't practise under time pressure at first. We look at questions from every angle.",
  L("Learning time vs. exam time", 'While learning: do your best work.  In simulations: 35 minutes, strictly.', 210, 36),
  "The same with the essay. I want to write as well as I can. Yes, the exam gives thirty-five minutes. In simulations I'll limit myself to thirty-five. But right now, I want to learn.",
 ]),
 dict(mode='concept', active=1, title='Why review yourself', script=[
  L("Finding your own mistakes", 'Finding your own mistakes makes you think', 110, 42),
  "One of the best ways to improve is to review your own essay. When I review myself, I have to think.",
  L("Not just reading comments", 'Reading someone else\'s comments is not the same: you may repeat the mistakes', 210, 36),
  "If someone just writes the mistakes for me, I only look at them, and I may repeat them or similar ones.",
  L("You go deep", 'You examine each paragraph: its parts, connectors, thread, repetition, language', 310, 36),
  "When I must find my own mistakes, I go much deeper: what parts the paragraph has, are the connectors in place, is the thread clear, is there repetition, is my language high enough?",
  L("'I could have done that myself'", 'Then, if you can, ask a teacher or a friend to read it: they will add what you could not find alone', 420, 34),
  "You'll say: wow, I could have done that myself. And if you have a teacher or a friend who can read it, show it to them after your own review. Their comments will then teach you the things you really couldn't find.",
 ]),
 dict(mode='concept', active=2, title='Time each stage', script=[
  "First, we review the timing.",
  L("A stopwatch", 'Use a stopwatch. Note the time of every stage:', 110, 38),
  "We don't just take thirty-five minutes and stop. We use a stopwatch, and at every stage we note how long it took.",
  L("The stages", 'planning (analysis, arguments, skeleton) · opening · argument 1 · argument 2 · rebuttal · closing · proofreading', 200, 32),
  "How long did planning take: analysis, finding arguments, the skeleton? The opening? Argument one? Argument two? The rebuttal? The closing?",
  L("A 5-6 minute opening = a problem", 'Opening took 5-6 minutes? That is a problem, and great news: now you can fix it', 320, 34),
  "Then I compare. If the opening took me five or six minutes, I have a problem. And that's excellent, because now I know what to shorten next time.",
 ]),
 dict(mode='concept', active=3, title='Read the key lines', script=[
  "Now the essay itself. First, a general pass. There's no time pressure now; this isn't proofreading, it's a review.",
  L("Read only", 'Read only:  the position (last sentence of the opening) + the key sentence of every paragraph', 110, 34),
  "I read the last sentence of the opening, my position, and then the first sentence of each paragraph: the key sentences.",
  L("In the rebuttal", 'In the rebuttal paragraph: the counterargument AND the weakening sentence', 210, 34),
  "In the rebuttal paragraph, I read both the counterargument and my weakening, which is in the middle of the paragraph.",
  L("Is the thread clear?", 'Does it make sense as a sequence? Do all the reasons support the stated position?', 310, 34),
  "Background doesn't matter now; it's fixed content. I check: is there a clear thread? Do the reasons actually support my position? Does this essay make sense?",
 ]),
 dict(mode='concept', active=4, title='Paragraph by paragraph', script=[
  "Now we go deep: every paragraph.",
  L("Inside each paragraph", 'Inside each paragraph: the flow of ideas, focus, cohesion', 110, 36),
  "We read it and check the flow of ideas inside the paragraph, its focus and cohesion.",
  L("Did it do its job?", 'Did it do its job?  (for the essay, and for the rater)', 200, 36),
  "We ask: did this paragraph achieve its goal? Remember, in each lesson every paragraph had a goal for the essay and a goal for the rater.",
  L("Example", 'The opening was supposed to make a strong first impression in language. Did it?', 290, 34),
  "The opening was supposed to create a great first impression in language. Did it or didn't it?",
 ]),
 dict(mode='concept', active=5, title='Lift the language', script=[
  L("Fix mistakes, lift the language", 'Correct language mistakes, and lift the language where you can', 110, 36),
  "We also fix language mistakes and lift the language where we can.",
  L("Precise, not flowery", 'Precise, formal words, not flowery ones:', 200, 36),
  "Not by stuffing in over-the-top expressions. There are plenty of words that aren't very high but upgrade the essay.",
  L("Swaps", 'a lot of -> considerable · get -> obtain · show -> demonstrate · so -> therefore · I mean -> that is', 280, 32),
  "Like: 'a lot of' becomes 'considerable'. 'Show' becomes 'demonstrate'. 'So' becomes 'therefore'. 'I mean' becomes 'that is'.",
  L("Only if it is accurate", 'Use a more formal word only when it means exactly what you want', 380, 34),
  "But use it only when it means exactly what you want. A difficult word used inaccurately costs more than a simple one.",
  L("Rewrite it", 'Fix everything you found and rewrite the essay', 480, 36),
  "I fix everything I find and rewrite the essay. Comparing the two versions shows me how far I've come.",
 ]),
 dict(mode='concept', active=6, title='Wait a day', script=[
  "A few more recommendations.",
  L("Don't review the same day", 'Don\'t review on the same day. Wait at least a night.', 110, 40),
  "First: don't review on the same day. Even after you write it, don't review it right away.",
  L("You're biased", 'Right after writing, you are too close to it, and less critical', 200, 36),
  "Why wait at least a night? Because right now I'm biased toward the essay I just wrote. An hour or two later, I'm still inside it. I'm less critical.",
  L("A day or two later", 'A day or two later, the mistakes are easier to see', 290, 36),
  "Come back after a day, maybe two, and you look at it with a more critical eye. Your mistakes are much easier to see.",
 ]),
 dict(mode='concept', active=7, title='Sample essays', script=[
  "A great way to improve: read official sample essays.",
  L("Three labels", 'Official English sample essays are labelled: Strong · Adequate · Weak', 110, 36),
  "The official English samples come in three labels: strong, adequate, and weak.",
  L("The most neglected topic", 'The essay is the part students tend to neglect most, yet it is 25% of the Verbal score', 210, 34),
  "And a reminder: the essay is the part students tend to invest in least, even though it's a quarter of the Verbal score.",
  L("Diagnose first, then look", 'Tip: read a sample, decide its level and why, then check the label', 310, 36),
  "A tip: read the sample first, decide what level it is and why, point to a specific passage, and only then look at the label.",
 ]),
 dict(mode='concept', active=8, title='Strong samples', script=[
  L("Why is it strong?", 'Strong: ask why. "The argument is well supported." "The language is precise."', 110, 34),
  "From strong essays, I try to understand why they're strong. The argument is really well supported. What precise language.",
  L("Take a paragraph apart", 'Go micro: key sentence · development · example · comparison · weakening (which type?)', 210, 34),
  "If you want to go deep, take a paragraph apart: here's the key sentence, here's the development, here's an example, a comparison, a weakening of this type or that.",
  L("Not all equal", 'Strong samples are not all equal, and not flawless', 320, 36),
  "And strong samples are not all the same. Some will make you say: wow, amazing. Others: fine, I could write something like that too.",
 ]),
 dict(mode='concept', active=9, title='Adequate samples', script=[
  L("Find the problems", 'Adequate: find what holds it back', 110, 40),
  "In adequate essays, I read and try to find the problems. Why is this one only adequate?",
  L("Typical problems", '"The development isn\'t enough here." "A link is missing." "The same point, repeated." "The language slips."', 200, 32),
  "The development isn't good enough here. A step in the explanation is missing. The same point comes back in other words. The language isn't right here.",
  L("Then fix it", 'Then ask: how would I fix it?', 320, 38),
  "I try to find the problems and also how they could be fixed.",
 ]),
 dict(mode='concept', active=10, title='Weak samples', script=[
  L("Weak: feel better", 'Weak: mostly, they make you feel better', 110, 40),
  "And the weak samples? The benefit there is mainly to feel good about yourself.",
  "It sometimes makes me laugh, but it can really help. You reviewed an essay, found loads of mistakes, and feel you can't write and you're not improving?",
  L("'I'm not that bad'", 'Read a few and you will say: "I\'m not as bad as I thought."', 250, 36),
  "Read a few weak essays and you'll say: I'm not as bad as I thought.",
 ]),
 dict(mode='concept', active=11, title='Write the other side', script=[
  "And one more tip, a very warm recommendation.",
  L("Same task, other side", 'Finished an essay? Write it again on the same task, from the other side', 110, 38),
  "You finished an essay on a topic. Now write on the same topic, from the other position. Argue against what you just argued.",
  L("It trains critical thinking", 'It trains critical thinking: arguments AND weakenings from the side you rejected', 220, 36),
  "This improves your critical thinking, because you force yourself to find arguments, and weakenings, from the other side.",
  L("Better than a new topic", 'Even better than moving straight to a new topic', 320, 38),
  "I recommend it even more than writing another essay on a new topic. One task, both sides, and only then the next task.",
  L("Review, fix, rewrite", 'Review -> fix -> rewrite', 420, 44),
  "So remember: review, fix, and rewrite. That's the end of this whole section on how to write an essay. One last workshop, and then the practice tasks.",
 ]),
], T50)


MODULES = [OPEN, OPEN_TPL, CLOSE, CLOSE_TPL, STRUCT, SKEL, ESSAY, PROOF, REVIEW]


# ================================================================= memory cards
MEMORY = [
 dict(id='mem-wr-open-close', after='vr50-h-closing-tpl', title='Opening & closing templates',
  intro='The bread of the sandwich: the opening comes from the task text, the closing from your own essay. Keep both short.',
  tables=[
   dict(title='Opening paragraph', head=['Template', 'Fill in'], rows=[
    ['Minimal', '[Rewritten background: who is doing what, and why]. However, some oppose this [move / proposal], and I [agree with them / believe it should nevertheless be adopted].'],
    ['Rewrite', '[Every sentence of the task text, shortened]. Supporters argue that [...]. Opponents, however, fear that [...]. I agree with the [former / latter], [although / provided that ...].'],
    ['Position options', 'I agree with the former. · I side with the critics. · In my view, [X] should [not] be [adopted].'],
   ]),
   dict(title='Closing paragraph', head=['Template', 'Fill in (and where each part comes from)'], rows=[
    ['Benefits summary (default)', 'In conclusion, [position = last line of the opening], since [benefit 1 = second half of key sentence 1], and also because [benefit 2 = second half of key sentence 2].'],
    ['Essay summary (advanced)', 'In conclusion, although [counterargument = first line of the rebuttal], I believe that [position], since [weakening]. Moreover, [benefit 1], and [benefit 2].'],
    ['Time-pressure line', 'In conclusion, [position], since, as shown above, its advantages outweigh its disadvantages.'],
   ])],
  tips=['Opening: background + dispute + your position (at the end). About 2-3 minutes. No empty phrases ("This is a problematic issue").',
        'Copying segments of the task text is fine, but not the whole task word for word. Struggling to rewrite? Use the minimal template.',
        'Closing: no new argument, no repeated counterargument. It must follow from the body.',
        'Never leave out the closing. No time? The one-line template.']),
 dict(id='mem-wr-skeleton', after='vr50-h-essay', title='Essay skeleton + 35-minute plan',
  intro='Plan the content first (short notes and chains), then write. Opening and closing are not in the skeleton: their content is known.',
  tables=[
   dict(title='The skeleton (basic structure 1)', head=['Paragraph', 'Write in the skeleton'], rows=[
    ['Argument 1 (your ace)', 'Argument + chain (~10 words: X -> step -> step -> result) + example or comparison'],
    ['Argument 2', 'A different reason + chain + example or comparison'],
    ['Rebuttal', 'Counterargument (their chain) + weakening: a NEW argument aimed at their weakest arrow'],
    ['Checks', 'Relevance to the exact question · flow in the whole essay · every arrow: "why would this lead to that?"'],
   ]),
   dict(title='35 minutes', head=['Minutes', 'Stage'], rows=[
    ['0-10', 'Read, analyse, find arguments and weakenings, choose a side, skeleton + chains'],
    ['10-13', 'Opening paragraph'],
    ['13-19', 'Argument paragraph 1'],
    ['19-25', 'Argument paragraph 2'],
    ['25-31', 'Rebuttal paragraph'],
    ['31-33', 'Closing paragraph'],
    ['33-35', 'Proofreading (2-3 minutes)'],
   ])],
  tips=['Argument 2 needed for the weakening? Basic structure 2: drop argument paragraph 2, richer rebuttal, longer opening.',
        'Always short on time? Opening -> argument 1 -> rebuttal -> (argument 2 if time) -> closing.',
        'The structure is a teaching aid, not an exam rule: let the task shape the paragraphs, and give each paragraph one job.',
        'Length: at least 25 lines, at most 50; good essays are usually about 30-40.']),
 dict(id='mem-wr-proofread', after='vr50-h-proofread', title='Proofreading checklist',
  intro='2-3 minutes at the end (or one quick check after each paragraph). Raters read a first draft: fix language, not content.',
  tables=[dict(title='Check', head=['What', 'Look for'], rows=[
    ['Punctuation', 'Full stops · comma after an opening phrase · no comma splices'],
    ['Agreement', 'Subject-verb (the cameras are) · singular/plural · pronouns (this data ... it)'],
    ['Articles', '"the government", "a database", "the police"'],
    ['Missing words', 'Especially "not" (it reverses your position)'],
    ['Examples', 'Each example or comparison ends by tying back to the topic'],
    ['Repetition', 'The same idea in other words: cross the sentence out'],
    ['Connectors', 'A missing link between sentences: add the connector that fits the relationship'],
    ['Weak spot', 'Go first to the paragraph that felt weaker while writing'],
   ])],
  tips=['Leave a blank line between paragraphs and indent each first line: room for corrections.',
        'Delete with one clean line; insert with a caret (^). Keep it clear.',
        'Write only on the lines, in pencil, legibly: an essay that\'s hard to read may hurt your score.',
        'A few small mistakes are fine. It is a draft.']),
 dict(id='mem-wr-practice', section='vr50-practice', after='vr50-h-review', title='Practice writing tasks',
  intro='Eight original tasks in the shape of the real exam: the situation, the change, both sides, then the question. Write each one in 35 minutes, on a 50-line sheet.',
  tables=[dict(title='Before you write: ask yourself', head=['#', 'Question'], rows=[
    ['1', 'Am I answering the exact question, every part of it?'],
    ['2', 'Does every arrow in my chains hold? "Why would this lead to that?"'],
    ['3', 'Did I state the other side\'s real reason, and answer its actual worry?'],
    ['4', 'Does every paragraph do one job, and does the closing follow from the body?'],
    ['5', 'Did I leave 2-3 minutes to proofread (punctuation, agreement, a missing "not")?'],
   ])] +
         [dict(title='Task %d · %s' % (i + 1, _T[k]['title']), head=['', ''],
               rows=[[p, ''] for p in _T[k]['paras']] + [[_T[k]['q'], '']]) for i, k in enumerate(PRACTICE)],
  tips=['How to practise: set a timer for 35 minutes. Spend the first 8-10 minutes on the skeleton: draft a chain (~10 words) for each argument and for the opponent\'s main argument, and find its weakest arrow.',
        'Then write on a 50-line sheet (at least 25 lines; about 30-40 is good), and leave 2-3 minutes to check with the proofreading checklist.',
        'Note the time of every stage. A day later, review the essay yourself (key lines first, then paragraph by paragraph), fix it and rewrite it; if you can, ask a teacher or a friend to read it.',
        'Best of all: write the same task again from the other side.']),
]

MODULES = split_task_slides(MODULES)
